### ISSUE TITLE
HTTP server's /_xtdb/entity endpoint doesn't use the tx-id parameter

### ISSUE THREAD

**Issue by caleb** [xtdb/crux#1616]
When calling the http server’s `/_xtdb/entity` endpoint with the `tx-id` parameter, the server ignores it and just returns the latest version of the document.

The issue is that the `xtdb.http-server.entity/search-entity` function doesn't pass the tx-id argument along when finding the db instance:

https://github.com/xtdb/xtdb/blob/5e1d822602a39fcc6a448f959c294def21988aa1/modules/http-server/src/xtdb/http_server/entity.clj#L163-L166

I also noticed that the `tx-id` parameter isn't passed along when doing queries:

https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/modules/http-server/src/xtdb/http_server/query.clj#L76-L78

If this is on purpose I can try to patch the documentation, otherwise I can update those two functions to use the `tx-id` parameter to find the db.

**Comment by refset** [comment]
Hi @caleb thanks for opening the issue - I agree the documentation is definitely out of step with the code (I'll dig into this soon!). It looks like `tx-id` is missing from the query endpoint also https://github.com/xtdb/xtdb/blob/5e1d822602a39fcc6a448f959c294def21988aa1/modules/http-server/src/xtdb/http_server/query.clj#L76-L85

I hope you aren't too blocked while this remains unresolved.

**Comment by jarohen** [comment]
Hey @caleb, thanks for the heads-up :pray: Fix will go in with 1.19.0.

James
