### ISSUE TITLE
invalid doc errors not going away

### ISSUE THREAD

**Issue by tkovis** [xtdb/crux#1617]
I'm still using pro.juxt.crux/crux-core {:mvn/version "1.18.1-beta1"} but I'm migrating to latest xtdb after writing this issue and checking if the issue persists.

I ended up in an error state and couldn't find a way out expect deleting db and starting fresh. In the error state I couldn't await transactions because I would keep getting the error:
```
; Execution error (ExceptionInfo) at crux.tx.conform/check-doc (conform.clj:16).
; invalid doc
```
I narrowed it down to an invalid match transaction:
```
  (let [node @node]
    (->> [[:crux.tx/put {:crux.db/id 2}]]
         (crux/submit-tx node)
         (crux/await-tx node)
         (crux/tx-committed? node)))
=> true
  (let [node @node]
    (->> [[:crux.tx/match 2 {:crux.db/id 2}] ;; correct match no issues
          [:crux.tx/put {:crux.db/id 2}]]
         (crux/submit-tx node)
         (crux/await-tx node)
         (crux/tx-committed? node)))
=> true
  (let [node @node]
    (->> [[:crux.tx/match {:crux.db/id 2}] ;; no eid, only the doc
          [:crux.tx/put {:crux.db/id 2}]]
         (crux/submit-tx node)
         (crux/await-tx node)
         (crux/tx-committed? node)))
=> Execution error (ExceptionInfo) at crux.tx.conform/check-doc (conform.clj:16). invalid doc
  (crux/sync @node)
=> Execution error (ExceptionInfo) at crux.tx.conform/check-doc (conform.clj:16). invalid doc
  (let [node @node]
    (->> [[:crux.tx/put {:crux.db/id 2}]]
         (crux/submit-tx node)
         (crux/await-tx node)
         (crux/tx-committed? node)))
=> Execution error (ExceptionInfo) at crux.tx.conform/check-doc (conform.clj:16). invalid doc
```

This is not a state that a normal application would end up in, but I'd still like to know if there's a way out if mistakes are made.

**Comment by tkovis** [comment]
Yes it persists even in xtdb

```
  (let [node @node]
    (->> [[::xt/put {:xt/id 2}]]
         (xt/submit-tx node)
         (xt/await-tx node)
         (xt/tx-committed? node)))
=> true
  (let [node @node]
    (->> [[::xt/match 2 {:xt/id 2}]
          [::xt/put {:xt/id 2}]]
         (xt/submit-tx node)
         (xt/await-tx node)
         (xt/tx-committed? node)))
=> true
  (let [node @node]
    (->> [[::xt/match {:xt/id 2}]
          [::xt/put {:xt/id 2}]]
         (xt/submit-tx node)
         (xt/await-tx node)
         (xt/tx-committed? node)))
; Execution error (ExceptionInfo) at xtdb.tx.conform/check-doc (conform.clj:18).
; invalid doc
  (xt/sync @node)
; Execution error (ExceptionInfo) at xtdb.tx.conform/check-doc (conform.clj:18).
; invalid doc
  (let [node @node]
    (->> [[::xt/put {:xt/id 2}]]
         (xt/submit-tx node)
         (xt/await-tx node)
         (xt/tx-committed? node)))
; Execution error (ExceptionInfo) at xtdb.tx.conform/check-doc (conform.clj:18).
; invalid doc
```

**Comment by refset** [comment]
Hi @tkovis thanks for reporting this. We will take a look very soon!

> I'd still like to know if there's a way out if mistakes are made

We don't currently provide any convenient utilities for doing so, and I wouldn't ever recommend attempting it on a production database (please speak to us first instead!), but you might have some success with manually removing the offending entry from the underlying tx-log - which is a little simpler if you are using a JDBC backend. Otherwise though, it is much simpler to start with a clean tx-log if you can (i.e. during dev / testing).

**Comment by refset** [comment]
Hi again - we found a bug in the Lucene module we think was related to this - were you using Lucene here? It has been fixed via https://github.com/xtdb/xtdb/issues/1627 - pending release soon(!)

**Comment by tkovis** [comment]
Yes I was using Lucene
