### ISSUE TITLE
Remove requirement  to include the same logic vars in all legs of an or clause?

### ISSUE THREAD

**Issue by maacl** [xtdb/crux#1618]
Are there any plans to remove the need to include the same logic vars in all legs of an or clause? They create a lot of noice, and it seems to me that the missing clause [(any? x]) could be auto generated if need be? I might be missing something.

Inserting dialog with @refset  below:

> refset:xtdb:
> Hi, there are no immediate plans to change this behaviour, although I have certainly experienced the same thoughts/questions. The reasoning behind the current behaviour is that it is an accurate implementation of the axioms of Datalog. The [(any? x)] clauses definitely could be inferred/auto-generated, but I imagine there may be occasions during development where, being implicit, that makes things more confusing (despite the reduced line count) - it is probably worth experimenting with something like this in userspace though. Alternatively, an option could be added to the query like :ignore-non-matching-rule-leg-vars true
> Another thought is that we could add a built-in pred, equivalent to any? but that accepts varargs (which clojure.core/any? sadly doesn't), that way you could at least consolidate everything into a single clause [(any? x y z)] (edited) 
> 
> maacl:
> The latter would definitely be a nice bit of sugar. I might just implement my own version of this for now.
> 
> refset:xtdb: 
> Cool, I'll be curious to see what you come up with! We should probably create a more permanent issue or GH discussion to track this though - would you like to do the honours? Otherwise I'm happy enough to just briefly copy and paste these notes myself

**Comment by jarohen** [comment]
This was fixed in b91fda039d0d9d2fa2a1866984d9c65afb8b5ee3 :slightly_smiling_face: The requirement has been weakened - it's now that all vars _returned_ from an or-clause/rule must be the same in every clause, but doesn't require that each clause needs to use all of the input vars.
