### ISSUE TITLE
curl POST EDN format not working

### ISSUE THREAD

**Issue by franz65** [xtdb/crux#1620]
### Discussed in https://github.com/xtdb/xtdb/discussions/1619

<div type='discussions-op-text'>

<sup>Originally posted by **franz65** September 17, 2021</sup>
Hi,
I have a running xtdb node and I'm trying the examples on official documentation https://xtdb.com/reference/http.html#submit-tx
When I try to put documents it works fine using JSON format, but if I try using EDN format I always get an error {:error "Malformed \"application/edn\" request."}

	curl -X POST \
	     -H "Content-Type: application/json" \
	     -H "Accept: application/json" \
	     -d '{"tx-ops": [["put", {"xt/id": "ivan", "name": "Ivan", "last-name": "Petrov"}],
	          	         ["put", {"xt/id": "boris", "name": "Boris", "last-name": "Petrov"}],
	          	         ["delete", "maria", "2012-05-07T14:57:08.462-00:00"]]}' \
	     $XTDB_URL/_xtdb/submit-tx

works fine and I can retrieve the documents uploaded.
 
      curl -X POST \
	     -H "Content-Type: application/edn" \
	     -H "Accept: application/edn" \
	     -d '{:tx-ops [[::xt/put {:xt/id :ivan, :name "Ivan" :last-name "Petrov"}],
	          	       [::xt/put {:xt/id :boris, :name "Boris" :last-name "Petrov"}],
	          	       [::xt/delete :maria #inst "2012-05-07T14:57:08.462-00:00"]]}' \
	     $XTDB_URL/_xtdb/submit-tx

always answers with the error message  {:error "Malformed \"application/edn\" request."}

I have tried with very simple edn documents, but nothing works, the JSON version, instead, works perfectly.

Thanks to everybody

</div>

**Comment by refset** [comment]
Hi @franz65 I think the issue is that you are using a namespace alias `::xt/put` (a Clojure run-time thing), whereas when using raw edn here you need to use the fully qualified namespace `:xtdb.api/put` - please replace accordingly and see if that works :)

**Comment by jarohen** [comment]
Hey @franz65, thanks for reporting this. `::xt/put` isn't valid EDN, I'm afraid - namespace aliases aren't permitted. Could you replace with `:xtdb.api/put` and re-check? 

Also, did you come across this in any of our documentation? If so, could you send us a link and we'll get it corrected :smile: 

Cheers,

James

**Comment by jarohen** [comment]
heh, @refset beat me to it :runner:

**Comment by franz65** [comment]
Hy @jarohen,
thanks for your answer. Using the command :xtdb.api/put it works fine.
I got the original code from here [https://xtdb.com/reference/http.html#submit-tx](https://xtdb.com/reference/http.html#submit-tx) but I found similar code in other places too, for example here [https://nextjournal.com/xtdb-tutorial/start](https://nextjournal.com/xtdb-tutorial/start) but here it's not used from CURL.
     
        (xt/submit-tx node [[::xt/put manifest]])



This version of the code works fine 
        
     curl -X POST \
	     -H "Content-Type: application/edn" \
	     -H "Accept: application/edn" \
	     -d '{:tx-ops [[:xtdb.api/put {:xt/id :joe, :name "Joe" :last-name "One"}],
	          	       [:xtdb.api/put {:xt/id :ben, :name "Ben" :last-name "Two"}]]}' \
	     $XTDB_URL/_xtdb/submit-tx

**Comment by franz65** [comment]
Hi,
scaffolding from Luminus generate the same kind of code: 

     (:require
       [xtdb.api :as xt]
        ...
        ...
      (xt/submit-tx node [[::xt/put user-doc]]))))

**Comment by jarohen** [comment]
> I got the original code from here https://xtdb.com/reference/http.html#submit-tx

Thanks for letting us know - fixed! Yeah - the NextJournal and Luminus ones are both correct, as you alluded to, but it is a bit of a gotcha when translating those examples to cURL. We'll have a think on how to make this clearer :)

James
