### ISSUE TITLE
rocksdb SIGSEV on WSL2

### ISSUE THREAD

**Issue by ozimos** [xtdb/crux#1621]
[hs_err_pid22175.log](https://github.com/xtdb/xtdb/files/7189591/hs_err_pid22175.log)
SIGSEV when starting up a rocksdb node in Windows Subsystem for Linux (WSL2)
Only happens during tests, not when connecting to node using REPL

**Comment by ozimos** [comment]
The SIGSEV happens on every test run in my main project. I tried to create an error repro repo here https://github.com/ozimos/xtdb_rocksdb_repro but was able to reproduce the error only for one test run. The hs_err log is in the repo

**Comment by refset** [comment]
Thanks for the report and repro. I'm not familiar with how Kaocha works, but I wonder if it is possible that the node isn't stopped correctly between tests, as this looks similar to what is described in https://github.com/facebook/rocksdb/issues/5038

**Comment by refset** [comment]
With INFO logging turned on, what do you see in the console? If the tx-ingester thread (which looks to be what's causing the issue) isn't closing properly then it probably won't be logging this message during `.close` of the node https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/core/src/xtdb/tx.clj#L435

**Comment by ozimos** [comment]
> Thanks for the report and repro. I'm not familiar with how Kaocha works, but I wonder if it is possible that the node isn't stopped correctly between tests, as this looks similar to what is described in [facebook/rocksdb#5038](https://github.com/facebook/rocksdb/issues/5038)

Thanks for the hint.  I'll look in this direction

**Comment by ozimos** [comment]
The test completes successfully, then the JVM crashes. The XTDB node is stopped correctly. Here is my console output

```
INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO  xtdb.tx - Started tx-ingester
WARN  xtdb.api - MALLOC_ARENA_MAX not set, memory usage might be high, recommended setting for XTDB is 2
INFO  xtdb.tx - Shut down tx-ingester
INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000007e0, pid=3630, tid=5288
```

**Comment by ozimos** [comment]
After enabling XTDB logging Problematic frame has changed. Here are some new log
[hs_err_pid6359.log](https://github.com/xtdb/xtdb/files/7190700/hs_err_pid6359.log)
[hs_err_pid8312.log](https://github.com/xtdb/xtdb/files/7190701/hs_err_pid8312.log)
s
[hs_err_pid8728.log](https://github.com/xtdb/xtdb/files/7190703/hs_err_pid8728.log)

**Comment by ozimos** [comment]
I have found the problem. My docker postgres container did not have the database and user account specified in the xtdb config.

**Comment by jarohen** [comment]
Thanks for letting us know, @ozimos :pray:
