### ISSUE TITLE
HTTP server returns 0 bytes for some queries that should return an empty set

### ISSUE THREAD

**Issue by caleb** [xtdb/crux#1622]
Hi again (tired of me yet? :))

I am working on a ruby client to XTDB and since I'm new to datalog I'm sure I'm sending it terrible queries.

I've noticed that some queries to the HTTP server return 0 bytes, rather than returning an empty set. The same queries executed directly on the db return an empty set.

You should be able to test the curl statements below against an empty database and get the same results.

Here's an example query:

```clojure
{:find [$eid $id $name]
 :where [[$eid :expense-type/id $id]
         (or (and [$eid :expense-type/id $id]
                  [(clojure.core/> $id 250N)]
                  [(any? $name)])
             (and [$eid :expense-type/name $name]
                  [(clojure.string/starts-with? $name "C")]
                  [(any? $id)]))]
 :keys [eid id name], :in [$kind]}
```

I passed `[:expense-type]` as the args to the query.

Here's an example curl query via POST:

```
curl -v -H 'Accept: application/edn' -H 'Content-Type: application/edn' -d '{:query {:find [$eid $id $name], :where [[$eid :expense-type/id $id] (or (and [$eid :expense-type/id $id] [(clojure.core/> $id 250N)] [(any? $name)]) (and [$eid :expense-type/name $name] [(clojure.string/starts-with? $name "C")] [(any? $id)]))], :keys [eid id name], :in [$kind]}, :in-args [:expense-type]}' 'localhost:17678/_xtdb/query'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 17678 (#0)
> POST /_xtdb/query HTTP/1.1
> Host: localhost:17678
> User-Agent: curl/7.64.1
> Accept: application/edn
> Content-Type: application/edn
> Content-Length: 306
>
* upload completely sent off: 306 out of 306 bytes
< HTTP/1.1 200 OK
< Content-Type: application/edn; charset=utf-8
< Content-Length: 0
< Server: Jetty(9.4.36.v20210114)
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

Here's the same query via GET:

```
curl -g -X GET -H "Accept application/edn" 'localhost:17678/_xtdb/query?query-edn=%7B%3Afind%20%5B%24eid%20%24id%20%24name%5D%2C%20%3Awhere%20%5B%5B%24eid%20%3Aexpense-type%2Fid%20%24id%5D%20(or%20(and%20%5B%24eid%20%3Aexpense-type%2Fid%20%24id%5D%20%5B(clojure.core%2F%3E%20%24id%20250N)%5D%20%5B(any%3F%20%24name)%5D)%20(and%20%5B%24eid%20%3Aexpense-type%2Fname%20%24name%5D%20%5B(clojure.string%2Fstarts-with%3F%20%24name%20%22C%22)%5D%20%5B(any%3F%20%24id)%5D))%5D%2C%20%3Akeys%20%5Beid%20id%20name%5D%2C%20%3Ain%20%5B%24kind%5D%7D&in-args-edn=%5B%3Aexpense-type%5D'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 17678 (#0)
> GET /_xtdb/query?query-edn=%7B%3Afind%20%5B%24eid%20%24id%20%24name%5D%2C%20%3Awhere%20%5B%5B%24eid%20%3Aexpense-type%2Fid%20%24id%5D%20(or%20(and%20%5B%24eid%20%3Aexpense-type%2Fid%20%24id%5D%20%5B(clojure.core%2F%3E%20%24id%20250N)%5D%20%5B(any%3F%20%24name)%5D)%20(and%20%5B%24eid%20%3Aexpense-type%2Fname%20%24name%5D%20%5B(clojure.string%2Fstarts-with%3F%20%24name%20%22C%22)%5D%20%5B(any%3F%20%24id)%5D))%5D%2C%20%3Akeys%20%5Beid%20id%20name%5D%2C%20%3Ain%20%5B%24kind%5D%7D&in-args-edn=%5B%3Aexpense-type%5D HTTP/1.1
> Host: localhost:17678
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/edn; charset=utf-8
< Content-Length: 0
< Server: Jetty(9.4.36.v20210114)
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Comment by refset** [comment]
> tired of me yet? :)

Never! :relieved: 

This isn't a complete answer to the issue, since I can't personally shine any light on whether or not returning 0 bytes or `[]` (an empty vector/list) is "more correct", but I realise now that we haven't explained the bag vs. set semantics of the API in the `http-server` documentation.

Unlike when running in-process, where an XT query returns a set by default, over HTTP the results are always streamed as a bag (and therefore may contain duplicates).

You can see here in the remote client API that the streamed results will get converted into a set, to keep the local & remote API behaviours aligned:
https://github.com/xtdb/xtdb/blob/20a2632a18a36dae2e915ab032307ce0c5b3e150/modules/http-client/src/xtdb/remote_api_client.clj#L140-L144

**Comment by caleb** [comment]
Thanks for the heads up on bags vs sets.

What made me think it's a bug is that other queries return an empty list:

```clojure
{:find [?eid] :where [[?eid :xt/id :non-existent]]}
```

```
curl -H 'Accept: application/edn' -H 'Content-Type: application/edn' -d '{:query {:find [?eid] :where [[?eid :xt/id :non-existent]]}}' 'http://localhost:17678/_xtdb/query'
()
```

I just read the EDN spec and realize now that EDN doesn't need to have a single top-level map/list/vector/element like JSON, so maybe when encoding in EDN http-server should always return its results as multiple EDN objects, rather than wrapping them up in a top-level list. I'm half joking, but this would make the behavior consistent. It would also remove the need for the remote-api-client to look at parser exceptions to detect the end of the list when parsing from a stream:

https://github.com/xtdb/xtdb/blob/20a2632a18a36dae2e915ab032307ce0c5b3e150/modules/http-client/src/xtdb/remote_api_client.clj#L19-L34

When requesting JSON the server also returns an empty body, which is not valid JSON, so that might actually be a bug.

**Comment by refset** [comment]
Hi @caleb - apologies for the long turn around to dig into this properly!

Unfortunately though I can't seem to reproduce the results of your errant `curl` commands. Instead I correctly get `Content-Length: 2` in the header and `()` in the results in all 3 cases you shared - but nothing relevant in our http-server code has changed, that I can see. I tested `master` (@https://github.com/xtdb/xtdb/commit/90f2d365dc42b78a6170f2e2da2e7d7386b567e9) in the repl, and also the `1.19.0` and `1.20.0` Docker sample images (`juxt/xtdb-standalone-rocksdb`).

Which OS and version of `curl` were you using? Did you have anything that might have been proxying requests between the xtdb-http-server endpoint and wherever you were running the command? Can you describe how exactly you were running XT? (which version? what was the config map? via Docker? etc.)

**Comment by caleb** [comment]
Hi @refset,

I just tried my curl examples again and I now get a consistent empty list with `Content-Length: 2`.

I don't know what was going on before because I was getting `Content-Length: 0` in both curl and in my Ruby HTTP client, but now it seems to work.

I was running my XTDB (1.19.0-beta1) in a Docker container on macOS. I updated to the new version of macOS since the original post, but I was also getting an empty result from my ruby code running in a docker container.

Thanks for the help, I'm stumped on what caused this, but it seems to be working now.

Caleb

**Comment by refset** [comment]
Hmm, how weird! Thanks for circling back to this again though.

I'll close this issue for now in the _hope_ that the underlying cause was something very subtle and strange about your dev environment and not XT itself - but if anyone else out there reading encounters something similar then please feel free to re-open :)
