### ISSUE TITLE
Reference documentation transaction function Creating / Updating

### ISSUE THREAD

**Issue by tkovis** [xtdb/crux#1633]
In https://xtdb.com/reference/1.19.0-beta1/transactions.html#_creating_updating it says 
"The document should use the ::xt/fn key." but the example demonstrates the use of :xt/fn. Mistakingly using the wrong one (and not realising the mistake) results in
```
08:03:23.806 [xtdb-tx-subscription-1] DEBUG xtdb.tx - Transaction aborted: {:xtdb.api/tx-time #inst "2021-09-28T05:03:23.793-00:00", :xtdb.api/tx-id 14}
```
and someone scratching their head wondering how/why transactions get aborted and how to figure it out.

**Comment by refset** [comment]
Thanks @tkovis for pointing this out :pray: it's a very subtle difference! Maybe it can all be made/presented simpler still, but for now I have added a couple of sentences that should prevent others experiencing the same pain.
