### ISSUE TITLE
Range Predicate with arguments

### ISSUE THREAD

**Issue by rowlandwatkins** [xtdb/crux#1636]
Hi folks,

I'm looking to see if I can use a range predicate with an argument _that is not bound_ within the query itself: 

```
    (xt/q
      (xt/db node)
      '{:find [p]
        :where [[p :age a]
                [(> 18 a)]]})
```

In the above example I'd like to pass 18 as a variable from the function running this query rather than hardcoding as part of the the range predicate:

```
(defn my-query
   [adult]
    (xt/q
      (xt/db node)
      '{:find [p]
        :where [[p :age a]
                [(> adult a)]]}))
```

I've attempted using :args and :in for this but in both cases I get _Range constraint refers to unknown variable: adult_

Any tips would be most welcome

If this is not possible, I suppose I have another option of writing a macro!

Cheers,

Rowland

**Comment by refset** [comment]
Hey (again) @rowlandwatkins :)

I think you should have luck with careful quoting + constructing edn forms manually like this:

```clojure
(defn my-query
   [adult]
    (xt/q
      (xt/db node)
      {:find '[p]
        :where ['[p :age a]
                [(list '> adult 'a)]]}))
```

**Comment by rowlandwatkins** [comment]
@refset magnificent, thanks so much for the tip - works like a charm! It was the list that I was missing. Closing.

**Comment by refset** [comment]
Great, it was a good question. I'll add the tip to the docs now. In case anyone else was wondering, `list` is not some special XTDB Datalog thing, it's just a built-in Clojure function available (`clojure.core/list`).
