### ISSUE TITLE
Valid Time travel for only a single entity

### ISSUE THREAD

**Issue by rowlandwatkins** [xtdb/crux#1637]
Hi folks,

Is it possible for the XTDB snapshot machinery to load a single entity for a certain valid-time, but then join against other entities using their `latest` valid-time? In effect, I'd like to time travel on only one entity, not the sub-graph (not sure what else to call it) that's formed in the join.

Thanks in advance!

Rowland

**Comment by refset** [comment]
Hey @rowlandwatkins I can't think of a way to achieve that right now, as the query entity resolver (& cache) is designed to operate at a single point in time. However you might be able to work around this using a `with-tx` speculative transaction to (re-)put the single entity at the relevant point in time that you would like to perform the joins - let me know if you'd like a quick example.

**Comment by rowlandwatkins** [comment]
Woah, that's an interesting idea - basically using the speculative transaction to bring everything together - I'll take a look at the with-tx docs and have a go, thanks so much for the suggestion! I'll report back!

**Comment by refset** [comment]
Hey @rowlandwatkins did you get a chance to try out that idea?
