### ISSUE TITLE
Lucene module - wildcard-text-search doesn't respect query :timeout

### ISSUE THREAD

**Issue by xlfe** [xtdb/crux#1654]
I'm seeing the following query completely ignoring the :timeout option
```
(#xtdb.query_state.QueryState{:query-id "01dd4d16-0fb9-4786-9b71-0e489a089921",
                              :started-at #inst "2021-11-03T12:36:32.862-00:00",
                              :finished-at nil,
                              :status :in-progress,
                              :query {:find [?s ?e], :in [?term], :limit 1000, :timeout 1000, :where [[(wildcard-text-search ?term) [[?e ?v ?a ?s]]]]},
                              :error nil})
```

Note: @refset  has added this as a todo to #1599 

* This is with lmdb and ~1.6m documents
* The ?term that causes this is likely to match many documents (ie >10%)
* xtdb responds to new queries, but this query has now run for > 1hr ie unlikely to every complete
* htop shows `20   0 27.1G 18.0G 7139M R 99.3 56.8 54:54.05 xtdb-lucene-fsy`

**Comment by refset** [comment]
Thanks again for opening this issue @xlfe - the next release should avoid this happening again :crossed_fingers:
