### ISSUE TITLE
Passing empty set for an unused collection query parameter will return empty results. I think it should not affect returned results as not passing it.

### ISSUE THREAD

**Issue by xuelin-wang** [xtdb/crux#1680]
Say I have a query that returns 1 results when passing models.
(def q '{:find '[(pull v? [*])] :in '[[models ...] ] :where '[[v? :x/type :v] [v? :v/model models]] :limit 10})
(xt/q (xt/db node) q ["model-a"]) returns 1 result.

Now if I add an extra collection argument:
(def q '{:find '[(pull v? [*])] :in '[[models ...] [x ...]] :where '[[v? :x/type :v] [v? :v/model models]] :limit 10})
(xt/q (xt/db node) q ["model-a"] []) returns 0 result.
but below returns 1 result:
(def q '{:find '[(pull v? [*])] :in '[[models ...] [x ...]] :where '[[v? :x/type :v] [v? :v/model models]] :limit 10})
(xt/q (xt/db node) q ["model-a"] [1]) returns 1 result.

**Comment by jarohen** [comment]
Hey @xuelin-wang, thanks for getting in touch :wave: 

I'm afraid, as I understand it, this is correct behaviour, and similar to what would happen if you were to execute a similar query in a SQL database. Datalog implicitly joins all of the clauses you provide - as inner joins if there are variables that it can unify, and cross joins if the clauses have no variables in common (as in this case). Given one side of the cross join has no elements, the result of the cross join will also have no elements, even if there are elements on the other side.

HTH,

James

**Comment by xuelin-wang** [comment]
Thanks for the explanation! I need remove unused input variables.
