### ISSUE TITLE
The Second Chance cache should be stable

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1702]
Despite previous efforts to improve the stability of the Second Chance cache in https://github.com/xtdb/xtdb/pull/1469 there has been a new report of the cache misbehaving in real-world scenarios - specifically, during a bulk-querying case reported by @sw1nn, where the application usage is essentially a long-running export job that makes extensive use of the ability to run many queries against a consistent `db`.

Based on the following stack trace, it seems that the problem occurred in the `canonical-buffer-cache`, which was introduced https://github.com/xtdb/xtdb/pull/1469 (the same PR).

> I am seeing xtdb(1.20) spinning in the loop recur [here](https://github.com/xtdb/xtdb/blob/421db6dfe3bbcc57dac2db8eeafb9ece2a4703d5/core/src/xtdb/cache/second_chance.clj#L27)
> I haven't grokked (the need for) the reflective peeking into the guts of the ConcurrentHashMap, so not sure what's going on here.
> Stack Trace:
```
"async-thread-macro-1" #125 daemon prio=5 os_prio=0 cpu=17402880.79ms elapsed=22906.55s tid=0x000055b584fba800 nid=0x114 runnable  [0x00007f00ed809000]
   java.lang.Thread.State: RUNNABLE
        at xtdb.cache.second_chance$random_entry.invokeStatic(second_chance.clj:27)
        at xtdb.cache.second_chance$random_entry.invoke(second_chance.clj:15)
        at xtdb.cache.second_chance$move_to_cooling_state.invokeStatic(second_chance.clj:97)
        at xtdb.cache.second_chance$move_to_cooling_state.invoke(second_chance.clj:91)
        at xtdb.cache.second_chance$move_to_cold_state.invokeStatic(second_chance.clj:136)
        at xtdb.cache.second_chance$move_to_cold_state.invoke(second_chance.clj:123)
        at xtdb.cache.second_chance$resize_cache.invokeStatic(second_chance.clj:143)
        at xtdb.cache.second_chance$resize_cache.invoke(second_chance.clj:138)
        at xtdb.cache.second_chance.SecondChanceCache.computeIfAbsent(second_chance.clj:64)
        at xtdb.cache$compute_if_absent.invokeStatic(cache.clj:10)
        at xtdb.cache$compute_if_absent.invoke(cache.clj:9)
        at xtdb.kv.index_store$canonical_buffer_lookup.invokeStatic(index_store.clj:568)
```

The current workaround in place is to manually override the default cache to use LRU (instead of Second Chance) in ~all cases, which has successfully mitigate the issue(s) so far. However, this workaround has exposed potentially another key bit of information:

> whilst reduced in frequency, we are still seeing OOMKills on the JVM. These have been happening before the workaround and need to be analysed. Perhaps there's an unrelated leak and that contributed to pressure on the second_chance cache, triggering the issue.

Also:

> we seem to have a step in the JVM thread count since implementing the workaround - possibly unrelated

There has also been discussion/speculation about the root cause:

> if there are nil entries in the CHM then this could spin, but perhaps there are guarantees elsewhere that this can't happen?

> the check of isEmpty() before entering the loop/recur may not be strong enough (possibly depending on single-threaded or multi-threaded usage). My understanding is that size/isEmpty for a CHM is more of an estimate than a guarantee because of the concurrent nature of access. Adding an additional check in the loop/recur to see whether you're back to where you started without finding an entry seems like reasonable thing to try. (i.e. when i == start for the 2nd time ) https://stackoverflow.com/questions/37690525/multiple-threads-checking-map-size-and-conccurency

**Comment by sw1nn** [comment]
Regarding:
> we seem to have a step in the JVM thread count since implementing the workaround - possibly unrelated

I'm fairly confident that this isn't directly an xtdb issue, but a separate code change introduced at nearly the same time as the above investigation was leaking ~25k threads, and with each thread allocating a small stack this likely contributed to the OOM.
