### ISSUE TITLE
depstar is deprecated and archived; switch to tools.build

### ISSUE THREAD

**Issue by seancorfield** [xtdb/crux#1708]
`depstar` has been deprecated and archived for six months now. I'm encouraging everyone to migrate to `tools.build`. My `build-clj` wrapper makes it easier to switch from `depstar` to `tools.build`.

**Comment by jarohen** [comment]
Cheers @seancorfield :pray:

**Comment by jarohen** [comment]
Really painless, cheers @seancorfield :pray: One day I'll migrate XT proper to use deps.edn/tools.build...
