### ISSUE TITLE
Pull shouldn't throw errors when attempting forward joins with non-ID types 

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#1710]
(from @refset) 

forward join in a pull where the stored value is a list

**Comment by jarohen** [comment]
@refset: we have a test that's quite similar to this already, and passes - `xtdb.pull-test/test-missing-forward-join`. any idea what's different in your case?

**Comment by refset** [comment]
As per the test, this isn't a bug as such, more just a confusing/unhelpful error message.
