### ISSUE TITLE
MySQL tx_time shouldn't be in the future

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1716]
From @realgenekim via Clojurians #xtdb
> Here’s the strange behavior on transactions using JDBC, running Graal 21 Java 17 in Rosetta mode on Apple M1.  I copied this code from https://gist.github.com/alndvz/89931bb8f16867fd5f2e28d36ff85be9
> Everything works as expected when running with local datastores, but strange things happened when I used JDBC on MySQL.  In short, the transaction time is 8 hours in the future.  So, for hours, I was trying to figure out why I couldn’t see the effects of any of my transactions.
> I finally noticed that when no valid-time is specified in the transaction, the :tx-time returned from the submit-tx is 8 hours in the future.  This is when no timezone is specified for the JVM.
> PS: (I tried adding  -Duser.timezone=UTC, but then await-tx never returns — presumably it will finally return in 8 hours?  I see the transaction in MySQL.)
> See below.

```clojure
(defn prepare-docs [docs]
  (mapv (fn [doc]
          ;[::xt/put doc #inst "2021-01-04T18:00:00.000-00:00"]) docs))
          ;[::xt/put doc]) docs
          [::xt/put doc (java.util.Date.)]) docs))

(defn prepare-docs-bare [docs]
  (mapv (fn [doc]
          ;[::xt/put doc #inst "2021-01-04T18:00:00.000-00:00"]) docs))
          [::xt/put doc]) docs))
          ;[::xt/put doc (java.util.Date.)]) docs)

(def tx (xt/submit-tx db/xtdb-node (prepare-docs-bare products-1)))
=> #'genek.xtdbtest/tx
tx
=> #:xtdb.api{:tx-id 6672, :tx-time #inst"2022-02-28T04:52:15.798-00:00"}
(java.util.Date.)

;;; ^^^. note the tx-time!  8 hours in future

=> #inst"2022-02-27T20:52:22.414-00:00"

;;; ^^^ current time
```
> Note that entity-history doesn’t include :tx-id 6672:
```clojure
(def history (xt/entity-history (xt/db db/xtdb-node) :towel1 :desc))
=> #'genek.xtdbtest/history
history
=>
[#:xtdb.api{:tx-time #inst"2022-02-27T20:49:46.884-00:00",
            :tx-id 6670,
            :valid-time #inst"2022-02-27T20:49:46.884-00:00",
            :content-hash #xtdb/id"bb15c9cf37c646f76e90105643e7dcec8ad86b2e"}
 #:xtdb.api{:tx-time #inst"2022-02-27T20:49:36.997-00:00",
            :tx-id 6669,
            :valid-time #inst"2022-02-27T20:49:36.997-00:00",
            :content-hash #xtdb/id"bb15c9cf37c646f76e90105643e7dcec8ad86b2e"}]
```

> My workaround was to change prepare-docs to add current time as valid time explicitly.
> (I’m using Graal Java 17 just because I had it around, when I was playing with native image creation.  It only works in x86 mode…. I haven’t tried another x86 JVM.)

> I’m using JDBC and MySQL, connecting to a MySQL instance in Google Cloud SQL.  So absolutely they are on different machines.
> I presume Cloud SQL is running on UTC, and I typically keep everything in local time — I had never tried to run my dev machine in UTC until today.

After looking into it briefly, I think we may want to be using `UTC_TIMESTAMP` instead of `CURRENT_TIMESTAMP` here: https://github.com/xtdb/xtdb/blob/a3d6ce5b113948df0dfcf6c99d66b4c29838b782/modules/jdbc/src/xtdb/jdbc/mysql.clj#L35

(because CURRENT_TIMESTAMP is timezone-sensitive, based on https://dba.stackexchange.com/questions/62466/mysql-timestamp-timezone-handling)

If that is the case, there may be similar implications for Postgres and others too.

**Comment by jarohen** [comment]
We've been experimenting with this - it seems the issue arises when (and only when) the MySQL server's TZ differs from the JVM TZ. This is because MySQL sends timestamps back converted to the session's TZ, and JDBC then converts them back to UTC based on what it thinks the server's TZ is (same as its own, if not provided). Hence, if the server is in UTC, and the JVM in UTC-8, the JVM will assume that MySQL has sent it a UTC-8 timestamp, and add 8 hours to get 'back' to UTC. (The same holds for all of the other combinations of server/JVM TZs too - fun times!)

You can explicitly specify the server's TZ using the `serverTimezone` parameter to the `:db-spec`, which then means times are converted correctly to UTC regardless of the JVM's TZ:

```clojure
{:xtdb.jdbc/connection-pool {:dialect 'xtdb.jdbc.mysql/->dialect
                             :db-spec {:dbname "xtdbtest", :user "root", :password "my-secret-pw"
                                       :serverTimezone "America/Los_Angeles"}}}
```

HTH!

**Comment by jarohen** [comment]
> After looking into it briefly, I think we may want to be using `UTC_TIMESTAMP` instead of `CURRENT_TIMESTAMP` here: 

@refset: this won't work if the server's in a non-UTC TZ - `TIMESTAMP` cols in MySQL are stored in UTC, but are expected to be passed in the server's TZ and then converted by the server - so for UTC midday on an LA server would get stored as 20:00Z. `CURRENT_TIMESTAMP`, OTOH, is in server local time, so gets correctly converted to UTC when it's stored.

@mbutlerw and I did also discuss storing these as `DATETIME` cols instead (at which point we _would_ use `UTC_TIMESTAMP`) but opted against them, mainly because it would mandate a migration, but also because of a slight preference towards TIMESTAMP, as it's explicitly documented that it's stored in UTC, rather than relying on an implicit agreement that everything touching the column uses UTC.

That said, we're not MySQL experts (I'm far more familiar with Postgres!) so there may be a more idiomatic solution.

**Comment by realgenekim** [comment]
@refset and team: Thanks so much!  I can confirm that using the `:serverTimezone "America/Los_Angeles"` configuration setting does indeed work.  

FWIW, I think that documenting this in the JDBC instructions is more than sufficient — but, please be aware that I consider myself neither an expert in MySQL, or for that matter, JDBC or timezones, as I had told @refset in Slack. 😃 

```
(time (def tx (xt/submit-tx db/xtdb-node (prepare-docs-bare products-1))))
"Elapsed time: 419.903917 msecs"
=> #'genek.xtdbtest/tx
(time (xt/await-tx db/xtdb-node tx))
"Elapsed time: 2.864167 msecs"
=> #:xtdb.api{:tx-time #inst"2022-03-09T01:43:15.653-00:00", :tx-id 13635}
```

Kudos on the great work, and thorough explanations! 👏👏👏🎉🎉🎉

**Comment by jarohen** [comment]
Thanks @realgenekim, glad to hear it's resolved :slightly_smiling_face:

**Comment by realgenekim** [comment]
I'm afraid I may still need help getting timezones working correctly when using JDBC, connecting to a Google Cloud SQL MySQL db.  Because of a rather incredible experience of my laptop timezone changing while on a east to west flight, I totally see the value of using UTC time on the JVM.

But, I'm having problems again with transactions being put in the future — or something...

Here's the log of actions/events, hopefully annotated so that the error will be apparent — either my error, or something happening incorrectly...

Any hints on how to get things working as expected?  (Which is that when I do `xt/sync`, it returns right away; and when I do query, the inserted record shows up — when I do a query for all records, the two inserts appears right away, but all subsequent records don't show up.)

Thank you in advance for any advice!

```
(comment
  ;
  ; log
  ;
  ; # clear table
  ;
  (jdbc/execute! ds ["SELECT COUNT(*) FROM etldata.tx_events"])
  ;=> [{:COUNT(*) 452}]
  (jdbc/execute! ds ["DELETE FROM etldata.tx_events"])
  ;=> [#:next.jdbc{:update-count 452}]
  (jdbc/execute! ds ["SELECT COUNT(*) FROM etldata.tx_events"])
  ;=> [{:COUNT(*) 0}]

  ;
  ; # start db
  ;
  (.close jdbc)
  ;=> nil
  (def jdbc (db/start-jdbc!))
  ; .... this is what that function looks like
  (xt/start-node
        {:xtdb.jdbc/connection-pool {:dialect {:xtdb/module 'xtdb.jdbc.mysql/->dialect}
                                     ;:pool-opts { ...}
                                     :db-spec {;:jdbcUrl "..."
                                               ;; OR
                                               :host     "localhost"
                                               :dbname   (-> secrets :db :dbname)
                                               :user     (-> secrets :db :user)
                                               :password (-> secrets :db :password)
                                               :serverTimezone "UTC"}}})
  (System/getProperty "user.timezone")
  ;=> "UTC"
  ;
  ; === confirmed: jdbc and local JVM are set to UTC
  ;
  (def tx (zm/save! jdbc (second meetings)))
  ;#:xtdb.api{:tx-id 1968, :tx-time #inst "2022-04-11T04:49:52.133-00:00"}
  ;=> #'xtdb-s1-migrate-from-local/tx
  ;
  ; ==== :tx-time #inst "2022-04-11T04:49:52.133-00:00"
  ;
  ; what time is it now?
  ;
  (java.time.LocalDateTime/now)
  ;=> #object[java.time.LocalDateTime 0x12b6dd9f "2022-04-11T04:52:20.743003"]
  ;
  ; ===== yes, localdatetime matches the transaction time, and it's in utc
  ;
  (jdbc/execute! ds ["SELECT * FROM etldata.tx_events"])
  ;=>
  ;[#:tx_events{:event_offset 1967,
  ;             :event_key "2da97bc3029e4e59513018a2bb0ae3516941bc60",
  ;             :tx_time #inst"2022-04-11T04:49:51.963000000-00:00",
  ;             :topic "docs",
  ;             :v #object["[B" 0x3ba0ba0a "[B@3ba0ba0a"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1968,
  ;             :event_key nil,
  ;             :tx_time #inst"2022-04-11T04:49:52.133000000-00:00",
  ;             :topic "txs",
  ;             :v #object["[B" 0x1461d6d6 "[B@1461d6d6"],
  ;             :compacted 0}]
  (jdbc/execute! ds ["SELECT COUNT(*) FROM etldata.tx_events"])
  ;=> [{:COUNT(*) 2}]
  ;
  ; ===== 2 events, :tx_time #inst"2022-04-11T04:49:51.963000000-00:00",
  ; ===== :tx_time looks consistent with what we saved...
  ;
  ; ==== await-tx
  (time (xt/await-tx jdbc tx))
  ; hangs!!!
  ;
  ; what happens when we try to sync the db?
  (xt/sync jdbc)
  ; hangs!!!
  ;
  ; === try again
  ;
  tx
  ; => #:xtdb.api{:tx-id 1968, :tx-time #inst"2022-04-11T04:49:52.133-00:00"}
  (java.time.LocalDateTime/now)
  ;=> #object[java.time.LocalDateTime 0x40e04d69 "2022-04-11T05:04:46.351984"]
  ;
  ;

  #_0)
```

**Comment by realgenekim** [comment]
Some more evidence of the mismatch between what's in MySQL, and what XTDB sees — I hope this helps!!

```
; confirm that there are 4 records inserted
  (jdbc/execute! ds ["SELECT COUNT(*) FROM etldata.tx_events"])
  ;=> [{:COUNT(*) 8}]
  (jdbc/execute! ds ["SELECT * FROM etldata.tx_events"])
  ;=>
  ;[#:tx_events{:event_offset 1985,
  ;             :event_key "2da97bc3029e4e59513018a2bb0ae3516941bc60",
  ;             :tx_time #inst"2022-04-11T05:28:11.321000000-00:00",
  ;             :topic "docs",
  ;             :v #object["[B" 0x4682a18 "[B@4682a18"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1986,
  ;             :event_key nil,
  ;             :tx_time #inst"2022-04-11T05:28:11.452000000-00:00",
  ;             :topic "txs",
  ;             :v #object["[B" 0x22d7d6bc "[B@22d7d6bc"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1987,
  ;             :event_key "b449be6e8315c066ccd94f45c210ae8965068a36",
  ;             :tx_time #inst"2022-04-11T05:28:42.596000000-00:00",
  ;             :topic "docs",
  ;             :v #object["[B" 0x514d82d0 "[B@514d82d0"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1988,
  ;             :event_key nil,
  ;             :tx_time #inst"2022-04-11T05:28:42.721000000-00:00",
  ;             :topic "txs",
  ;             :v #object["[B" 0x53e6cb7d "[B@53e6cb7d"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1989,
  ;             :event_key "cfa951cc5b9e554af03583805be411b84c31d936",
  ;             :tx_time #inst"2022-04-11T05:28:55.232000000-00:00",
  ;             :topic "docs",
  ;             :v #object["[B" 0x169b13f3 "[B@169b13f3"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1990,
  ;             :event_key nil,
  ;             :tx_time #inst"2022-04-11T05:28:55.347000000-00:00",
  ;             :topic "txs",
  ;             :v #object["[B" 0xa6545aa "[B@a6545aa"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1991,
  ;             :event_key "02a2be7e21b2c9ed71a142ab8068e7575959cb8e",
  ;             :tx_time #inst"2022-04-11T05:29:17.292000000-00:00",
  ;             :topic "docs",
  ;             :v #object["[B" 0x37030d34 "[B@37030d34"],
  ;             :compacted 0}
  ; #:tx_events{:event_offset 1992,
  ;             :event_key nil,
  ;             :tx_time #inst"2022-04-11T05:29:17.413000000-00:00",
  ;             :topic "txs",
  ;             :v #object["[B" 0x52db858a "[B@52db858a"],
  ;             :compacted 0}]
  (java.time.LocalDateTime/now)
  ;=> #object[java.time.LocalDateTime 0x801dada "2022-04-11T05:34:14.024834"]
  (count (db/get-all jdbc))
  ;=> 2
  ;
  ; === there are 8 transactions in MySQL (4x docs, 4x txs)
  ; === but xtdb sees only 2 records
```

**Comment by realgenekim** [comment]
(20m later, xtdb reports 5 records [one is nil?]...  Maybe JDBC is just super slow?)

**Comment by realgenekim** [comment]
New data point: I have confirmed that everything works as expected when JVM timezone is set to UTC (`-Duser.timezone=UTC` <--- note, no quotes around UTC in the command line parameter!) and JDBC connection is set to UTC (`:serverTimezone "UTC"`).  Thanks again for the help.
