### ISSUE TITLE
Only warn about MALLOC_ARENA_MAX when using RocksDB

### ISSUE THREAD

**Issue by arichiardi** [xtdb/crux#1719]
A minor one, but we see:

`2022-03-21 09:48:50,080 WARN                                                      xtdb.api - MALLOC_ARENA_MAX not set, memory usage might be high, recommended setting for XTDB is 2`

when using LMDB.

It is probably easy to fix given the code [here](https://github.com/xtdb/xtdb/blob/529105575507e4d5d32595f8baea8bf153ada3ed/core/src/xtdb/api.clj#L249-L250).

Any known unknowns there? I might queue it up in my free time.

**Comment by refset** [comment]
Hey @arichiardi - we discuss the environment variable in the docs for the RocksDB module here: https://docs.xtdb.com/storage/rocksdb/#_project_dependency - I don't personally know whether the configuration could/should affect LMDB at all though. Therefore, I think the recommendation might be to set the value anyway, and update the LMDB docs to say the same.

**Comment by refset** [comment]
On reflection and a little further investigation, it seems safe enough to move the check to be only within the RocksDB namespace and therefore the warning would only be logged if the user is actually using Rocks (i.e. during module startup). A PR would be very appreciated if you can spare the time :slightly_smiling_face:

**Comment by arichiardi** [comment]
@jarohen thanks! I had a PR ready but I was about to sign the contributor agreement :smile:

**Comment by jarohen** [comment]
Ah, sorry @arichiardi! @refset and I chatted about this one on Slack, I hadn't seen his comment here before I'd pushed the change :sweat_smile:

**Comment by arichiardi** [comment]
@jarohen no worries, you PR is more complete anyways - side question, is there a dev guide of sort? Do I just `lein install` for building the local jars against `HEAD`?

**Comment by jarohen** [comment]
We have https://github.com/xtdb/xtdb/tree/master/dev, if that helps? If this doesn't work, I'd be keen to update it :slightly_smiling_face:

**Comment by arichiardi** [comment]
I think it helps yes, thank you - somehow I missed that in the main readme :cry:

**Comment by jarohen** [comment]
My fix introduced an unexplained `UnsatisfiedLinkError`, I can't see how. Reverted for now.

**Comment by arichiardi** [comment]
In my patch I had the `when` after loading RocksDb, not sure it solves though cause I was not able to try it out
