### ISSUE TITLE
Closing LMDB module should close the checkpointer thread

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1724]
Reported via https://juxt-oss.zulipchat.com/#narrow/stream/194466-xtdb-users/topic/.5BXPOST.5D.20LMDB.20crash.20on.20JDK.2017 (great report and investigation :pray:)
> Investigating I realised that the problem is the checkpointer thread, specifically the lmdb checkpointer thread is not stopped when lmdb is. The crash occurs after shutdown when all systems are closed except the checkpointer and the checkpointer then attempts to create a checkpoint against a closed lmdb instance.
> 
> The following change (made to git master branch) appears to fix the problem:
> 
> In xtdb/modules/lmdb/src/xtdb/lmdb.clj:
> 
> on line 223:
> 
> (defrecord LMDBKv [db-dir env env-flags dbi ^StampedLock mapsize-lock sync?]
> (defrecord LMDBKv [db-dir env env-flags dbi ^StampedLock mapsize-lock sync? ^Closeable cp-job]
> and on line 267:
> 
> (close [_]
> (let [stamp (acquire-write-lock mapsize-lock)]
> 
> becomes:
> 
> (close [_]
> (xio/try-close cp-job)
> (let [stamp (acquire-write-lock mapsize-lock)]

The suggestion looks in line with the Rocks module: https://github.com/xtdb/xtdb/blob/2f9f07c51d9fc04f7cf4edfbf7a859189a2b2b14/modules/rocksdb/src/xtdb/rocksdb.clj#L60

**Comment by jarohen** [comment]
proposed fix lgtm - thanks!
