### ISSUE TITLE
Extend edn http API with literal reader support for encoded types

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1725]
Noting a request/question raised via https://clojurians.slack.com/archives/CG3AM2F7V/p1648444641257069

e.g. `#xtdb/local-date` or `#xtdb.java.time/local-date` mapping to `java.time.LocalDate`

As per the list of encoded types:
https://github.com/xtdb/xtdb/blob/2f9f07c51d9fc04f7cf4edfbf7a859189a2b2b14/core/src/xtdb/codec.clj#L82-L100

**Comment by tatut** [comment]
To be able to use XTDB from non-JVM languages, the HTTP API is the easiest option. 
It would be good if it supported all the types that can be stored, especially j.t.LocalDate, LocalTime, LocalDateTime and Duration.

JSON is a bad format for these, but they could be supported in EDN payloads.

**Comment by jarohen** [comment]
I've made these opt-in, via `XTDB_ENABLE_JAVA_TIME_PRINT_METHODS`, and added docs on our various environment variables to the 'configuration' section of the site

**Comment by theronic** [comment]
What should the env var be set to? If I set env var `XTDB_ENABLE_JAVA_TIME_PRINT_METHODS=1` (or true), attempting to transact a `LocalDateTime` via HTTP still throws 400 malformed EDN. Sample:

```
        System.out.println("XT Java time print method setting:" + System.getenv("XTDB_ENABLE_JAVA_TIME_PRINT_METHODS")); // this prints "1"

        // Start XT and build Ledger
        var server = IXtdb.startNode(n -> {
            n.with("xtdb.http-server/server", http -> {
                http.set("port", 3000);
            });
        });

        //var node = IXtdb.startNode(File.read "xtdb.json");
        var node = IXtdb.newApiClient("http://localhost:3000");

        var txData = new HashMap<String, Object>();
        txData.put("tx/date", LocalDateTime.now());

        var builder = Transaction.builder();

        var txDoc = XtdbDocument.create("test-id", txData);
        builder.put(txDoc);
        node.submitTx(builder.build()); // throws malformed EDN
```

**Comment by theronic** [comment]
Ah, maybe this is in unreleased version?

**Comment by theronic** [comment]
Tried bumping XT to version 1.21.0-beta2, but same result. Assume not released yet.

**Comment by theronic** [comment]
Perhaps an option to pass EDN readers/writers to startNode would be helpful?

**Comment by jarohen** [comment]
@theronic: ah, you're already here :slightly_smiling_face: 

(from https://github.com/xtdb/xtdb/issues/1740#issuecomment-1090402424)

> Surely this should not require an ENV var? Maybe in XT configuration?

The reason this is an environment var is that (unfortunately - at least, as far as I know) it takes a JVM-wide change (via `print-method`) to add support for writing extra EDN types, which may then interfere with XTDB in-process users' Clojure applications, should they wish to print these types in a different way. We could consider making this opt-out instead - while we usually play this kind of thing on the safe side, it'll likely become clear quite quickly if there's a conflict.

The other option that we could consider would be for the XTDB http-client to request Transit over the wire - in this case, you _could_ specify per-call writers.

It'd be good to get some other suggestions and opinions on this one! :thinking:

**Comment by refset** [comment]
Just noting that there was some further (JUXT-internal) Slack discussion on this, roughly proposing:
> There are other edn printers in the wild that may let you override the printers non-globally, and a new dep would be limited to the HTTP server module (and could even be processed via mranderson). We probably don't care if these objects are round-trippable outside of the HTTP server

via https://juxt.slack.com/archives/C02U0TGCHM3/p1649261729623409
