### ISSUE TITLE
What is the meaning of the ellipsis in the documentation?

### ISSUE THREAD

**Issue by rawoke083** [xtdb/crux#1791]
Trying to switch to LMDB (since the quickstart of RocksDB is giving exception) so this is what is provided in the guide to configure LMD

```
{:xtdb/index-store {:kv-store {:xtdb/module 'xtdb.lmdb/->kv-store
                               :db-dir (io/file "/tmp/lmdb")}}
 :xtdb/document-store {...}
 :xtdb/tx-log {...}}

```
I pray what in the blue blazes do we need to put in the  "..." ellipses ?
I'm sure once you read the source code, the other 10001 out of date documentation, you might figure it out. But as a potential new user what in the world does that mean "..."

Can I put my "my-blue-cat " ?
Do I leave that out ??

Wow !

**Comment by jarohen** [comment]
This isn't the way to get the answers you want - please remember that we are fellow developers, after all.

If you wanted to start over and resubmit your question, I'm sure someone here would still be more than happy to help.
