### ISSUE TITLE
Issues with the entity-history

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#1795]
Sometimes the `entity-history` is missing things
```clj
(def xt-mem (xt/start-node {}))

(xt/submit-tx xt-mem [[::xt/put {:xt/id :testing/foo :testing/foo 1} #inst "2022-04-01" #inst "2022-05-02"]])
(xt/submit-tx xt-mem [[::xt/put {:xt/id :testing/foo :testing/foo 1} #inst "2022-07-01" #inst "2022-09-02"]])

(xt/entity-history (xt/db xt-mem) :testing/foo :desc {:start-valid-time #inst "2022-04-01"}) ;; only one tx returned
(xt/entity-history (xt/db xt-mem) :testing/foo :asc {:start-valid-time #inst "2022-04-01"}) ;; correct 3 itmes returned (as of 2022-08-03)
```
Also just a smaller nitpick 
```clj
(xt/entity-history (suser/xtdb-db (Date. Long/MAX_VALUE)) :testing/foo :asc) ;; returns nothing
(xt/entity-history (suser/xtdb-db (Date. Long/MAX_VALUE)) :testing/foo :desc) ;; correct
(xt/entity-history (suser/xtdb-db (Date. (dec Long/MAX_VALUE))) :testing/foo :asc) ;; correct
```

**Comment by refset** [comment]
Hey @FiV0, in the first case, the meaning of `:start-valid-time` may be the source of the confusion here. I think you are expecting it to mean "earliest valid time", but it is actually the point along the timeline where iteration starts (in either direction!). With that understanding, it looks to me like the results from the first snippet are correct. Does that make sense?

For the nitpick, the `:start-valid-time` will be implicitly defaulted to the valid-time supplied to the `db` call, which is done [here](https://github.com/xtdb/xtdb/blob/ffb5d00efde9e147f9daaef39973f5310c339aab/core/src/xtdb/query.clj#L1962). Hopefully that makes sense also.
