### ISSUE TITLE
fetch-docs can send a huge number of requests causing ingestion to fail

### ISSUE THREAD

**Issue by nivekuil** [xtdb/crux#1800]
Testing 1.22.0-rc1, indexing fails in `strict_fetch_docs` with the exception indicating hundreds of mismatched hashes. These documents do exist in Cloudflare R2 so I think the huge batch of async requests may be getting rate limited, exacerbated by the new ingest pipelining. I tested this patch and it successfully boots, albeit slowly:
```patch
diff --git a/modules/s3/src/xtdb/s3.clj b/modules/s3/src/xtdb/s3.clj
index 76ffde07..ecd4c6a4 100644
--- a/modules/s3/src/xtdb/s3.clj
+++ b/modules/s3/src/xtdb/s3.clj
@@ -30,32 +30,36 @@
                (.get req)))))
 
 (defn ^:no-doc get-objects [{:keys [^S3Configurator configurator ^S3AsyncClient client bucket prefix]} reqs]
-  (->> (for [[path ^AsyncResponseTransformer response-transformer] reqs]
-         (let [s3-key (str prefix path)]
-           [path (-> (.getObject client
-                                 (-> (GetObjectRequest/builder)
-                                     (.bucket bucket)
-                                     (.key s3-key)
-                                     (->> (.configureGet configurator))
-                                     ^GetObjectRequest (.build))
-                                 response-transformer)
-
-                     (.handle (reify BiFunction
-                                (apply [_ resp e]
-                                  (if e
-                                    (try
-                                      (throw (.getCause ^Throwable e))
-                                      (catch NoSuchKeyException e
-                                        (log/warn "S3 key not found: " s3-key))
-                                      (catch Exception e
-                                        (log/warnf e "Error fetching S3 object: s3://%s/%s" bucket (str prefix path))))
-
-                                    resp)))))]))
-
-         (into {})
-         (into {} (keep (fn [[path ^CompletableFuture fut]]
-                          (when-let [resp (.get fut)]
-                            [path resp]))))))
+  (transduce
+   (map (fn [reqs]
+          (->> (for [[path ^AsyncResponseTransformer response-transformer] reqs]
+                 (let [s3-key (str prefix path)]
+                   [path (-> (.getObject client
+                                         (-> (GetObjectRequest/builder)
+                                             (.bucket bucket)
+                                             (.key s3-key)
+                                             (->> (.configureGet configurator))
+                                             ^GetObjectRequest (.build))
+                                         response-transformer)
+
+                             (.handle (reify BiFunction
+                                        (apply [_ resp e]
+                                          (if e
+                                            (try
+                                              (throw (.getCause ^Throwable e))
+                                              (catch NoSuchKeyException e
+                                                (log/warn "S3 key not found: " s3-key))
+                                              (catch Exception e
+                                                (log/warnf e "Error fetching S3 object: s3://%s/%s" bucket (str prefix path))))
+
+                                            resp)))))]))
+
+               (into {})
+               (into {} (keep (fn [[path ^CompletableFuture fut]]
+                                (when-let [resp (.get fut)]
+                                  [path resp])))))))
+   merge
+   (partition-all 10 reqs)))
 
 (defn ^:no-doc list-objects [{:keys [^S3Configurator configurator ^S3AsyncClient client bucket prefix]}
                              {:keys [path recursive?]}]
```

**Comment by refset** [comment]
Thanks for the report @nivekuil - we will investigate this as a priority to unblock the release.

**Comment by refset** [comment]
Hey again, a few questions:

1. what is your average transaction size (number of ops/docs)?
2. can you paste the error you're seeing along with the stack trace? (was it `Caused by: java.lang.IllegalStateException: missing docs: #{...}`?)
3. are you seeing any errors that are clearly being (console) logged by the S3 SDK and not XT? or e.g. the `warn`/`warnf` shown above

Some initial reading suggests that S3 will throttle beyond "5,500 requests per second per prefix per bucket" but I'm unclear on what I would expect this to look like from an XT user perspective. The S3 console may also offer clues.

**Comment by nivekuil** [comment]
1. Not sure but shouldn't be relevant, it only takes one big tx with thousands of docs to fail ingestion entirely 
2. Yes it's that one
3. I searched for these https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/handling-exceptions.html but nothing came up

Cloudflare r2 has significantly lower caps, and clients should be respectful when sending requests to dependent systems in general. My transducer approach isn't great, I would probably do a semaphore with a long retry to be more flexible with different systems

**Comment by jonpither** [comment]
Hey @nivekuil, thanks for this information - we are looking into it. Is there any warning stack-trace earlier in the logs?

**Comment by jonpither** [comment]
I.e. `Error fetching S3 object` ...

**Comment by nivekuil** [comment]
Nothing for "S3 object". I've only seen that one when the doc was missing.

**Comment by wotbrew** [comment]
Hi @nivekuil 👋 , thanks again for the issue report 🙏 .

To test the 'rate limiting' hypothesis, would it be possible for you to try setting some [ environment variables ](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html) and test the same indexing again?

- `AWS_RETRY_MODE=adaptive` this should allow a more sophisticated rate limiting and retry algorithm to be used
- `AWS_MAX_ATTEMPTS=10` increases the maximum number of retries if a retryable error is encountered

These variables should override the default policy of the aws sdk used by the s3 module.

I would not recommend setting these variables system wide as they will change the behaviour of all standard aws tools and clients - so only as a test, if possible.

I am curious that you do not see an s3 client error in the log output, I would expect something like `Error fetching S3 object: s3://foo/bar` along side the mismatched hash exception. Would it be possible to confirm your logging configuration would show you `WARN` level messages from the package `xtdb.s3`?

**Comment by nivekuil** [comment]
The env vars don't work, still the same `Transaction ingester aborted` with `Caused by: java.lang.IllegalStateException: missing docs: #{#xtdb/id "de36494da52565ba5d32b6827a7a0090587068d4"` x 2000. Yes any xtdb warn logs should be printed.

**Comment by wotbrew** [comment]
We've just pushed a speculative fix as a snapshot, @nivekuil would it be possible try the latest `dev-SNAPSHOT` [as described here](https://github.com/xtdb/xtdb#pre-release-snapshot-builds) and report back? 🙏

**Comment by nivekuil** [comment]
lightly tested but lgtm

**Comment by jarohen** [comment]
Thanks @nivekuil!

#1808
