### ISSUE TITLE
Calling functions on a closing/closed node results in segfaults

### ISSUE THREAD

**Issue by ferdinand-beyer** [xtdb/crux#1803]
Every now and then, my REPL crashes with a segmentation fault, when trying to create a `db` object for a LMDB-backed index store.

It happens from a thread started by a `ScheduledThreadPoolExecutor`.

I've seen similar segfaults with RocksDB.

Example logfiles generated when the segmentation fault happens:
* [hs_err_pid20189.log](https://github.com/xtdb/xtdb/files/9375714/hs_err_pid20189.log)
* [hs_err_pid63855.log](https://github.com/xtdb/xtdb/files/9375715/hs_err_pid63855.log)

**Comment by ferdinand-beyer** [comment]
**Update**: I noticed that I caused this by accessing a closed node from a different thread, when meanwhile a new node has been started.

Here is a complete example to reproduce:

```clojure
(ns crash
  (:require [clojure.java.io :as io]
            [xtdb.api :as xt]))

(defn- kv-store [data-dir name]
  {:xtdb/module 'xtdb.lmdb/->kv-store
   :db-dir      (io/file data-dir name)})

(defn start-node
  []
  (let [data-dir "./data"]
    (xt/start-node {:xtdb/index-store    {:kv-store (kv-store data-dir "idx")}
                    :xtdb/document-store {:kv-store (kv-store data-dir "doc")}
                    :xtdb/tx-log         {:kv-store (kv-store data-dir "log")}})))

(def node (start-node))
(.close node)

(start-node)

(future (xt/db node))
```

My `deps.edn` file looks like this:

```clojure
{:paths ["src"]
 :deps {com.xtdb/xtdb-core {:mvn/version "1.21.0"}

        ;; LMDB
        com.xtdb/xtdb-lmdb {:mvn/version "1.21.0"
                            :exclusions [org.lwjgl/lwjgl org.lwjgl/lwjgl-lmdb]}
        org.lwjgl/lwjgl-lmdb                     {:mvn/version "3.3.0"}
        org.lwjgl/lwjgl$natives-linux            {:mvn/version "3.3.0"}
        org.lwjgl/lwjgl-lmdb$natives-linux       {:mvn/version "3.3.0"}
        org.lwjgl/lwjgl$natives-macos-arm64      {:mvn/version "3.3.0"}
        org.lwjgl/lwjgl-lmdb$natives-macos-arm64 {:mvn/version "3.3.0"}}}
```

**Comment by ferdinand-beyer** [comment]
**Update**: With the same example, but using RocksDB, I get segfaults as well.

Just to be clear: This clearly is a programming error, one should not access closed nodes like this. But maybe XTDB could prevent the JVM to segfault?

**Comment by ferdinand-beyer** [comment]
More info:

Without starting a second node, with LMDB I do not get segfaults, but exceptions like these:

```
MDB_READERS_FULL: Environment maxreaders limit reached
MDB_BAD_RSLOT: Invalid reuse of reader locktable slot
```

With RocksDB, I get segfaults when trying to access the closed node from any thread:

```clojure
(def node (start-node))
(.close node)
(xt/db node) ;; segmentation fault
```

**Comment by refset** [comment]
@wotbrew is this closeable now?

**Comment by refset** [comment]
Hey @ferdinand-beyer - I just realised we never said explicitly: thanks for the report! :slightly_smiling_face:

**Comment by ferdinand-beyer** [comment]
Oh, I think you did mention me in the release notes. My pleasure, thanks for this awesome project!
