### ISSUE TITLE
Bump Snappy and/or Kafka versions for M1 xtdb-kafka users

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1806]
Reports of:
```
[FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
```

https://github.com/xerial/snappy-java/pull/303

**Comment by jarohen** [comment]
@refset would this require a Kafka _major_ version bump?

**Comment by refset** [comment]
> would this require a Kafka major version bump?

Longer-term yes, but we have assumed that @wotbrew's addition of the explicit Snappy dep should be sufficient for now:
https://github.com/wotbrew/xtdb/commit/894eb70cd3215b7b18b3211a6c8cc6e31f4aeb83#diff-f9d2022a24859130dad04d6958bf6985aaf3df19426e5d388796c80db181aa87R20
