### ISSUE TITLE
Self-joining in queries / `pull` should not leak memory

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1810]
It's not quite a 'minimal' repro yet, but this whole expression will easily cause an OOM if evaluated (repeatedly, manually) a handful of times (i.e. leaking memory across runs):
```clojure
  (count (let [n (xt/start-node {})
               d (clojure.string/join (repeat 10000 "asdf"))]
           (xt/submit-tx n (vec (for [e (range 1000)]
                                  [::xt/put {:xt/id e :ref e :a d :b d :c d :d d :e d :f d :g [d d d d d d d d d d]}])))
           (xt/sync n)
           (for [x (range 1)]
             (xt/q (xt/db n) '{:find [(pull e1 [* {:ref [*]}])
                                      (pull e2 [* {:ref [*]}])]
                               :where [[e1 :ref e2]]}))))
```

I haven't dug into which part(s) of this might be responsible.

As a workaround, depending on the exact specifics of the desired query, it might be sufficient to simply add a predicate to ensure that self-joins don't happen, i.e. `(!= e1 e2)`

Thanks for your efforts with pinning this down @kevinmershon !

**Comment by wotbrew** [comment]
> (let [n xt/start-node {})

^^ I think the reason this expr leaks is because the in memory nodes are started and not closed, so its simply a case of caches/storage being consumed without being freed.

I tried this test to reproduce, memory usage seemed ok? Observed under profiler too.

```clojure
(with-open [n (xt/start-node {})]
  (let [mem (fn [] (let [total-memory (.totalMemory (Runtime/getRuntime))
                         free-memory (.freeMemory (Runtime/getRuntime))]
                     (double (/ free-memory total-memory))))]
    (let [d (clojure.string/join (repeat 10000 "asdf"))]
      (xt/submit-tx n (vec (for [e (range 1000)]
                             [::xt/put {:xt/id e :ref e :a d :b d :c d :d d :e d :f d :g [d d d d d d d d d d]}])))
      (xt/sync n)
      (dotimes [i 1000]
        (printf "Before %.2f" (mem))
        (newline)
        (time (count (xt/q (xt/db n) {:find '[(pull e1 [* {:ref [*]}])
                                              (pull e2 [* {:ref [*]}])]
                                      :where ['[e1 :ref e2]
                                              ;; blow query cache
                                              [(list '= i i)]]})))
        (printf "After %.2f" (mem))
        (newline)))

    (System/gc)
    (printf "After GC %.2f" (mem))
    ))
```

Have I missed something here?

**Comment by refset** [comment]
Ah yep that should have been a with-open, my mistake. In which case maybe this whole repro I attempted to cook up is a red herring. The report still stands however, and I'll share the source with you in case you have other thoughts.

**Comment by refset** [comment]
This was likely caused by the 'second chance' cache, per the notes in https://github.com/xtdb/xtdb/pull/1823 (where the default cache was subsequently changed to LRU)
