### ISSUE TITLE
Use a tar when checkpointing

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1824]
Create a single file rather than a directory (better to list, manage, verify etc.), and use object store metadata capability

- [ ] Validate multi-part upload behaviour with max SST file sizes (e.g. >5GB)

**Comment by jarohen** [comment]
@sw1nn may well have started on this one, worth a chat before we also start on it :slightly_smiling_face:

**Comment by refset** [comment]
Just noting that I am wondering whether the tar will mitigate this default S3 client async behaviour: https://stackoverflow.com/questions/72773439/how-to-configure-checkpointing-on-an-xtdb-node-using-aws-s3/72866754#72866754 - it would be good to validate somehow.

**Comment by jsulmont** [comment]
IIRC the solution proposed in this SO post (which is S3 specific)  are a situation resulting from an attempt to simultaneously transfer a large number of files e.g.  when the checkpoint directory to be copied has a large number of (large) files. 

As discussed in #1873 XTDB attempts to copy in parallel individual (e.g. SST) files: there is no attempt to somehow flow-control.

A checkpoint directory can be large (GB), and so would be a tarball of it (bad compression rate for SST).

Transferring a tarball (i/o a directory) would require us to use multipart transfer, and would require us to make assumptions on the mini/maxi size of a single part, not talking about having make decisions on the maximal number of inflights transfers: somehow addressing the flow control of the transfer;

So unless we address these issues, using tar would would not alleviate the problem described in this SO post.

A probably better solution, would be to use some *existing* transfer management facility offered by the store -- if any!

S3 offers a [transfer manager](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html) facility and I am pretty sure GCP has something similar. Issue #1889 describes that (together with this [PR](https://github.com/xtdb/xtdb/pull/1889)).

I haven't checked yet, but I am pretty sure GCP has something similar.


@refset

**Comment by jsulmont** [comment]
See #1864 #1868 #1889
