### ISSUE TITLE
Attribute stats wrong in 1.22.0 version

### ISSUE THREAD

**Issue by tatut** [xtdb/crux#1825]
I noticed that after upgrading to XTDB 1.22.0 and recreating the indexes, the attribute-stats are wrong.

In my case there were multiple attributes missing from attribute stats, but they could be found in queries and when pulling data.
Looks like it might be related to tx-ops generated by transaction functions.

(tested with tx-log, docs and indexes all in separate RocksDB kv-stores).

Discussion in clojurians slack https://clojurians.slack.com/archives/CG3AM2F7V/p1663659031894769

```clojure
(defn check-all-attrs [node]
  (let [doc-count (atom 0)
        attrs (atom #{})]
    (with-open [docs (xt/open-q (xt/db node)
                                '[:find ?e :where [?e :xt/id]])]
      (doseq [[d] (iterator-seq docs)
              :let [e (xt/entity (xt/db node) d)]]
        (swap! attrs into (keys e))
        (swap! doc-count inc)))
    {:docs @doc-count
     :attrs @attrs}))
```

The above check code returned attribute set that had more values than were in the `xt/attribute-stats`map.

**Comment by tatut** [comment]
```clojure
(xt/submit-tx node [[::xt/put {:xt/id "missing-test1" :some-missing/attribute "NEW VALUE"}]])
```

After submitting a new tx with a simple put that has one of the missing attributes, it appears in attribute-stats, but with a wrong count of 1.

**Comment by tatut** [comment]
What are the implications of this? Is it safe to run 1.22.0? 
Does the stats missing have any negative effects?

**Comment by wotbrew** [comment]
Hypothesis:

Looking at the tx-ingest pipeline in 1.22.0 it appears stats are missing on docs introduced via transaction function expansion.  Transaction functions are evaluated in `index-tx-events`, and docs introduced at this point are not supplied as args to the `stats-fn` in `->tx-ingester`.

Minimal repro:

```clojure
(with-open [node (xt/start-node {})]
  (->> [[::xt/put {:xt/id :put-foo,
                   :xt/fn '(fn [_ n] [[::xt/put {:xt/id :foo, :answer n}]])}]
        [::xt/fn :put-foo 42]]
       (xt/submit-tx node))
  (xt/sync node)
  ;; stats are delivered async, no easy hook right now to block 
  (Thread/sleep 1000)
  (xt/attribute-stats node))
```

EDIT for clarity:
You would expect a count of `1` for `:answer` in this example, but you do not.  You have to introduce the doc via a top level put.
