### ISSUE TITLE
Improving user support on ingester errors

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#1831]
At the moment, in the unlikely event of an ingester error, we don't provide users with enough guidance about what's happened, why, or what to do next.

"For example, if the doc store has latency spikes and one request happens to hits a timeout, the node will left in a degraded state indefinitely" (as per #1854).

* include ingester-error in the API (maybe status map?) so that users can easily check for it (e.g. for healthchecks)
* link to documentation in the error message?
* consider node configuration to deterministically skip a troublesome transaction (needs to happen on all nodes - may require a reindex.)

**Comment by wotbrew** [comment]
Closed by #1906
