### ISSUE TITLE
More robust ingester

### ISSUE THREAD

**Issue by nivekuil** [xtdb/crux#1854]
If the transaction ingester halts, it remains in an errored state until the node is restarted. For example, if the doc store has latency spikes and one request happens to hits a timeout, the node will left in a degraded state indefinitely. This leads to confusing behavior, e.g. `await-tx` always returns the same error pointing to the transaction that broke the ingester, while writes continue to be sent. Can the ingester be made more robust in the face of these sorts of transient errors?

**Comment by jarohen** [comment]
Hey @nivekuil, thanks for reporting this! It's very much on our radar at the moment, we're considering solutions over in #1831.

James
