### ISSUE TITLE
xtdb blocks jvm exit in clojure

### ISSUE THREAD

**Issue by jflinchbaugh** [xtdb/crux#1882]
I have a simple program that opens the DB like the examples, and immediately closes the connection and exits, but with 1.23.0, the execution hangs after exit of main. I can ctrl-c it fine. 
```
(ns xtdb-bug.core
  (:gen-class)
  (:require [clojure.java.io :as io]
            [xtdb.api :as xt]))

(defn start-xtdb! [dir]
  (letfn [(kv-store [d]
            {:kv-store {:xtdb/module 'xtdb.rocksdb/->kv-store
                        :db-dir d
                        :sync? true}})]
    (xt/start-node
     {:xtdb/tx-log (kv-store (io/file dir "tx-log"))
      :xtdb/document-store (kv-store (io/file dir "doc-store"))
      :xtdb/index-store (kv-store (io/file dir "index-store"))})))

(defn -main [& args]
  (with-open [xtdb-node (start-xtdb! "data")]
    (prn xtdb-node)))
```

deps.edn:
```
{
 :deps
 {org.clojure/clojure {:mvn/version "1.11.1"}
  com.xtdb/xtdb-core {:mvn/version "1.23.0"}
  com.xtdb/xtdb-rocksdb {:mvn/version "1.23.0"}}

 :paths ["src" "test" "resources"]

 :aliases
 {}
}
```

I can get it to exit if I add `(shutdown-agents)` to the end of main, or if I revert back to xtdb 1.22.0.

**Comment by refset** [comment]
Thanks for the report @jflinchbaugh, hopefully that's suitably resolved in the next release! It's worth noting though that it's normally recommended for Clojure CLI usage to end with `(shutdown-agents)` in any case (e.g. see https://clojureverse.org/t/why-doesnt-my-program-exit/3754/2)
