### ISSUE TITLE
`latest-submitted-tx` should avoid scanning the MariaDB tx-log

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1896]
There has a been a report of running `sync` with MariaDB (via `xtdb-jdbc`) taking much longer than necessary because the lookup isn't using SQL indexes correctly (and the index-store is otherwise caught up). This requires further investigation.

**Comment by keytiong** [comment]
This is to provide further information on the issue.

We an XTDB deployment using MariaDB (with mysql dialect) as our transaction log store and have observed a noticeable performance derogation (tens of seconds latency) on `latest-submitted-tx` after substantial number of transactions (in the order of tens of millions events) in XTDB.

The `JdbcTxLog` executes the following query to get the latest submitted transaction id.

`SELECT max(EVENT_OFFSET) AS max_offset FROM tx_events WHERE topic = 'txs'`

This query appears to be a table scan on `tx_events`. There is an index on `EVENT_OFFSET` but the `MAX()` aggregate function doesn't seem to be able to take advantage of that. And if it can, the filter by `topic` column would prevent it to do so and forcing the query to perform a scan.

**Comment by zackteo** [comment]
These are the results of running the query with and without the ` WHERE topic = 'txs'` 

MariaDB [(none)]> use Z
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [Z]> SELECT max(EVENT_OFFSET) AS max_offset FROM tx_events;
+------------+
| max_offset |
+------------+
|  128002164 |
+------------+
1 row in set (0.005 sec)

MariaDB [Z]> SELECT max(EVENT_OFFSET) AS max_offset FROM tx_events WHERE topic = 'txs';
+------------+
| max_offset |
+------------+
|  128002164 |
+------------+
1 row in set (2 min 36.252 sec)

**Comment by zackteo** [comment]
This follows the result of running explain plan, with and without the where clause

Database used: Z

SELECT max(EVENT_OFFSET) AS max_offset FROM tx_events WHERE topic = 'txs'

SUCCESS : explain_plan_20230210_131754.txt

Date-20230210_131754; detail of explain plan:

+------+-------------+-----------+------+---------------+------+---------+------+----------+-------------+
| id   | select_type | table     | type | possible_keys | key  | key_len | ref  | rows     | Extra       |
+------+-------------+-----------+------+---------------+------+---------+------+----------+-------------+
|    1 | SIMPLE      | tx_events | ALL  | NULL          | NULL | NULL    | NULL | 23534971 | Using where |
+------+-------------+-----------+------+---------------+------+---------+------+----------+-------------+

Database used: Z

SELECT max(EVENT_OFFSET) AS max_offset FROM tx_events

SUCCESS : explain_plan_20230210_132049.txt

Date-20230210_132049; detail of explain plan:

+------+-------------+-------+------+---------------+------+---------+------+------+------------------------------+
| id   | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra                        |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------------------+
|    1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Select tables optimized away |
+------+-------------+-------+------+---------------+------+---------+------+------+------------------------------+

**Comment by jarohen** [comment]
Hey @zackteo, cheers, and noted 🙏 commented on #1898
