### ISSUE TITLE
tx-time should only monotonically increase alongside tx-id (JDBC/Postgres)

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1917]
There has been a [report](https://clojurians.slack.com/archives/CG3AM2F7V/p1678736012528299) of an Aurora Postgres user experiencing a subsequent tx-id with a _lower_ tx-time than the previous tx under a lightly parallel workload.

This may affect `entity-history` sorting or any user code relying on the monotonic tx-time property, but there could be wider effects (TBC). The behaviour is at least consistent (i.e. open-tx-log is stable).

Short of understanding the root causes, at a minimum we could mitigate using `MAX(last_known_tx_time, current_timestamp)` - this could potentially even just happen locally on replay/query rather than in the SQL to 'correct' the view of existing logs/histories.

**Comment by wotbrew** [comment]
Resolved by #2989
