### ISSUE TITLE
JDBC NodeOutOfSyncException should not happen after await-tx

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1918]
There has been a [report](https://clojurians.slack.com/archives/CG3AM2F7V/p1678736012528299) of an Aurora Postgres user (JDBC tx-log and doc-store sharing a connection pool) experiencing the following:

> I just experienced some NodeOutOfSyncExceptions coming from tx-committed? - my code to submit a TX is basically this:
```clojure
(let [submitted-tx (xt/submit-tx node ops)]
  (xt/await-tx node submitted-tx)
  (if (xt/tx-committed? node submitted-tx)
    nil
    (throw (Error. "TX not committed"))))
```
> The message is Node out of sync - requested '{:xtdb.api/tx-id 3970, :xtdb.api/tx-time #inst "2023-03-13T19:15:45.803-00:00"}', available '{:xtdb.api/tx-time #inst "2023-03-13T19:15:45.806-00:00", :xtdb.api/tx-id 3969}'

I speculated that there may something happening in the connection pooling (i.e. using two different connections) that is causing the second API call to return slightly stale results.

Workaround:
> catching that particular error and retry tx-committed? after a short sleep.

Possibly related to https://github.com/xtdb/xtdb/issues/1917 (reported in the same thread)

UDPATE (20230921) Thomas Moerman on has experienced this also (running Postgres in Docker locally) https://clojurians.slack.com/archives/CG3AM2F7V/p1695280975177629?thread_ts=1678736012.528299&cid=CG3AM2F7V

**Comment by refset** [comment]
It's very likely more noticeable given Aurora's clustered replication setup

> all Aurora Replicas return the same data for query results with minimal replica lag. This lag is usually much less than 100 milliseconds after the primary instance has written an update. Replica lag varies depending on the rate of database change. That is, during periods where a large amount of write operations occur for the database, you might see an increase in replica lag.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html

**Comment by wotbrew** [comment]
https://www.postgresql.org/docs/current/transaction-iso.html
https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT

> Since these functions return the start time of the current transaction

Hypothesis: The CURRENT_TIMESTAMP function will return the start time of the transaction, which is established before the table lock. Concurrent serializable transactions may see earlier timestamps, but be later acquiring the lock. Therefore causing an invalid tx-time ordering.

Will test this and report back.
