### ISSUE TITLE
ClassCastException in `xtdb.s3.checkpoint-transfer-manager/download-checkpoint` if dir is not empty.

### ISSUE THREAD

**Issue by tatut** [xtdb/crux#1926]
Minor issue I ran into when investigating transfer manager checkpoint workings in the REPL.

If directory is non-empty when downloading, it should throw IllegalArgumentException.
Instead it throws ClassCastException as the 2nd argument to IAE constructor is a File not a Throwable.

Probably meant to wrap the message with `str` like: 
```clojure
(throw (IllegalArgumentException. (str "non-empty checkpoint restore dir: " dir)))
```

**Comment by sw1nn** [comment]
Fixed by #1912 ?

**Comment by refset** [comment]
I think we can assume this was observed in 1.23.1 (?) - so perhaps the 1912 fix was insufficient :thinking: 

Thanks for the report @tatut

**Comment by tatut** [comment]
Yes on 1.23.1
