### ISSUE TITLE
Investigate intermittent test failures

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#1929]
We see test flake that does not always have any report of a failure or error, yet leiningen exits with non-zero.

There are plenty of examples in the [CI logs](https://app.circleci.com/pipelines/github/xtdb/xtdb/2927/workflows/60af91ba-aa2d-4b12-b6cc-95065e0bff1a/jobs/11215)

Investigate and fix

**Comment by refset** [comment]
@wotbrew in this specific example you linked to it's showing:
```
FAIL in (test-non-entity-id-lookup-issue-287) (query_test.clj:2048)
xtdb.lmdb/->kv-store
expected: (<= secondary-time (* entity-slowdown-factor entity-time))
  actual: (not (<= 3859862 3073760))
```

All such "slowdown" tests are inherently prone to flake, especially when the underlying hardware may be changing, and also when dependencies get upgraded which can affect performance characteristics. Normally we can just adjust the timings to make them not flake, but equally _sometimes_ it can be worth first understanding if there's a legitimate regression or material change to performance.

In this exact case it looks like there may actually have been a significant speed up in the LMDB doc store (which isn't necessarily a bad thing!) but I don't understand how that could have happened without us spotting it already.

**Comment by wotbrew** [comment]
Sorry, yes sometimes there is flake with a FAIL (such as slowdown), where might need to tune some numbers BUT I should have linked to another report, as most of the time there is no failure or error that I can see: 


I think this one is better: https://circleci.com/api/v1.1/project/github/xtdb/xtdb/11210/output/103/0?file=true&allocation-id=642c005b5e75636a8ed7c73a-0-build%2FF17A419

**Comment by refset** [comment]
Fair :)

I actually don't recall seeing this error before (at the end of your link):
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@367fd5db rejected from java.util.concurrent.ScheduledThreadPoolExecutor@62db0e63[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 214]
```

Possibly also worth noting there are apparently ways to suppress logging for (most of?) these tests where we are legitimately expecting the `ERROR xtdb.tx - Ingester error occurred` behaviour, to make it _much_ easier to eyeball for the actual failure cases.

**Comment by wotbrew** [comment]
https://github.com/technomancy/leiningen/issues/1859#issuecomment-1462232132

The latest 1.10.3 clojure image from Circle uses lein 2.9.8, this explains the absence of error information in the report.
