### ISSUE TITLE
Establish SQL conformance test suite

### ISSUE THREAD

**Issue by hraberg** [xtdb/crux#2051]
We need to use an existing suite to check our conformance to the SQL standard. This card involves picking one, and get a few initial queries passing and establish the framework for future work.

Potential options:
* https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki (Materialize's fork: https://github.com/MaterializeInc/sqllogictest/tree/master)
* https://github.com/h2database/h2database/tree/master/h2/src/test/org/h2/test/scripts
* https://github.com/postgres/postgres/tree/master/src/test/regress
* https://github.com/MonetDB/MonetDB/tree/master/sql/test

The Sqllogictest suite seems to be one of the most common to use, and has support to add new dialects and databases. In practice, a fork of one of these is likely easiest to work from, and also add our own tests. We could also use more than one suite, especially if a simpler suite helps to get started and doesn't overwhelm us.

> Sqllogictest is concerned only with correct results. No attention is paid to performance, optimal use of indices, disk and memory usage, transactional behavior, or concurrancy and locking issues. The sqllogictest program seeks to answer just one question: "Does the database engine compute the correct answer."

**Comment by hraberg** [comment]
A few other tools:
https://github.com/sqlancer/sqlancer
https://github.com/anse1/sqlsmith
https://github.com/elliotchance/sqltest

**Comment by hraberg** [comment]
A few other suites:
https://github.com/google/zetasql/tree/master/zetasql/compliance
https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/logictest/testdata/logic_test (potential license issue)

**Comment by hraberg** [comment]
Last APL version:
https://github.com/cockroachdb/cockroach/tree/v19.1.11/pkg/sql/logictest/testdata/logic_test (idea being that older BSL releases are already/soon-to-be converted to Apache Public License)

**Comment by hraberg** [comment]
https://github.com/duckdb/duckdb/tree/master/test/sql
https://duckdb.org/docs/dev/testing

**Comment by hraberg** [comment]
https://github.com/MaterializeInc/materialize/tree/main/test/sqllogictest (also BSL license).

**Comment by hraberg** [comment]
https://github.com/partiql/partiql-lang-kotlin/tree/main/testscript/pts/test-scripts

**Comment by hraberg** [comment]
Old version of PostgreSQL regress in SLT format for MonetDB:
https://github.com/MonetDB/MonetDB/tree/master/sql/test/pg_regress

**Comment by hraberg** [comment]
Versions of select1-5 SLT tests with more rows visible without hashing (for sanity check) for MonetDB:
https://github.com/MonetDB/MonetDB/tree/master/sql/test/SQLite_regress/sqllogictest/Tests

**Comment by hraberg** [comment]
https://github.com/apache/spark/tree/master/sql/core/src/test/resources/sql-tests

**Comment by jarohen** [comment]
Done for now, using SLT - let's re-open this when we want further suites
