### ISSUE TITLE
Support non-literals in `VALUES` expressions

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2062]
`VALUES` expressions (mapped into `:table` in the LP) can take arbitrary expressions - see the spec for more details, but here're some examples:

* static calculations: `VALUES (3 + 4, 5 * 6)`
* sub-queries: `VALUES (3, (SELECT x FROM y))`
* scalar rows: `VALUES (3, 4), (SELECT x, y FROM z)`
* combinations of the above

**Comment by hraberg** [comment]
Just a note, queries will essentially already been resolved to a column at the point the expressions in the table are executed (this is true for all subqueries). That is, the operator itself doesn't need to deal with it directly, but individual values in the maps needs to be using expressions.

**Comment by jarohen** [comment]
Let's sync up on what we want the LPs to look like :slightly_smiling_face:

**Comment by jarohen** [comment]
plans we might yield for these:

```clojure
;; FROM x, (VALUES (1 + 2, 1 + (SELECT y FROM foo FETCH FIRST 1 ROW ONLY)), (SELECT x, y FROM query...)) AS vs (x, y)

;; option A
'[:cross-join
  (plan x)
  [:union-all
   [:apply :cross-join {y ?y} #{...}
    [:top {:limit 1}
     [:scan [y]]]
    [:table [{:x (+ 1 2), :y (+ 1 ?y)}]]]
   [:max1row (plan query)]]]

;; option B
'[:cross-join
  (plan x)
  [:apply :cross-join {x ?x1, y ?y1}
   [:max1row [:scan [x y]]]

   [:apply :cross-join {y ?y} #{...}
    [:top {:limit 1}
     [:scan [y]]]
    [:table [{:x (+ 1 2), :y (+ 1 ?y)}
             {:x ?x1, :y ?y1}]]]]]
```

**Comment by jarohen** [comment]
done a first pass, although requires more thought about how to use the expression engine to yield scalar values. 
* this first commit, for example, means that tables no longer support inline lists. 
  * I've tried extending `codegen-expr` to list, but this then means the elements need to be translated back from their expression engine intermediate values (e.g. strings being passed as `ByteBuffer`s), without having the type information necessary to do so
