### ISSUE TITLE
Fresh build has a broken classpath

### ISSUE THREAD

**Issue by deobald** [xtdb/crux#2067]
`./bin/prep.sh` and `./bin/re-prep.sh` both fail with the following on a _new_ Clojure install:

```
Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/namespace/repl__init.class, clojure/tools/namespace/repl.clj or clojure/tools/namespace/repl.cljc on classpath.
```

`deps.edn` specifies `clojure.tools.namespace` but it can't get it until it resolves the dependencies `prep` itself is trying to, uh, prepare.

## Steps to reproduce

1. Remove Clojure completely from the system (or start with a fresh box)
2. Remove `~/.clojure/deps.edn` if you have one and any other dependency magic that might bring `c.t.n` into your classpath by coincidence
3. `pacman -S clojure`
4. Run `./bin/prep.sh` -- it should fail

## Expectation

As silly as it seems, the readme probalby shouldn't even assume the reader has Clojure installed. Steps like "install clojure, run this script" should work for anyone even if no one outside the core team is working with Core2 at the moment.

**Comment by jarohen** [comment]
Strange - CI is running exactly this, on a fresh Docker image. wonder why that works... :thinking:

**Comment by jarohen** [comment]
Can't repro this one any more:

* Fresh clone
* Using `-Srepro` to ensure it's not pulling in anything magic:
  * adapted from prep.sh: `clojure -Srepro -X:deps prep`
* checking the classpaths for the modules that are prep'd (api, core, modules/s3): `clojure -Srepro -Spath -X:deps | tr ':' '\n' | grep clojure` - none contained c.t.n, but prep still went through ok.

@deobald will close this one for now unless you're still able to repro, or I'm missing a step?
