### ISSUE TITLE
Ability to order by NULL values.

### ISSUE THREAD

**Issue by hraberg** [xtdb/crux#2109]
Results in ISE "Value at index is null" in select3.test.

There's a related piece of work to this which is to support NULLS FIRST/LAST, but this issue is about the fact that it blows up. Unsure what the default order of NULL is.

In XT, there's an additional issue when it comes to sorting on different (incompatible) types, which also is a different Q3-style card.

**Comment by jarohen** [comment]
Think this is a different issue to the original fix - `vw/vec->duv-copier` doesn't seem to be handling scalar nullable vectors yet.
