### ISSUE TITLE
Variadic concat in the expression engine

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2116]
---- 
(from @wotbrew)
e.g concat could be specialised for arg arities up to some N right now. But we cannot implement for any number of args, we must implement each individual arity (perhaps in a doseq).

We could leave things are they are an specialise for N up to 32 for example, but it means the plan optimiser rules that collapse repeated binary application into a single variadic implementation must know what the break points are.

**Comment by jarohen** [comment]
@wotbrew this might be a bit easier after xtdb/core2#177 - an implementation of `codegen-call*` might have the power you want here?

**Comment by wotbrew** [comment]
> @wotbrew this might be a bit easier after xtdb/core2#177 - an implementation of `codegen-call*` might have the power you want here?

I think so! Thanks!

**Comment by wotbrew** [comment]
Closed by [3e2034ec](https://github.com/xtdb/core2/commit/3e2034ec50119c559c2698316707c0b9ea4c973d)
