### ISSUE TITLE
Ensure correct return values for EVERY/ANY Aggregate/set functions

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2123]
https://crate.io/docs/sql-99/en/latest/chapters/33.html#set-functions

**Comment by jarohen** [comment]
@mbutlerw could you add a repro for this one? do you mean aggs or sub-queries?

**Comment by mbutlerw** [comment]
No repo, not currently failing any tests AFAIK, simply came across a table in that doc which outlines what the current return values should be and I don't think we do, will change card to "ensure" as its possible theres no work here.
