### ISSUE TITLE
Add Support for `all` variants of aggregates.

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2124]
Some line numbers from random aggr
 
 ["No method in multimethod '->aggregate-factory' for dispatch value: :avg-all" (70643 53979 41578 12491 7451) 6]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :min-all" (90310 90181 89176 88365 86712) 84]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :max-all" (89572 88749 88048 85447 84128) 84]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :max-distinct" (90047 88222 87488 85814 83459) 87]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :sum-all" (90075 87706 87582 86749 85890) 88]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :count-all" (90635 89088 88818 87866 86615) 89]
 ["No method in multimethod '->aggregate-factory' for dispatch value: :min-distinct" (90706 89617 89028 88878 88313) 102])

**Comment by jarohen** [comment]
unblocked now, after a22da935e16ad453d23ee0a8d8b435f7f22c2579. as discussed, let's add aliases for these into the group-by operator, to allow the plan to 'just' create symbols without worrying about which ones are actually equivalent etc.
