### ISSUE TITLE
core2.types/least-upper-bound In SLT random expr and aggr

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2125]
Follow error appears multiple times in both files.

Some Line numbers from aggr

 ["Wrong number of args (0) passed to: core2.types/least-upper-bound/fn--12248" (79956 76563 72509 67798 66661) 18]
 
`.maybePromote` requires at least one numeric type in the input vector.  maybePromote is responsible for determining the type of the initial accumulator value, which again requires at least one numeric input. An alternative solution could involve revisiting the promotion of null vectors (to ensure the acc type remains null) and fix a few aggregate implementations emit-init steps.

An additional complication with changing `.maybePromote` is that you may receive monomorphic vectors with nulls in the validity bitmap, which again would mess with accumulator init values. You really do need to know if all elements are null, or once visited by the agg have been observed to be null - not just the types.

Repro: `(op/query-ra '[:group-by [{n (sum a)}] [:table [{:a nil}]]] {})`

**Comment by mbutlerw** [comment]
Think this might be fixed by https://github.com/xtdb/core2/pull/196 so moving to awaiting merge for now, particularly to avoid someone else looking at it in the meantime.

**Comment by wotbrew** [comment]
Going to park this until @jarohen is ready with schema inference as it makes solving the problem a lot easier.

**Comment by jarohen** [comment]
@mbutlerw I've closed this one after a22da93 because the original `core2.types/least-upper-bound` has gone, and also the PR you two originally wrote against `promotable-agg-factory` (#196 - `promotable-agg-factory` has also gone). If you can still repro this, could you re-open the issue? cheers mate
