### ISSUE TITLE
Breakdown why this Query from slt/index/1/between takes 32s from cold (on matts machine)

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2134]
```SELECT pk FROM tab0 WHERE ((((((col0 >= 3 OR ((col4 > 5.3) OR col0 = 1)) OR (((((((((((col0 IN (6,8,8) AND (((col3 IS NULL)) OR (col3 >= 7)) OR col4 > 1.7 AND (col3 < 6) AND col1 < 6.94 OR col3 <= 0 AND col4 > 4.97 OR col3 < 4))) AND (col4 >= 2.32)) AND (col1 > 9.72) OR col4 < 1.15 OR (col3 = 5 OR col0 >= 6 AND (col4 = 8.11) OR col3 > 2 OR col4 >= 7.17 OR col4 <= 0.15)))) AND col3 > 9 AND ((col1 < 4.34) AND col1 IS NULL) AND ((col0 >= 1))) OR ((col3 < 9 AND col0 > 2))) OR ((col1 >= 2.33) OR (col0 IS NULL) OR col0 < 8) OR col0 > 4 AND col4 < 2.41 OR col3 < 1 OR col1 IS NULL OR (col0 = 1 OR col0 < 0 OR col0 IS NULL) OR (col3 IS NULL) OR col0 > 4)) AND col3 <= 1))) OR col3 = 0 AND col0 < 3 OR col4 <= 1.54) AND (col0 IN (4,8,1,9,6) OR (col1 = 8.45 OR col3 IS NULL OR (((col0 = 2 OR col0 < 1 OR ((col0 >= 9)) AND (col4 <= 9.36) OR col3 < 1 OR ((col3 >= 5 OR (col4 < 1.77) OR col3 < 5)) OR col0 > 2 OR ((col3 < 1)) AND (col3 > 6) AND col1 <= 5.45 OR (((col1 <= 1.25 OR col3 < 1 AND (col1 < 9.3)) AND (col3 > 0 AND col3 = 5 OR (col1 IN (7.77,3.86,0.2) OR col1 > 1.85 OR ((col3 < 7 AND col3 > 3))) OR ((col0 >= 7 AND (col1 IN (2.13,7.79,7.5,4.90)))) AND ((((col3 < 5)))) AND (col1 < 6.11 AND col0 > 8) AND col3 <= 2 AND (col3 > 9)) AND col3 > 9 AND (col3 <= 5))) OR (col3 BETWEEN 6 AND 0 AND ((col0 < 1)) AND (col3 IS NULL OR (col0 IN (4,6,5,4,0) AND (col4 > 5.59)) OR col0 > 3 OR (((col3 BETWEEN 5 AND 7) OR (col1 >= 4.28)) AND col0 >= 2))) AND (col0 BETWEEN 5 AND 7 OR col4 <= 0.21) AND col0 <= 1 AND (((col4 >= 9.81 AND col1 > 9.33 OR col3 > 4 AND col3 > 4 AND (col1 >= 5.41) AND col1 = 6.30 AND (col0 = 1)))) OR col4 = 5.37 OR col3 IS NULL))))) OR (((col0 > 7) AND col3 IS NULL AND col3 > 6 OR col4 >= 5.33) AND col0 > 2) AND col4 > 1.59 AND col0 IN (SELECT col3 FROM tab0 WHERE col3 >= 9 AND col3 >= 4) AND col4 > 8.41 OR (col3 = 4) AND (((col3 < 6))) OR col3 >= 2)```

**Comment by jarohen** [comment]
assume this was resolved?
