### ISSUE TITLE
doc instructions fail with 'can't find time-literals'

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2146]
following the instructions in `HACKING`, you get a 'can't find time-literals namespace' error

cause is that api's `core2.edn` namespace depends on it, but the dep is in the root deps.edn (which isn't shipped), and something else requires core2.edn.

choices:
* move time-literals dep to the api `deps.edn` (if we're happy with that as an API dependency)
* move `core2.edn` and the data-readers into `dev` if nothing in the main src (outside of the tests) depends on it
* move `core2.edn` and the data-readers into the server (I think that's the other thing that depends on them)
* probably some others. likely worth some analysis as to what we actually want/need here.

**Comment by deobald** [comment]
Instructions in `HACKING` are now correct, but this issue is still outstanding with the same potential solutions.
