### ISSUE TITLE
Create a mark -> semi/anti join rule.

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2161]
Problem exists for SQL and Datalog. Rewriting any plan from a join where columns from the rhs are returned to one where they are not (such as semi/anti join) requires knowing that column is not referenced elsewhere in the plan, this is difficult with local rewrites. See examples below, the former of which cannot be rewritten as `fn` must be returned.

```
'{:find [order fn]
      :where [(match :order {:id order, :customer customer})
              (q {:find [fn]
                  :in [customer]
                  :where [(match :customer {:id customer, :firstname fn})]})
              [(= "bob" fn)]]}
```
vs
 
```
'{:find [order]
      :where [(match :order {:id order, :customer customer})
              (q {:find [fn]
                  :in [customer]
                  :where [(match :customer {:id customer, :firstname fn})]})
              [(= "bob" fn)]]}
```    

-----

Should replace the apply-predicative-subquery shortcut at plan time. However we may need to be careful when removing cols (see comment). 

; subquery anti/semi optimisation
;; EXISTS - type subqueries can be optimised in certain cases to semi/anti joins.

;; A decision was taken to optimise when we build the initial plan, rather than as a rewrite rule
;; due to the possibility of inter node dependence on the pre-optimised cross apply:

;; imagine a node [:select $exists [:apply :cross-join ...]] we may chose to optimise this away into [:apply :semi-join ...]
;; a problem arises in that the projected column set of the previous relation contains columns that are not returned by the :semi-join.
;; Namely the $exists column. This can interfere with other rules and introduce ordering dependencies between rules.

;; e.g decorrelation rule-9 caused a problem in this case as it introduced a dependency in the group-by on the $exists column - only to later find
;; that column had been rewritten away by the semi/anti join apply rule.

**Comment by refset** [comment]
Is the performance gain enough to justify this level of work soon? We probably don't know yet. Avoiding cross joins is the main aim.

**Comment by mbutlerw** [comment]
An idea here is that if we make sure to project away the `mark` column immediately (which we do in XTQL), we can probably ensure that its not referenced elsewhere.

**Comment by jarohen** [comment]
> An idea here is that if we make sure to project away the mark column immediately (which we do in XTQL), we can probably ensure that its not referenced elsewhere.

worked around this by explicitly projecting it again - if we don't use it, we can add other rules to remove it at our leisure
