### ISSUE TITLE
Interval literals ClassCastException if used in `VALUES`

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2171]
They work if used as straight literals in project, but not in VALUES.

```clojure
(t/deftest test-interval-literal-cce-271
  (c2/sql-query tu/*node* "select a.a from (values (1 year)) a (a)" {}))
```

**Comment by jarohen** [comment]
notes to self:
* `1 year` is being planned as a call to `single-field-interval`
* EE says this call yields a type of `:interval :year-month`, returns a `PeriodDuration`
* `:table` then wants to put a `PeriodDuration` via `types/write-value!`, which (for PD) expects an `IntervalMDNVector`. 
* sad times ensue.
