### ISSUE TITLE
Bump `time-literals` version

### ISSUE THREAD

**Issue by deobald** [xtdb/crux#2178]
The most recent version of `time-literals` (and thus `cljs.java-time`) does not have a license included in the artifact, which means the `maven-license-plugin` (from Neo4j) that we use can't find a license when it crawls our deps.

The next version of `time-literals` should include the license in the release artifact, but it may be a long time before the lib sees its next release. When it does, we should bump the version we depend on.

https://github.com/henryw374/time-literals/issues/7
https://github.com/henryw374/cljs.java-time/issues/10

**Comment by jarohen** [comment]
now vendored
