### ISSUE TITLE
Ability to compare dates/times/timestamps of different types

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2184]
Users are allowed to submit (for example) system time/app time constraints using different date-time types - we should convert them as required, per the spec:

* §4.6 (p37) specifies how to convert between different types
* §7.6 (General Rules, 1.c.ii.1, p356) specifies how to compare date-times in `FOR SYSTEM TIME` clauses. In this case, it says to cast the argument into the type of the system time cols (which, for us, is always timestamp-tz).
* §8.20 (General Rules, 4, p483) specifies how to compare date-times in period predicates (used for application time filters).

* Period predicates were introduced in xtdb/xtdb#2174. There were some coercions introduced into the front-end planner (as a short-term fix), but these will not work when the provided values aren't compile-time literals - these comparisons need to be handled by the expression engine, and the planner coercions removed.
* May depend on xtdb/xtdb#2176

**Comment by wotbrew** [comment]
As part of resolving xtdb/xtdb#2176 I added a basic equality behaviour ([d633ea0a](https://github.com/xtdb/core2/commit/d633ea0ac2a3e01a1b97c3b5572627789f2ab0ea)) to demonstrate the clock influencing a timestamps implicit zone. This should be taken as a demonstration only, test coverage is minimal (just enough to show this behaviour). 

I did start thinking about different units and so on but realised to test this well would likely extend to table and/or prop tests to properly cover overflow, unit mixing and so on given the dimensionality of the problem
