### ISSUE TITLE
`DELETE` with no `WHERE` causes IAE

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2198]
i.e `DELETE FROM foo`

Repro:

```clojure
(with-open [node (node/start-node {})]
  @(node/await-tx-async node (c2/submit-tx node [[:sql "DELETE FROM foo"]])))
```

**Comment by jarohen** [comment]
Fixed the original issue in the metadata compiler - getting `DELETE FROM foo` working now depends solely on xtdb/xtdb#2038, so I'll close this one and add a note to xtdb/xtdb#2038 to re-check this one.
