### ISSUE TITLE
More principled support of postgres specific syntax

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2203]
To support many/most popular postgres clients, some syntax compatibility is necessary, for example - the parameter placeholder style sent to the server is `$1,$2,$3` instead of `?, ?, ?`.

To get us going, the techniques currently used by the server for postgres sql compatibility include 

- string replace for param convention, which will rewrite string literals which include $\d. This is simply dangerous.

- string matching with regex/starts-with to interpret pg specific commands (e.g `BEGIN`) and canned responses to queries issued by connections automatically in commonly used libraries. This may be brittle, may accidentally match queries it shouldn't, not match when it should, and not participate in nice parse error generation if they are gotten wrong.

While these techniques may be ok for the current 'almost toy' pgwire server, I would like us to consider how we might better solve the sorts of parsing problems posed by pg compatibility.

I wonder if these problems may be best solved by parsing and substituting of pg specific ast nodes with XT compatible ones. Could the existing tools for these sorts of problems be leveraged (our sql parser)? After all these extensions often sit within the broader 'sql 2011' grammar, such as the param placeholder style.

One potential issue considering ast -> ast transformation, is the node api takes opaque strings for query and as `:sql` tx ops, if this is the case the output of any pg -> xt transform must be a string, and our ast is not currently intended to be printed as an equiv SQL string.

**Comment by jarohen** [comment]
cheers @wotbrew :pray: as discussed, have broken this down into different cards:
* xtdb/xtdb#2204 
* xtdb/xtdb#2205 
* For `BEGIN`, we can continue to implement this as a string replacement in the pgwire server for now - we may consider adding it as an alias to the parser in future but for now, let's err on the side of fewer changes to the parser where possible (i.e. excluding xtdb/xtdb#2204)

Hopefully the pgwire server can then nigh-on completely re-use the core parser to understand the SQL statements it receives?

**Comment by jarohen** [comment]
closing now that we have individual cards :slightly_smiling_face:
