### ISSUE TITLE
`INSERT` should abort the transaction if there's a conflict in the implicit `(id, APP_TIME WITHOUT OVERLAPS)` primary key

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2219]
Currently, `INSERT` behaves more like an upsert - if a document with that `id` is already present then it updates it in the given app-time range. This behaviour is more similar to the existing `:put` semantics, but the spec suggests this should abort the transaction with a constraint violation.

(Of course, we may choose to deliberately deviate from the spec here?)

**Comment by jarohen** [comment]
choosing a deliberate deviation from the spec here - put semantics are mighty useful 🙂

**Comment by refset** [comment]
Makes sense - as long as the spec behaviour can be achieved somehow if really needed, e.g. via `WHERE NOT EXISTS ( )`

**Comment by jarohen** [comment]
@refset SQL `MERGE` might do that?
