### ISSUE TITLE
Check static errors on submit

### ISSUE THREAD

**Issue by hraberg** [xtdb/crux#2221]
We should parse and analyze, and check that there are no errors (there's an attribute for this, but we first also want to check parse errors) -before- putting things on the log. This involves adding a new error and analysis that INSERT contains an id (either explicitly, or in the projected columns in its SELECT). These errors will be thrown / presented directly to the submitter.

Could mean that we can avoid rechecking this when planning during actual transaction processing.

Note that analysis currently isn't dependent on the database itself, so this should be possible to do based on the query itself only.

The easiest way to get the actual errors is to call `core2.sql.analyze/analyze-query` but this also includes scope information which isn't needed and also costly to calculate.

* [x] If a user misses an `id` column in an `INSERT`, it shouldn't break the node
* [x] string literals with double quotes (instead of single quotes) shouldn't break the node (prevents subsequent commits with correct quoting also), same for `DATE "1998-01-01"` (needs to be `DATE '1998-01-01'`)
* [x] UPDATE without qualified column `UPDATE Prop_Owner SET customer_number = 827 WHERE property_number = 7797;`
* [x] duplicate columns `INSERT INTO foo (id, application_time_start, application_time_start)`

... and probably loads more

**Comment by refset** [comment]
Short of creating a comprehensive fix, can we (for now) just keep track of & skip transactions that are erroneous to the extent of breaking the node?

As a user (or workshop delegate (or person preparing a workshop)), it feels reminiscent of happily working in your Clojure REPL and then suddenly having a segfault crash the JVM :slightly_smiling_face:

**Comment by jarohen** [comment]
@refset that'll be xtdb/xtdb#2256 (just created from an existing note)
