### ISSUE TITLE
Support SQL queries without `FROM`

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2225]
If a SQL statement doesn't contain a `FROM`, you can think of it as selecting from `[:table [{}]]` (i.e. 1 row, no cols).

**Comment by wotbrew** [comment]
related [#324](https://github.com/xtdb/xtdb/issues/2203)

**Comment by jarohen** [comment]
Worth double-checking the spec to see whether it has any nuances - this is just me guessing.

**Comment by FiV0** [comment]
@jarohen and me checked the spec an this is not officially supported, but `"VALUES (1)"` is and that currently works. So we are deprioritizing for now. Postgres and many others support the query without `FROM`, so we might revisit.

An article that highlights the different supported options/alternatives: https://modern-sql.com/use-case/select-without-from e.g. this works `SELECT GREATEST (4, 2) FROM (VALUES (1)) x`, unlike `SELECT GREATEST (4, 2) `
