### ISSUE TITLE
Should the temporal index yield zero-width periods?

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2257]
see (e.g.) https://github.com/xtdb/core2/blob/e4953c89276dc62bf4e293801d1d83a28e806c65/test/core2/api_test.clj#L255-L286

**Comment by refset** [comment]
Quite possibly not be applicable here, but it might help someone to note that 'coalescing' is a term used in the literature https://homes.cs.aau.dk/~csj/Thesis/pdf/chapter2.pdf

**Comment by refset** [comment]
Noting the related failing eviction test to be solved as part of this card https://github.com/xtdb/xtdb/commit/c2d5e68e6ec6242aaa6021fb67d953253d491b16#diff-03eb6da82c1c5e581e6749ffc715e96c50cce2b49c272ffa26d186479b12cb22R489-R490
