### ISSUE TITLE
Case sensitivity with period references.

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2280]
I've been using lower-case column names extensively so far, e.g. `Prop_Owner.system_time_start` - which perhaps is the real mistake (should we allow lower-case?) - but this was a little surprising to see:

```
ERROR:  Invalid SQL query:
  - Prop_Owner.system_time is not a valid period. Please use a qualified reference to APPLICATION_TIME or SYSTEM_TIME: at line 4, column 8
```

Current Behaviour with regards to period refs

```
;; valid
(plan-sql
        "SELECT foo.bar
        FROM foo
        FOR application_time AS OF CURRENT_TIME")

(plan-sql
        "SELECT foo.bar
        FROM foo
        FOR system_time AS OF CURRENT_TIME")

(plan-sql
        "SELECT foo.SYSTEM_TIME OVERLAPS foo.APPLICATION_TIME
        FROM foo")

;;invalid

(plan-sql
        "SELECT foo.system_time OVERLAPS foo.application_time
        FROM foo")

;; doesn't realise projected foo.sYstem_time_start and
;; the system_time_start added by the period_spec are the same col

(plan-sql
        "SELECT foo.sYstem_time_start
        FROM foo
        FOR system_time AS OF CURRENT_TIME")```

**Comment by jarohen** [comment]
this one is a subset of xtdb/xtdb#2267, but I reckon we could pick this off specifically, especially as it seems the error message is already being thrown from the place that'd need to handle it

**Comment by refset** [comment]
Having spoken with @mbutlerw I realise now that the uppercasing of `foo.APPICATION_TIME` is actually correct and very helpful (so we probably shouldn't support lower-case, after all), because as per the spec/grammar these are "period references" and shouldn't be thought about as columns (they can't be projected etc.). I find it somewhat confusing that the "dot" syntax (`foo.*`) is used for both, but that's just how it is. I will continue to use lower-case `foo.application_time_start` (etc.) as column names.

**Comment by jarohen** [comment]
> Having spoken with @mbutlerw I realise now that the uppercasing of foo.APPICATION_TIME is actually correct

@refset, @mbutlerw sure? in the spec it looks like `<period reference>` bottoms out in an `<identifier>`, and those tend to be case-insensitive...

**Comment by jarohen** [comment]
Wider card is xtdb/xtdb#2267, but we'll put in a workaround for now to make the planner recognise differently-cased period references

**Comment by refset** [comment]
To clarify, I meant correct in the sense of "sensible and proper" rather than "exacting to the spec" :)
