### ISSUE TITLE
Differing Array lengths for the same col: fixed-size-list vector already exists {}

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2286]
```
INSERT INTO t3(id, data) VALUES (1, [2, 3])
INSERT INTO t3(id, data) VALUES (2, [5, 6, 7])
```
or
```
INSERT INTO t3(id, data) VALUES (1, [2, 3])
INSERT INTO t3(id, data) VALUES (2, ['dog', 'cat'])
```

**Comment by jarohen** [comment]
Thought this was a relatively straightforward fix to make the EE use lists rather than fixed-size-lists, but this then rolls us into a DUV NPE on `DenseUnionWriter/.setPosition` (mentioned in writer.clj as a known issue). Parking til post SL.
