### ISSUE TITLE
Explore Possible Temporal Operations

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2295]
1. Extend temporal range for existing Entity
2. Add new temporal range for existing Entity
3. Add new temporal range for existing Entity but with differing content.

**Comment by refset** [comment]
It's possibly worth understanding how/why others do bitemporal things differently outside the 2011 standard, e.g. https://docs.teradata.com/r/Axxld~N4d3FvDqf8jv2aZQ/3B~YaS5mz2dtf3JYnvRgzA EDIT: archive.org to the rescue: https://web.archive.org/web/20210508005621/https://docs.teradata.com/r/Axxld~N4d3FvDqf8jv2aZQ/3B~YaS5mz2dtf3JYnvRgzA

**Comment by refset** [comment]
IIRC this was because UPDATE requires the content of a row to change in order to adjust the history, or at least it's not a great UX
