### ISSUE TITLE
Transaction ops should accept ZDTs (etc.) for `:app-time-start` & `-end` opts

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2379]
This is necessary for transaction functions that work with time, because SCI doesn't have access to do `(util/->instant app-start)` when processing the ZDTs returned by queries inside the function.

**Comment by refset** [comment]
It looks like the easiest course of action would be something like:
```clojure
(->> tx-ops
     (map #(update % 2 (fn coerce-app-times [opts]
                         (-> opts
                             (util/maybe-update :app-start-time util/->instant)
                             (util/maybe-update :app-end-time util/->instant))))))
```
..._before_ serializing (& spec conforming), here:
https://github.com/xtdb/core2/blob/31255227aa1b3c3e2d104da8a2b13310b7124503/core/src/main/clojure/core2/tx_producer.clj#L311

Are there better options?

**Comment by jarohen** [comment]
@refset: `core2.types/write-value!` (used in `->put-writer`, `->delete-writer`, etc) _should_ Just Work™ if you pass it ZDTs instead, suspect if you add it to the spec it'll be fine?

**Comment by refset** [comment]
I tried changing:
```clojure
(s/def ::app-time-start inst?)
;; to
(s/def ::app-time-start (s/or :inst inst?
                              :zdt (partial instance? java.time.ZonedDateTime)))
```

But got this:
```clojure
Unhandled java.lang.ClassCastException
   class core2.vector.writer.ScalarWriter cannot be cast to class
   core2.vector.IListWriter (core2.vector.writer.ScalarWriter is in unnamed
   module of loader clojure.lang.DynamicClassLoader @1192f4bf;
   core2.vector.IListWriter is in unnamed module of loader 'app')

        IVectorWriter.java:   24  core2.vector.IVectorWriter/asList
                 types.clj:  180  core2.types/eval42535/fn
                 types.clj:   33  core2.types/eval42361/fn/G
           tx_producer.clj:  185  core2.tx-producer/->put-writer/write-put!
           tx_producer.clj:  270  core2.tx-producer/write-tx-ops!
```

I guess the conform needs to (somehow) ignore the `s/or`, or the writer needs to be adapted?

**Comment by refset** [comment]
This works (plus adding the zdt import):
```clojure
(s/def ::app-time-start #(or (inst? %)
                             (instance? ZonedDateTime %)))
```
Is that good/idiomatic enough?
