### ISSUE TITLE
Datalog queries require an explicit table

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2386]
Currently this defaults to the `xt_docs` table if the user doesn't supply one explicitly.

* [x] Land xtdb/core2#624/#625
* [x] Remove default in the Datalog compiler - can just add (e.g.) `:where [(match xt_docs [{:id e}])]` at a minimum (i.e. still remove `:where [[e :_table foo]]`), or fully migrate to `match` syntax

---

Options:
* Continue with `:where [[p :_table :table-name], ...]`. 
  * Can't have table names as symbols here (to keep coherence with tx-ops xtdb/xtdb#2385) without visual ambiguity - looks like a logic-var. (in practice, we'd likely treat `:_table` triples different)
  * Rename `:_table` to `:xt/bag`?
* `:from`:
  ```clojure
  {:find ...
   :from {u users, p posts}
   :where ...}
  ``` 
  * Could extend from to include the temporal filters: `:from {u (users (for-app-time-at ...)), p posts}`

* Validation error if the user doesn't supply one (existing tests migrated to explicitly specify `xt_docs`

**Comment by refset** [comment]
Bikeshed discussion on naming here: https://juxt.slack.com/archives/G018EA25K71/p1678704674690529

**Comment by jarohen** [comment]
xtdb/core2#671 and xtdb/core2#672 landed
