### ISSUE TITLE
app-time -> valid-time

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2402]
* Columns to be named `:xt/valid-from`/`:xt/valid-to`,`:xt/system-from`, `:xt/system-to`
* `:for-app-time` etc -> `:for-valid-time`
* `:for-sys-time` etc -> `:for-system-time`
* `:xt/app-time` -> `:xt/valid-time`
* `:xt/sys-time` -> `:xt/system-time`

In SQL: 
* columns will hence be `xt$valid_from` etc. 
* `FOR VALID_TIME AS OF` etc.

**Comment by refset** [comment]
Liberally adding more aliases on the Datalog side generally sounds reasonable, but I'm currently against the idea of _promoting_ anything other than app/sys time (valid/transaction time should be for backwards compatibility only). Adding `:xt/*` namespace aliases is sensible given https://github.com/xtdb/xtdb/issues/2357

**Comment by refset** [comment]
Update: +1 for valid-time from me and @malcolmsparks

**Comment by refset** [comment]
`:xt/system-from`, `:xt/system-to`
