### ISSUE TITLE
[feature request] Sorting pulled entities

### ISSUE THREAD

**Issue by piotr-yuxuan** [xtdb/crux#2412]
Hello,

Thanks for this project that looks great. I've been using XTDB 1.x for a year now and I'd have found useful is the ability to sort pulled entities. We can already `:limit` how many entities are pulled, which is great, but it could be made even more useful with the ability to sort, for example to return the latest. Do you think this feature might somehow make its way into core2?

Best,
Piotr

**Comment by refset** [comment]
Hey @piotr-yuxuan thanks for your keen interest!

We have some early ideas to make handling these kinds of advanced pull requirements (filtering/sorting/nested values etc.) more easily achieved via regular subqueries, which are somewhat more verbose but much more powerful, e.g.
```clojure
{:keys [blog author comments]

 :find [(construct [content published])

        (q {:find [(construct [name avatar])]
            :in [author-id]
            :where [($ :authors [{:id author-id} name avatar])]})

        (q {:find [(array-agg
                    (construct [comment {:comment-author author-name} published]))]
            :in [blog-id]
            :where [($ :comments [{:blog-id blog-id} comment
                                  {:author {:name author-name}}
                                  published])]
            :order-by [[published :desc]]
            :limit 2})]

 :in [blog-id]
 :where [($ :blogs [{:id blog-id} author-id content published])]}

;;=>
{:blog {:content "..."
        :published #inst "2023-03-30T12:00:00Z"}
 :author {:name "James"
          :avatar "https://..."}
 :comments [{:comment "..."
             :comment-author "Jeremy"
             :published #inst "2023-03-30T12:05:34Z"}
            {:comment "..."
             :comment-author "Jon"
             :published #inst "2023-03-30T12:10:52Z"}]}
```
(note: this is just a sketch, neither `construct` or `array-agg` are implemented yet, and it doesn't factor in recursion)

If you sign up for an account on [Discuss XTDB](https://discuss.xtdb.com) I can add you to a private forum to continue the conversation :)

**Comment by piotr-yuxuan** [comment]
It may be an issue on my side but I was left with an impression that pull queries were performing much faster than subqueries. Happy to hear more constructs are on their way, looking to trying them.

**Comment by refset** [comment]
> pull queries were performing much faster than subqueries

That can definitely be the case in 1.x because of the nature of how `pull` retrieves entire documents in a single I/O (vs an I/O per individual attribute-value), but should not be the case in the future design here due to the major differences in the new storage, indexing and caching strategies.

**Comment by refset** [comment]
XTQL covers this already :slightly_smiling_face:

**Comment by piotr-yuxuan** [comment]
That's a very good reason to close such feature request! :+1:
