### ISSUE TITLE
Better option for `xt__id` in sql

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2416]
With xtdb/core2#741 `INSERT` as well as `SELECT` statements become a bit unwiedely as the column name `xt__id` seems a bit off. Maybe worth adding an alias.

**Comment by jarohen** [comment]
As discussed, let's try to avoid sugars and aliases where possible at this stage - not averse to ideas here about how to make things simpler across-the-board but would prefer not to introduce edge cases.
