### ISSUE TITLE
Top-level Datalog set operators

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2470]
At the moment, it's only possible to introduce unions through a `union-join`, as part of an existing query. In RA, though, union is an operator in its own right - `union-join` (nor `or-join`) aren't fundamental primitive operators.

e.g.

```clojure
(xt/q node
      '(union-all {:find ...
                   :where ...}
                  {:find ...
                   :where [(q (union-all {:find ...}
                                         {:find ...}))]}))
```

maybe a vector:
e.g.

```clojure
(xt/q node
      '[:union-all {:find ...
                    :where ...}
                   {:find ...
                    :where [(q (union-all {:find ...}
                                          {:find ...}))]}])
```

* Operations:
  * `union`/`union-all`
  * `intersect`/`intersect-all` (SQL naming)
  * `except`/`except-all` (likewise)
* Semantics to be the same as SQL (i.e. use the existing RA operators)

This should allow us to deprecate union-join, as such queries can be implemented in terms of a unioned set of subqueries

**Comment by jarohen** [comment]
Chatted with @refset - needs some further thought:

* We currently `(-> q (assoc :basis ...))`, which we couldn't do if the top level is anything apart from a map.
* We rely on top-level `:in` params to know what the arguments to the query are.

**Comment by mbutlerw** [comment]
Blocked in light of XTQL progress. Likely some of this work will be folded in when adding set ops to XTQL but not worth merging.
