### ISSUE TITLE
RFC: Should we allow namespaced logic vars?

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2471]
Question: logic-vars are represented as Clojure symbols in Datalog queries. Should we explicitly disallow namespaced symbols - and, if not, how should they behave?

Considerations:

* In Clojure, local variables must be simple symbols - qualified symbols are resolved against the runtime environment of the namespace.
* Logic variables in many ways behave like local variables, so we should avoid ['uncanny valley'](https://en.wikipedia.org/wiki/Uncanny_valley) territory where possible.
* Our match syntax is heavily inspired by Clojure's destructuring 
  * albeit reversed - `{:a a}` rather than `{a :a}` - because we wanted to be able to express (e.g.) `{:a 4, :b 4}` for `a = 4 and b = 4`, which wouldn't be allowed as `{4 :a, 4 :b}`.
  * `($ :table [a b])` (essentially) desugars into `($ :table {:a a, :b b})`, in the same way as `{:keys [a b]}` (again, essentially) desugars to `{a :a, b :b}`.
  * `{:keys [user/a user/b]}` and `{:user/keys [a b]}` desugar into `{a :user/a, b :user/b}`, but Datalog has implicit unification - so if `($ :table [user/a product/a])` were to desugar to `{:user/a a, :product/a a}`, there'd be an implicit `user.a == product.a` constraint added.
* Under 1.x:
  * using triples, a user would have to pick explicit names for each of these columns - `[[e :user/a user-a], [e :product/a product-a]]`
  * pull preserves full namespace qualification of keywords
  
Options:

1. `($ :table [user/a product/a])` desugars to `($ :table {:user/a a, :product/a a})` (i.e. accept implicit unification gotcha).
2. `($ :table [user/a product/a])` desugars to `($ :table {:user/a user/a, :product/a product/a})` (i.e. namespaced LVs are allowed).
3. Namespaced keywords are disallowed in match vector syntax, namespaced LVs are disallowed - users must use map syntax: `{:user/a user-a, :product/a product-a}`.
4. Remove match vector destructuring sugar for simplicity (vs e.g. potentially surprising uncanny valley of `let` scoping vs logic var scoping) and continue to allow quoted namespaced symbols as logic vars (given symbols are opaque to the query engine)

Decision: 2 - in practice (particularly with xt/id) this hasn't felt as unnatural as we'd feared.

**Comment by refset** [comment]
For completeness:

4. Remove match vector destructuring sugar for simplicity (vs e.g. potentially surprising uncanny valley of `let` scoping vs logic var scoping) and continue to allow quoted namespaced symbols as logic vars (given symbols are opaque to the query engine)

**Comment by FiV0** [comment]
One potential pro of namespaces symbols is that you get automatically namespaced  keywords in your result set.
```clj
{:find [user/id order/id]
 :where [(match :user [user/id])
         (match :order [order/id user/id])]}
;; =>
[{:user/id 1 :order/id 2} ....]
```
or
```clj
{:find [user/id order/id]
 :where [(match :user {:id user/id})
         (match :order [{:id order/id}] user/id)]}
```

**Comment by FiV0** [comment]
Our operators currently make a lot of usage of `name`. As the the namespaced logic vars will be present in the RA (as namespaced symbols) this will likely cause some issues which we have currently not tested against. This might be a separate issue of "Should the RA only allow for simple symbols or not?".

**Comment by FiV0** [comment]
Modified left-join example from `datalog-test.clj` only change are namespaced symbols. Fails with `NPE`.
```clj
(deftest test-left-join
  (xt/submit-tx tu/*node*
                '[[:put :xt_docs {:xt/id :ivan, :name "Ivan"}]
                  [:put :xt_docs {:xt/id :petr, :name "Petr", :parent :ivan}]
                  [:put :xt_docs {:xt/id :sergei, :name "Sergei", :parent :petr}]
                  [:put :xt_docs {:xt/id :jeff, :name "Jeff", :parent :petr}]])

  (t/is (= [{:e :ivan, :c :petr}
            {:e :petr, :c :sergei}
            {:e :petr, :c :jeff}
            {:e :sergei, :c nil}
            {:e :jeff, :c nil}]
           (xt/q tu/*node*
                 '{:find [foo/e c]
                   :where [(match :xt_docs {:xt/id foo/e, :name name})
                           (left-join {:find [foo/e c]
                                       :where [(match :xt_docs {:xt/id c})
                                               [c :parent foo/e]]})]}))

        "find people who have children"))
```
corresponding RA
```clj
[:project
 [foo/e c]
 [:left-outer-join
  [{foo/e foo/e}]
  [:project
   [{name _r0_name} {foo/e _r0_foo/e}]
   [:rename
    {name _r0_name, foo/e _r0_foo/e}
    [:project
     [{foo/e xt/id} name]
     [:scan
      {:table xt_docs, :for-valid-time nil, :for-system-time nil}
      [name xt/id]]]]]
  [:project
   [foo/e c]
   [:project
    [{c _r0_c} {foo/e _r0_foo/e}]
    [:rename
     {c _r0_c, foo/e _r0_foo/e}
     [:project
      [{c xt/id} {foo/e parent}]
      [:scan
       {:table xt_docs, :for-valid-time nil, :for-system-time nil}
       [parent xt/id]]]]]]]]
```

**Comment by jarohen** [comment]
closing, opting for 2.
