### ISSUE TITLE
UX consistency for transaction functions

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2480]
When writing up the docs for tx-fns it's become painfully obvious that we're (unnecessarily) exposing a number of implementation details and a brief history lesson of Core2.

Particularly:

* We're expecting users to put functions into the `xt_docs` table (which no longer has special status within C2)
* Users have to wrap functions with the `#xt/clj-form` reader macro.

**Comment by mbutlerw** [comment]
:put-fn -> :put xt/txs pre-log

Mirror C1 syntax (probably xt/fn)

Implicitly wrap in #xt/clj-form (or the object)
