### ISSUE TITLE
Case/punctuation sensitivity

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2481]
Problem: idiomatically, Clojure users use kebab-case. In SQL, though, tables or attributes with dashes or slashes need to be explicitly quoted.

Our overall aim is that users can query the same data from both Datalog and SQL; and, ideally, both should 'feel idiomatic'.

## Dimensions:

* Case sensitivity: whether `:foo-bar` and `:Foo-BaR` are considered the same attribute
* Punctuation sensitivity: whether `:foo-bar` and `:foo_bar` are considered the same attribute
* Recursive normalisation: whether to extend this behaviour into nested structs ('recursive') or preserve the casing/punctuation once you get past the top-level.

## Prior art

* We're not 100% sure on what the spec mandates (if anything - it may be 'implementation defined'). It does define 'case normal form' for identifiers (essentially up-casing).
  * SQL tooling that generates queries may expect that it can specify columns in any case. If so, it may well normalise column names itself (to upper-case).
  * In Postgres, no matter what case the user provides, the client seems to lower-case the column names in the result (even if this means returning duplicate column names).
  * In MySQL, it seems to preserve the case that the user specifies in the query, but columns that differ only in case refer to the same underlying column on disk.
  * Nothing in this world does punctuation normalisation, obviously.
* In Clojure:
  * two documents `{:foo-bar 42}` and `{:Foo_BaR 42}` would be considered unequal - these would be considered equal under case/punctuation insensitivity.
  * symbols/local variables (on which logic-vars are modelled) are case/punctuation sensitive - two local variables with different casing would be considered different local vars.
  
## Preferences to take into account when choosing a solution (RFC)

* We'd rather not have either Datalog or SQL be 'second-class' if possible - they're equal peers.
* We'd prefer to respect the casing/punctuation that the user provides us, if possible. (i.e. avoid the postgres "we'll just lower-case that for you" approach.)
* We'd prefer to continue to be SQL-spec compliant.
* We'd prefer to continue supporting namespaced keywords from Clojure, without imposing further restrictions on the user that aren't specified by Clojure itself.
* An ideal solution will Just Work™ in 99.9% of cases, in both languages, and have clear, simple rules for the remaining 0.1%.

## Options:

1. Case insensitive, punctuation insensitive
   
   e.g.
   
   ```clojure
   ;; document
   {:xt/id :foo, :foo-bar 42}
   
   ;; query
   {:find [Foo_bar foo-bar Foo-bar]
    :where [($ :Foo [Foo_bar foo-bar Foo-bar])]}
    
   ;; => [{:Foo_bar 42, :foo-bar 42, :Foo-bar 42}]
   ```
   
   Spec:
   
   * Tables and attribute names (keywords) are normalised before they hit the disk, to 'attribute normal form' (lower-case, dashes replaced with underscores). 
   * Namespace segments are replaced with dollars - e.g. `:foo.bar/baz` <-> `foo$bar$baz`. i.e. if a normalised column has more than one `$`, the last one is the namespace/name separator; the others are replaced with `.`s.
   * Logic-vars are case-sensitive - we return the case/punctuation that the user specifies. At the lowest level, when we actually go look for the attribute on disk, we normalise it.
   * For cases where the user doesn't specify a casing for every attribute (e.g. select-star), in Datalog we transform to kebab-case; in SQL we return the normal form.
   
   Benefits:
   
   * Probably 'Just Works™' in 99.9% of cases, for both Datalog and SQL, without any user thought/knowledge/customisation.
   * XT built-in columns have a natural translation between Datalog and SQL - e.g. `:xt/valid-time` in Datalog becomes `xt$valid_time` in SQL without any other rules/handling.
   
   Trade-offs:
   
   * Doesn't conform to Clojure/JVM equality - might be counter-intuitive?
     * OTOH, this likely comes under the '99.9% rule' - I highly doubt many Clojure devs are (deliberately) making use of this?
   * Doesn't fully round-trip documents - say you were to put `{:Foo_Bar 42}` and then select-star it, if we'd normalised the attribute names we won't still have the original case.
     * We could normalise it but store the first user-provided case, but hack.

2. Case sensitive, punctuation sensitive

   This behaves closer to Clojure's equality semantics - two attributes that differ in either case or punctuation are treated as different attributes.
   
   Benefits:
   * Fully round-trips documents - good for use cases that put arbitrary user supplied maps or JSON data into XT. You get out what you put in.

   Trade-offs:
   
   * Users that want to query data from both Datalog and SQL will likely have to standardise on case - snake case, I'd assume, given that `-`s in col-names need to be explicitly quoted in SQL.
     * We could offer Clojure users similar customisation to [clojure.java.jdbc](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/query)/[next.jdbc](https://github.com/seancorfield/next-jdbc/blob/develop/doc/result-set-builders.md) where they can supply a transformation function for keys to the query/submit-tx?
   * We'd likely have to introduce explicit aliases for the XT built-in cols - i.e. we'd likely have to support `:xt/valid-time`, `:xt/valid_time` as aliases in Datalog

3. Case sensitive, punctuation insensitive

   A halfway house. 
   
   Beneficial on the grounds that even fewer people likely deliberately have attributes that differ only in hyphens vs underscores, so we're less likely to run into the issues in option 1.
   
   Trade-offs:
   
   * Both of the above.

## Decision

We'll go with option 1. We accept that some documents with unidiomatic Clojure casing/punctuation will only be round-tripped if the user explicitly specifies the desired casing. We may decide to support SQL's explicit quoting semantics (i.e. preserving case) in the future.

* [x] xtdb/xtdb#2472

**Comment by refset** [comment]
@jarohen does `/` handling and keyword namespacing need to be considered at the same time?

**Comment by jarohen** [comment]
* add 4: ban it
* dots in namespaces
* namespace separators to become dollars or hashes instead? but note hash is ['bitwise XOR' in Postgres](https://www.postgresql.org/docs/9.4/functions-bitstring.html) and [a comment delimiter in MySQL](https://stackoverflow.com/questions/4300669/what-does-mean-in-sql), and #_ probably would clash with the Clojure reader

**Comment by jarohen** [comment]
> @jarohen does `/` handling and keyword namespacing need to be considered at the same time?

@refset I don't _think_ so. obv it may make sense to, but AFAICT they can be done separately, unless I'm missing something.
