### ISSUE TITLE
Limit on number of columns per table in `:xt/*`

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2484]
The assumption of C2 is that users put in documents that roughly resemble each other (+/- a couple of keys difference). The question is what happens if this assumption does not hold. With our current setup the following is kind of the worst case scenario. Every document has a different column set. With a 100 documents of 10 keys each this already breaks our query engine.
```clj
  (defn rand-str [l]
    (apply str (repeatedly l #(rand-nth "abcdefghijklmnopqrstuvwxyz0123456789"))))

  (defn random-doc [i]
    (let [data (repeatedly i #(rand-str 10))]
      (zipmap (map keyword data) data)))

  (defn random-docs [i]
    (->> (repeatedly i #(random-doc 10))
         (map-indexed #(assoc %2 :xt/id %1))))

  (defn wrap-in-puts [docs table]
    (map #(vector :put table %) docs))

  (def docs (wrap-in-puts (random-docs 100) :docs))

  (xt/submit-tx node docs)

  (xt/q node '{:find [e] :where [(match :docs {:xt/* e})]})

```
The last call results in 
```
1. Caused by java.lang.IndexOutOfBoundsException
   Method code too large!
```
Should we explicitly limit the number of columns (for now)? Make sure then even this extreme case is supported (even if it might be slow)?

Or the above with even just one doc:
```clj
  (xt/submit-tx node [[:put :docs (assoc (random-doc 200) :xt/id "large-doc")]])
  (xt/q node '{:find [e] :where [(match :docs {:xt/id "large-doc" :xt/* e})]})
```
EDIT:
As @refset has mentioned this also an issue for nested data so limiting the number of columns will not fix this issue.
```clj
  (xt/submit-tx node [[:put :docs2 {:xt/id "large-nested-doc" :doc (random-doc 2000)}]])
  (xt/q node '{:find [e] :where [(match :docs2 {:xt/* e})]}) 
```

**Comment by jarohen** [comment]
@FiV0 @armincerf we now seem to support ~200 cols here - would obviously like this to be higher but will de-prio for now unless you're still hitting this limit?

(have deployed a new SNAPSHOT with this fix)
