### ISSUE TITLE
Unify Arrow abstraction (readers/writers)

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2506]
We currently have two Arrow vector abstractions - one that was created originally for the indexer, one for the expression engine. They've got quite a lot of overlap and boilerplate - can we unify them?

**Comment by mbutlerw** [comment]
DISTINCT NULL with < 512 rows seems to return 2 rows rather than 1.  See failing tests in SLT index/random/1000 (slt_good_0.test has a single example)
