### ISSUE TITLE
Correct handling of `ExecutionException` in indexer.

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2530]
There two places in the indexer where we do sort of a query (sql indexing + getting a tx-fn). It can happen these throw an `ExecutionException` wrapping an `InterruptedException`. We should probably unwrap those so the indexer deals with these errors correctly.  

Maybe related to #2529.

**Comment by FiV0** [comment]
Pet theory for now: This might happen while an interrupt happens on some operation on the object-store.

**Comment by jarohen** [comment]
I haven't managed to reproduce this, so for now I've wrapped all of our derefs in a `rethrowing-cause` macro. Let's re-open this if we see this issue in the wild again
