### ISSUE TITLE
DISTINCT NULL with < 512 rows seems to return 2 rows rather than 1.

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2535]
_Originally posted by @mbutlerw in https://github.com/xtdb/xtdb/issues/2506#issuecomment-1523227505_
            
`DISTINCT NULL` with < 512 rows seems to return 2 rows rather than 1.  See failing tests in SLT index/random/1000 (slt_good_0.test has a single example)

**Comment by jarohen** [comment]
https://github.com/apache/arrow/issues/35588

**Comment by jarohen** [comment]
fix was released in Arrow 13

**Comment by jarohen** [comment]
we're now on Arrow 14 - could we confirm this is fixed

**Comment by FiV0** [comment]
Fixed in eaa29045
