### ISSUE TITLE
Small batch sizes might incur data loss.

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2536]
There seems to be some issue with smaller batch sizes. This also might not be deterministic so the numbers below might need to get tweaked for your machine.

```clj
(t/deftest data-loss
  (let [node-dir (util/->path "target/data-loss-on-smaller-batches")]
    (util/delete-dir node-dir)

    (with-open [node (tu/->local-node {:node-dir node-dir
                                       :rows-per-chunk 1000
                                       :rows-per-block 100})]
      (let [integer-count (* 5 1e3) #_(* 1 1e4)
            tx-batch-size 4]
        (doseq [tx (->> (range integer-count)
                        (map (fn [i] [:put :ints {:xt/id i :n i}]))
                        (partition-all tx-batch-size))]
          (xt/submit-tx node tx))

        (t/is (= integer-count
                 (-> (xt/q node '{:find [(count e)], :keys [id-count] :where [($ :ints {:xt/id e})]})
                     first :id-count)))))))
```

**Comment by jarohen** [comment]
@FiV0: I think this is an issue with the query - `tu/->local-node` uses a mock clock, so the tx-times (and hence valid times) increment by a day at a time. Without `{:for-valid-time :all-time}`, this goes into the future at around the tx-id 4900 mark (4904 for you last week, 4924 for me today, 5 days * 4 batch size).

If you can't repro this with the above flag, I'll close the card?

**Comment by FiV0** [comment]
:pray: @jarohen . My bad had not thought of the mock clock.
