### ISSUE TITLE
If a tx isn't included in a chunk before the retention period on the log runs out, it may get lost

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2548]
* All the nodes must agree on when to flush the live index.

One potential solution here would be for the nodes to put a 'let's all finish the chunk now if 8912 is still the latest tx' message on the tx-log, if they've got a chunk that's been idle for over ~a few hours? then, when that gets indexed, all the nodes flush the live index?

**Comment by refset** [comment]
@wotbrew might there be another edge case here where you need to, by default, always flush before `.close`-ing a node in the cluster because you have to assume it could be the last node? If so, I guess a flag to not flush might also be desirable - assuming you can somehow be sure that there's always at least one active node alive to do the flush before the retention period elapses.

**Comment by wotbrew** [comment]
> @wotbrew might there be another edge case here where you need to, by default, always flush before `.close`-ing a node in the cluster because you have to assume it could be the last node? If so, I guess a flag to not flush might also be desirable - assuming you can somehow be sure that there's always at least one active node alive to do the flush before the retention period elapses.

Yes agreed 👍 , but your prompting also made me rethink the 2nd approach taken here in regards to co-ordination (i,e there is none!). Have spoken to @@jarohen and will come at this again. Will make sure this point about closing is considered.

**Comment by jarohen** [comment]
Admittedly I was less concerned about the use case of the 'last node' - on the assumption that if a user closes down _all_ of the nodes in their cluster they either understand the impact of doing so, it's temporary enough that they don't hit the retention period (which I'm assuming will be of the order of days/weeks), or (if this is something they do frequently) they'll have an infinite retention log.

I'd be comfortable leaving this as a documented risk, unless others heartily object.

**Comment by jarohen** [comment]
So there seems to be something up between this PR and what's happened on 2.x in the meantime... :thinking: 

I've pushed two branches:
* https://github.com/xtdb/xtdb/tree/2548-flush-chunk-no-rebase, running [here](https://github.com/xtdb/xtdb/actions/runs/5762679621) - this is the PR as it stood earlier this morning, not rebased onto 2.x - this succeeded.
* https://github.com/xtdb/xtdb/tree/2548-flush-chunk-naive-rebase, running [here](https://github.com/xtdb/xtdb/actions/runs/5762687421) - this is the PR just rebased onto (the reverted) 2.x - this failed.
 
unfortunately I can't repro it locally.

**Comment by wotbrew** [comment]
Merged as #2672
