### ISSUE TITLE
Verifying the trie OLTP performance with a pre-baked set of AuctionMark tries

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2577]
Once we have the replication log from C1, let's pre-bake some tries and see how various queries then perform, relative to both C1 and the existing approach in C2.

* First, we can try with fully compacted tries. Because AuctionMark contains updates, this will involve pre-baking the T1, T2 and T3 tries (although the T2 and T3 tries won't be required for non-historical queries as all AuctionMark updates are done with vt=now->eot)
* Then, we can try with partially compacted tries and some log tries, to test the performance of log replay.

**Comment by wotbrew** [comment]
30 seconds of auctionmark at sf 0.1: s3://xtdb-datasets/auctionmark/am-01-30s.transit.json.tar.gz  

The file contains transit transaction vectors that can be submitted into a c2 node

Contains 1.4million rows, of which 60k have had one update, 5k have had 2. 280 have had 3. For more updates we need to run fo r longer but this trace already takes a long time to load in.

**Comment by wotbrew** [comment]
Will come back to this once more progress has been made on scan / history trees

**Comment by FiV0** [comment]
Marking this as done as the performance regarding point queries (via `xt/id`) has been verified.
