### ISSUE TITLE
Nodes can subscribe to files created/deleted in the object store, to reduce LIST requests

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2578]
Once a database grows above a certain threshold, we'll likely have many files on remote storage, to the point where it may be inefficient (not to mention uneconomical) to list the remote storage every time we need to check whether there's a new file (particularly as we'll need to paginate beyond 1000 files on S3, for example). 

We'd prefer to mirror the file listing locally by subscribing to updates, and then query a local cache rather than making requests of the remote store.

* API to be designed - although we may well just want this to live entirely within the object store for now rather than being exposed through its API (i.e. assuming that we'll mirror the whole object store).
* Consider the startup race condition - we'll want to list the remote store initially and also subscribe to updates, but we likely can't do these atomically. We don't want to miss files in the gap between the list and the subscription kicking in, but subscribing and then listing might mean we get an update for a file that's already there.
  * tbc, but I think we can assume that a deleted file is never re-put, if that helps?
* At a later date (out of scope for now) we may well want the creation of a file to (e.g.) stop the current node to stop background processing an index file (if another node's already done that work), or the creation of a chunk-finished marker to advance the node (if it's running slowly).

To be implemented for:
* the in-memory object store (an atom watcher, I'd guess)
* the file-system object store (using the `FileWatcher` API, I'd guess)
* S3. In this case, as a starter-for-ten, we could pipe S3 create/delete notifications to an SNS topic, and then (on node startup) create an SQS queue to subscribe to the SNS topic (deleting the queue on node shutdown).
  * If you do go this route, create a CloudFormation template in the XT repo that users can use for the S3 bucket, SNS topic and S3 events, along with an IAM role for nodes to create/delete SQS queues, and subscribe them to the topic.
  * May be a separate card...

**Comment by danmason** [comment]
We've decided against doing this for the in memory object store (should be cheap + easy enough to grab this from the on memory navigablemap) and for the filesystem object store (see #2640  for a bit more info).

We'll likely make separate tickets for doing all of the setup of this for other cloud based object stores, such (currently google cloud and azure)
