### ISSUE TITLE
Azure blob store should roundtrip documents containing UUIDs

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2602]
Context via: https://github.com/xtdb/xtdb/issues/1422#issuecomment-1612631604

> Ran into this issue yesterday when configuring the document-store to use Azure Blob Storage. And here is an example to replicate the behaviour https://github.com/philippkueng/xtdb-1422/blob/main/src/core.clj - I've also tried rocksdb and jdbc and both of them work just fine. It's only Azure failing consistently when inserting values of type UUID.

**Comment by jarohen** [comment]
we'll wait for #2603 to see whether that also fixes this one
