### ISSUE TITLE
Local filename caching setup for Azure Blobs Object Store  

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#2643]
- Similarly to the implementation within S3 (see #2633) - we want to set up local filename caching for list requests within the  Azure Blobs Object Store.
- This will likely be quite similar to S3 - we will need to make an initial list request and then react to all creation/deletion events in the bucket.
- We can push container events to Azure Event Grid and then subscribe to the event grid, filtering out the messages we need - see [Reacting to Blob storage events](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview)
- For infrastructure set up (including the blob container) - we will want some equivalent to the cloudformation template within AWS. This can be done in Azure using "Azure Resource Manager" templates: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/overview#template-deployment

**Comment by refset** [comment]
> There is no service level agreement around the time it takes for a message to arrive. It's not uncommon for messages to arrive anywhere from 30 minutes to two hours. As messages can arrive after some delay, use the etag fields to understand if your information about objects is still up-to-date.

[via [Reacting to Blob storage events](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview)]

If this really is the case then we might need to look at an alternative approach. That said I don't know understand the caching lifecycle well enough to know if this would actually be on a critical path.

**Comment by danmason** [comment]
Huh, I missed that.... that's not ideal :sweat_smile:

**Comment by danmason** [comment]
There is also the "change feed log" from the blob service - though that may also be fiddly to deal with, and its broken into hourly chunks that are updated every few minutes: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed?tabs=azure-portal
