### ISSUE TITLE
Defining the boundary between the scan operator and the IO layer

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2660]
As a first pass, let's define the boundary between the scan operator and the IO layer, so that we can work on the two components individually. This card involves the IO layer just meeting the new interface, even if it doesn't perform as well as the current IO layer. 

Particularly, taking into account:

* The scan operator will mostly know which pages it needs to access at the start of the query, but then shouldn't need to care about which order the pages are returned in. What information can the scan operator pass the I/O layer to enable the latter to intelligently schedule/prioritise requests between different queries?
* The scan operator may not need all the pages it's requested, so some degree of cancellation is likely necessary.
* The scan operator currently knows the indices of the pages it needs within a given file, but not necessarily what this means in terms of byte ranges. This information lives in the Arrow footer, but we'll want to define who's responsible for doing this translation (which should be evident in the scan/IO API boundary).
* As with all things Arrow, clear memory management expectations are crucial - the API should make clear at which point resources are the responsibility of the caller.
* Eventually, we'll be able to assume that if the scan operator only requests a few pages, it's likely to be a low latency query; if it requests most of a table, it's likely to be a scan-like query. If it's the latter, the IO layer will be able to ensure that such queries don't cycle any caches it might keep.

**Comment by wotbrew** [comment]
Some thoughts are documented here: https://github.com/xtdb/xtdb-team/blob/main/io/new-scan-thoughts.md

Will proceed to trying to get an iterator based interface together and integrated into scan
