### ISSUE TITLE
Reducing performance impacts of taking out a watermark

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2681]
We currently compact (each leaf of) the entire LiveHashTrie when opening a watermark.

This essentially means that every query and SQL DML statement causes log -> data compaction to take place.

Given the goal of the log is to delay the cost of sorting leaf data it would seem counterproductive to do this so eagerly.

Fixes/TODO:

- [x] move compactLogs call to scan

- [ ] get scan to sort-merge logs rather than calling compact

- [ ] call vec->reader lazily in openWatermark (i.e. just slice the vectors when the watermark is opened)

- [ ] cache the col-types within live-table, don't recalculate.

**Comment by jarohen** [comment]
as discussed, four changes to do:

1. move compactLogs call to scan
2. get scan to sort-merge logs rather than calling compact
3. call vec->reader lazily in `openWatermark` (i.e. just slice the vectors when the watermark is opened)
4. cache the col-types within live-table, don't recalculate.

**Comment by jarohen** [comment]
spin out (ii), close this one
