### ISSUE TITLE
Prevent double-loading of trie buffers on scan?

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2736]
I think we load trie-file buffers twice during a scan - once to check their metadata (to get `trie-file->page-idxs` in scan), and then once to calculate the merge plan (`trie/table-merge-plan`)

Haven't measured its impact on performance, but guessing it's not optimal 🙂

**Comment by FiV0** [comment]
Also worth rethinking if we don't want some toplevel metadata per trie to check if need to load the trie at all.

**Comment by FiV0** [comment]
Completed in #2753.
