### ISSUE TITLE
Confirm listObjects with prefix behaviour is consistent between object stores

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2740]
It seems like some object stores list objects recursively when listObjects is called with a directory. There are a few places that assume that it's a shallow list - i.e. it'll return directories and files within the current directory.

On S3 (and maybe the other cloud obj-stores) this requires setting a specific flag to limit the depth (which was only added relatively recently)

## Example of the issue

If we have a file directory, `foo` ,that has the following structure:
```
foo
  foo/example1
  foo/example2
  foo/bar/example3
  foo/bar/example4
  foo/baz/example5
```  

If we call to listObjects with prefix `foo`, we're seeing the whole nested list returned, ie:
```
foo/example1 foo/example2 foo/bar/example3 foo/bar/example4 foo/baz/example5
```

Where as what we want is a shallow list - only return files and directories at foo level, ie:
```
foo/example1 foo/example2 foo/bar foo/baz
```

### Subdirectories

Thinking on whether or not subdirectories should be distinguished from other filenames (ie, returned with a trailing `/`) - decided against it based on the below workaround that was being used in the compactor:
```
(->> (.listObjects buffer-pool "tables")
        ;; TODO should obj-store listObjects only return keys from the current level?
        (into #{} (keep #(second (re-find #"^tables/([^/]+)" %)))))
```

Shall likely make use of something with similar behaviour to the above regex in the implementation.

## To be verified/updated

- [x] #2842
  - These are all using list-files-under-prefix from the file-list namespace - this does not currently have the correct behaviour.
- [x] Remote File object store (Removed from code).
- [x] JDBC object store (Has similar behaviour to `list-files-under-prefix` and to be removed).
- [x] The buffer pools that implement their own listObjects implementations
   - In memory
   - Local

### Listing objects without a prefix

Exact behaviour here to be decided - from @/jms:
> We don't use it for a hell of a lot any more, it might be that it can be removed?

We do use it a fair bit in the tests - might be worth keeping it as a "fetch everything at all depths".

**Comment by danmason** [comment]
My current understanding of the issue:

If we have a file directory, foo , that has the following structure
```
foo
  foo/example1
  foo/example2
  foo/bar/example3
  foo/bar/example4
  foo/baz/example5
```  

If we call to listObjects with prefix `foo`, we're seeing the whole nested list returned, ie:
```
foo/example1 foo/example2 foo/bar/example3 foo/bar/example4 foo/baz/example5
```

Where as what we want is a shallow list - only return files and directories at foo level, ie:
```
foo/example1 foo/example2 foo/bar/ foo/baz/
```

**Comment by danmason** [comment]
Essentially, there's a few different places we'll need to verify/check/update this behaviour:
- Remote cloud object stores (S3, Azure, Google Cloud)
  - These are all using `list-files-under-prefix` from the file-list namespace. 
- Remote File object store.
- JDBC object store.
- The buffer pools implementing their own listObjects implementations
  - In memory
  - Local

**Comment by jarohen** [comment]
@danmason assuming you've now done the buffer-pool impls in #2850; remote fs obj-store has going, and JDBC is going (#2852)?
