### ISSUE TITLE
Is the MetadataManager still warranted?

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2752]
With the new index structure the metadata is tied to the trie files which need to be loaded anyway when doing a scan. This means the boundary between metadata loading and data loading becomes fuzzy. It's unlikely that the metadata manager then manages the buffers independently of scan. That then begs the question if we should just have a metadata ns that helps us with obtaining the metadata, but does no longer contain a stateful metadata manager object. The only purpose such an object would still serve is the caching of metadata.

**Comment by jarohen** [comment]
This does maintain a cache now, so it lives 🙂
