### ISSUE TITLE
Intermittent issue with slow buffer pool/object store 

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2772]
I only ran into this a couple of times but it sometimes seems the object store seems to hang for a while on some calls. Queries that normally take milliseconds all of sudden take seconds.
![Selection_017](https://github.com/xtdb/xtdb/assets/23086133/fb210a4e-9930-49a3-9ad7-4d50a6263f96)

**Comment by refset** [comment]
clj-async-profiler might be able to give some additional clues here (if it can peer deeper into `Files.copy`)

**Comment by FiV0** [comment]
Seems to be related to the `file-system-object-store`.

**Comment by FiV0** [comment]
Closed in #2787.
