### ISSUE TITLE
Incorrect query results using S3 object store

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2783]
It appears using the s3 object store causes incorrect results until the node is restarted

Same code works as expected on an in-memory object store 

Something to do with the file watching?

--- 

Repro:

```clojure
  (def node
    (node/start-node {:xtdb.s3/object-store {:bucket "xtdb-s3-test",
                                             :prefix (str "test-" (random-uuid))
                                             :sns-topic-arn "arn:aws:sns:eu-west-1:199686536682:xtdb-object-store-iam-test-bucket-events"
                                             :configurator (reify S3Configurator)}}))

  (doseq [tx (->> (for [i (range 1e6)] [:put :ints {:xt/id i, :n i}])
                  (partition-all 512))]
    (xt/submit-tx node tx))
  
  ;; should be 100k, observed: 78,400
  (time (count (xt/q node "select * from ints")))
```

Adding a finish chunk makes things more interesting: 

```clojure 
  (def node
    (node/start-node {:xtdb.s3/object-store {:bucket "xtdb-s3-test",
                                             :prefix (str "test-" (random-uuid))
                                             :sns-topic-arn "arn:aws:sns:eu-west-1:199686536682:xtdb-object-store-iam-test-bucket-events"
                                             :configurator (reify S3Configurator)}}))

  (doseq [tx (->> (for [i (range 1e6)] [:put :ints {:xt/id i, :n i}])
                  (partition-all 512))]
    (xt/submit-tx node tx))

  (tu/finish-chunk! node)

  ;; now returns 0, e.g finish-chunk! stops me from seeing any of the data
  (time (count (xt/q node "select * from ints")))
```
If the node is restarted after finish-chunk! however, the correct query results are returned. I think the re-initialisation of the file listing fixes the problem.

**Comment by danmason** [comment]
Some extra context from a conversation with @/wotbrew (thank you!)

> `finish-chunk!` will force any in-memory data to be flushed to object storage. This makes it possible for the restart to pick up the missing data
> So the main thing to focus on is why we don't see all the data prior to the restart
> the above repro's this for only 100 rows, if you increase the sleep to like 10 secs the data is all there, there seems to be some delay between the files being saved and the nodes being made aware of them
> I cannot repro this for memory/disk stores, might be s3 specific

This ten second delay in things being available is actually somewhat to be expected with the current approach of file watching. This is likely the same for _all_ of the remote object stores, as they all work the same way:
- We setup a local filename cache, initializing it using a list objects operation on the bucket.
- We listen for changes on the bucket and add/remove filenames from the filename cache:
  - Buckets/containers are set up such that they send notifications/messages on put/deletes.
  - We use whichever appropriate event bus/queue for the service (in AWS case, SNS & SQS queues), and setup a queue for messages.
  - Whenever a message is received and processed from that queue, we add it to the local file name cache.

As such - this is _not_ an instantaneous process. There is a delay between a file being written to the object store, and XTDB being aware that the file exists. The various file_watch implementations could likely be tuned to reduce that latency, but it will continue to exist (and similarly be somewhat out of our hands - especially if we are waiting on the message/notification to be sent in the first place).

That being said - we need to likely consider our approach, here:
> ..I believe the desired behaviour is an XT node (as a java object) provides immediate read-after-write

As a note - It may be possible for us to update our file list locally - for the particular node that we have in memory/in process to immediately take note of any files that it has written and add them to the file cache. This would not allow you to immediately have files made by other nodes, but you could be somewhat sure that you have all files that the node you have to hand has written/removed. Not sure how useful that necessarily is in this case, but worth a think. (If we took such an approach - we'd need to be somewhat cautious of things then getting removed/re-added at a later point by the same operations later being handled from the remote notifications).
