### ISSUE TITLE
Allocator `buffer` not setting the capacity correctly

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2803]
This was just something I came across with @wotbrew while fiddling around with the allocators. Not something that has high priority. Either the Arrow docstring on `BufferAllocator` needs to get updated or it's a bug in Arrow. 
```clj
(with-open [allocator (RootAllocator.)
            buf (.buffer allocator 9946)]
    (prn (.capacity buf))
    (.capacity buf 9946)
    (prn (.capacity buf)))
```
the output is 
```
16384
9946
```
without setting the capacity explicitly the allocator overallocates memory and also seems to set the capacity of the buffer to that. That is contrary to the docstring:
```
Note that the buffer may technically be larger than the requested size for rounding purposes. However, the buffer's capacity will be set to the configured size.
```

**Comment by jarohen** [comment]
Can this one be confirmed and raised with Arrow instead?

**Comment by FiV0** [comment]
Raised upstream https://github.com/apache/arrow-java/issues/141
