### ISSUE TITLE
Errors thrown lazily in tx-fns shouldn't stop ingestion

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2811]
(cc @malcolmsparks)

Repro:
* put tx-fn similar to `(fn [ns] (for [n ns] (throw (ex-info "boom" {}))))`
* call it - this stops ingestion

**Comment by FiV0** [comment]
Fixed in [c08e6d3f](https://github.com/xtdb/xtdb/commit/c08e6d3fc263d06e9205258d3082f5ba96f84a44)
