### ISSUE TITLE
.putObject does not support large files very well

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2814]
We have not yet decided exactly how large files should be allowed to become - we are doing some work to make sure we can better estimate file sizes here: #2816. 

Should we decide to store large files (1GB+) it might be worth solving problems related to memory usage and network timeouts.

There are two main sources of .putObject calls, L0 writes as when flushing a chunk during indexing - and compaction which generates L1+ files. 

We should be less concerned (I think) about L0 writes as they will likely be bounded by a limit described here #2816, which per-table is unlikely to cause significant memory or timeout issues.

## Memory

.putObject currently takes a nio ByteBuffer. This assumes that either we have the whole object in memory or memory mapped. If we are not memory mapping this may cause larger buffers to exhaust available memory, or put undue pressure on memory-starved queries.

Compaction currently writes to ByteArrayOutputStreams whose arrays are then realised as heap ByteBuffers to be sent to storage via .putObject, this requires at best the whole object to be realised in heap or 2X the memory to be allocated due to the copy semantics of .toArray on ByteArrayOutputStream. 

We could choose to:

- Require a memory mapped buffer, or have it be our accepted way of writing large files
  - requires writing the whole buffer up front, memory map or not
  - upload can be partitioned and sent in parts in parallel if using multipart
  - sdk should be able to work on mapped memory directly and avoid copies (this assumption needs testing)
  - multipart not strictly necessary if timeouts policy can be gotten right
  - implies a file when memory map is used

- Require a file e.g putFile rather than putObject
  - requires writing the whole file up front 
  - requires disk space
  - might not need multipart
  - cloudsdk can normally work with file handles directly requires us to write very little of our own code
  - latencies involved will make file open/close and even copy potentially not that important for small buffers
  - would still need to look at timeout policies and test timeouts do not need scaling the size of the file 
  - may provide fewer opportunities to tune parallelism
  - may need to remember to clean up temp files

- Expose an OutputStream or nio.WritableByteChannel 
  - pipelining and limited parallelism possible 
  - do not need to realise whole stream up front 
  - might be relatively more sophisticated, probably requires multipart

## Timeouts

With larger files, it seems possible to get S3 timeout exceptions depending on network speed. To reproduce, use a slow connection and/or `:put` large rows to cause file sizes to increase.

.putObject protocol does not explicitly define timeout policy, but if you have a 200MB ByteBuffer to put - given a timeout a caller has few options to resolve themselves.

Should file sizes become so large as to cause these timeouts the node may stop indexing writes and remain in a degraded state. 

Some early ideas (not exhaustive)
- print a handy error message on timeout suggesting the configuration variable to change the timeout
- limit file sizes and set a reasonable policy for the cloud (that can perhaps be overridden if testing using some low quality connection)
  - problem: file sizes are often determined by row-count rather than bytes, bytes per row will depend. 
- use an equation to determine a reasonable timeout given the size of the buffer, like the others hard to get right as network speeds may differ but we might find a reasonable number for 99% of cases
- use multi-part uploads, the timeout policy can be defined in terms of each part having a fixed size

### Multipart uploads - Dan M Update 

As part of the above, we've added a **SupportsMultipart** optional interface that remote object stores can support to create and upload multiparts. Subtasks below: 

Subtasks:
- [x] https://github.com/xtdb/xtdb/issues/2823 - multipart uploads on the S3 object store.
- [x] https://github.com/xtdb/xtdb/issues/2824 - multipart uploads on the Google cloud object store.
  - Decided against doing this for now - see comment on issue. 
- [x] - multipart/block uploads on Azure

### ArrowFileWriter integration 

- [] Implement and test writer abstraction for minimizing memory usage, timeouts when writing large files
- [] Test on EFS (FS atomics support lacking)
- [] Integrate with compactor 
- [] Integrate with indexer

**Comment by danmason** [comment]
At a quick glance, seems like each cloud provider we're currently supporting has some way of uploading chunks of large files in parallel:

- For S3, this is multipart uploads: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html
- Google cloud also has some concept multipart uploads: https://cloud.google.com/storage/docs/multipart-uploads
- Azure has "block blobs": https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs

(Would have to look into how the APIs for all of these are)

**Comment by danmason** [comment]
Based on the above, I've added a couple of smaller tasks for supporting multipart uploads. I'm not necessarily sure if they would immediately resolve this ticket on their completion, but we can consider their impact.

Tickets added:

- #2823 - multipart uploads on the S3 object store.
- #2824 - multipart uploads on the Google cloud object store.

I was going to also add one around using block blobs in Azure, but noticed this from the docs above:

> Storage clients default to a 128 MiB maximum single blob upload, settable in the Azure Storage client library for .NET version 11 by using the [SingleBlobUploadThresholdInBytes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions.singleblobuploadthresholdinbytes) property of the [BlobRequestOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions) object. When a block blob upload is larger than the value in this property, storage clients break the file into blocks.

Based on that - it sounds like the default behaviour already implemented by our usage of their storage library is that these uploads should already be being split into 128MB blocks. Obviously will want to investigate this further and try to verify that is the case, but decided to not create a ticket for it yet.

**Comment by jarohen** [comment]
* Design a multipart API for the object store to implement (in terms of ByteBuffers)
* S3/GCS to buffer to minimum part size limits
* object-store to track uploaded parts so that when the caller calls complete it can pass the required data to the API call

wider plan:
* land this one in isolation
* how do we wire it in?
  * option A: wait til we do the buffer-pool write-through
  * option B: wire up an ArrowFileWriter API on the buffer-pool which passes straight through for now
    * stage 1: passes straight through, ignores its own cache
    * stage 2: writes the file to disk as it goes. when it's complete it places the whole file in the cache (no need to change current caching behaviour)
    * stage 3: if we do decide that the buffer pool caches at the record batch level, we already have the boundaries available here.

**Comment by danmason** [comment]
## Implementing multipart for other libraries

### Google Cloud

While GCS supports multiparts with similar semantics to S3, it currently only supports it via it's [XML API.](https://cloud.google.com/storage/docs/multipart-uploads)

The google cloud storage Java client library **doesn't** support multipart uploads in any way. If we wanted to do it via Java, it seems that we would have to use the [S3 client library](https://stackoverflow.com/questions/71437653/perform-multipart-upload-in-gcs-in-java).

I suppose our options here are to either:
- Transform the whole google cloud implementation to use the S3 client, including this.
- Dip into the S3 client specifically for the multipart uploads.
- Leave everything as is, communicate with the XML api directly over HTTP. 

### Azure
For Azure - there is the BlockBlobClient, the process of uploading in parts/blocks (from [**here**](https://github.com/Azure/azure-storage-php/issues/170#issuecomment-458385176))
 
> For Azure Storage, there are 2 steps:
> - Do not need to initialize a multipart uploading
> - Upload block (like S3's part) to a blockblob with the blockID
> - Commit the blocklist to save the blockblob with the blockIDs

Looking at the Java API, we create a `BlockBlobClient`, can call to `upload`, which will upload an individual block, or 'part', and then when we finish/complete a block we commit the list of blocks. Seems pretty analogous to what we have - I think entirely possible to treat it the same. (Initializing becomes 'create the block blob client for the given blob')

Seems like we stage a block? https://stackoverflow.com/questions/66364156/how-to-upload-multiple-chunks-of-a-single-video-file-in-azure-blob-storage-using
