### ISSUE TITLE
xtdb slow startup

### ISSUE THREAD

**Issue by vinayus** [xtdb/crux#2856]
i have deployed xtdb pod as a statefulset application with a volume mount to /var/lib/xtdb.

when the pod is restarted the startup time is very long(hours). is there a way i can tune(like lazy load or bulk load in background) or improve this time?

current size of volume stands in range of 1-5GB but with intention of growing this to around 30-50GB

here are my configs and version currently i'm using is 1.23.0

xtdb.edn within the image is below
```
{:xtdb/index-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/indexes"}}
 :xtdb/document-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/documents"}}
 :xtdb/tx-log {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/tx-log"}}
 :xtdb.lucene/lucene-store {}
 :xtdb.calcite/server {}
 :xtdb.http-server/server {}}

```

logs at startup are
```
WARNING: Implicit use of clojure.main with options is deprecated, use -M
11:19:21.185 [main] INFO  xtdb.cli - XTDB version: null revision: null
11:19:30.021 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @30311ms to org.eclipse.jetty.util.log.Slf4jLog   
11:19:34.768 [main] INFO  xtdb.tx - Started tx-ingester 

```
is there any configuration I can add or any link to documentation that i can use?

**Comment by refset** [comment]
Hey @vinayus it looks like your Lucene module is not configured to use disk storage, so the node will be rebuild in-memory lucene indexes every time the it restarts (via a full log replay). I expect you simply need to add `:db-dir "/var/lib/xtdb/lucene"` to the currently empty config map `:xtdb.lucene/lucene-store {}`.

See also https://v1-docs.xtdb.com/extensions/full-text-search/#_setup

Hopefully that solves it for you, but if not then please do feel free to re-open the issue :slightly_smiling_face:

**Comment by vinayus** [comment]
my bad should've explored more. thanks this helps, it took couple of minutes to read and later restarts were faster

below was the change to xtdb.edn as suggested by you

```
{:xtdb/index-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/indexes"}}
 :xtdb/document-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/documents"}}
 :xtdb/tx-log {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store, :db-dir "/var/lib/xtdb/tx-log"}}
 :xtdb.lucene/lucene-store {:db-dir "/var/lib/xtdb/lucene"}
 :xtdb.calcite/server {}
 :xtdb.http-server/server {}}


```
