### ISSUE TITLE
Users can evaluate XT2 using a standalone Docker image

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2888]
To consider:
* [x] How do we get users to configure it? The existing XT1 images, for comparison, have the user submit an `xtdb.edn` configuration file, but this likely isn't suitable for non-Clojure users. potential options:
  * YAML/JSON file instead?
  * if we split the Docker images up (into standalone/AWS/etc), how many things does a user then need to configure? i.e. would they reasonably fit into env vars?
  * let's check current Best Practices™ for how to configure these things - it may be that specifying loads of env vars is actually fine because, in practice, they're all submitted in a CloudFormation template, for example.
  * that said, I'd prefer we didn't have to either artificially flatten the config (structured trees ftw) nor maintain two sets of configuration params
* [x] Build/deploy through CI
* [x] Documentation

## Thoughts on custom configuration

At the bare minimum, the docker image should be able to run without any user provided configuration. Ie - some default config file should be pulled in when creating the image. It should use the following:
- Local Buffer Pool
- Local Directory Log

We can likely make use of Docker's ability to map single files through as volumes as a method to replace/pass in custom configuration files. As a starter, this could be entirely around replacing a `.edn` file, though we will have to consider other methods of config for non-clojure users (JSON, YAML). 

In order to do so - the CLI client will need to support non-edn configuration files. 

We'll also need to ensure that the built docker image has _all_ of the XTDB dependencies - such that it can run any module config without throwing dependency errors.

**Comment by danmason** [comment]
Current plans for configuration of these images:
- We'll create relevant docker images as and when which will have some config pre-written with env vars, and tell users which environment variables they'll need to set for each image.
- Users can mount configuration files with standalone if they wish, but we could also add a folder under the directory for building your own docker image (along the lines of xtdb-builder), and write some docs on using that.
