### ISSUE TITLE
Deployed documentation for the XT2 HTTP API

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2891]
* OpenAPI, available through any XT HTTP server (is there a 'well-known' path for these?)
* Generated, deployed with, and linked from the documentation site

## Plan (Dan M):

Current plan here for serving this:

- We have some `openapi.json` file we serve from the HTTP server.
  - This lives under the `resources` directory in the http-server.
  - We serve this file from an appropriate route on the server.
- We edit this file manually with any changes - treating it as a proper OpenAPI spec.
  - Can include whatever examples we want here.
- We have a symbolic link from the `docs` directory to this file.
- We serve a documentation site for the `openapi.json` file using Amplify:
  - We extend the yarn setup to have a script to create a static documentation page.
    - Can use a number of tools for this - have prior used `redoc-cli` for this.
    - We return the generated page as part of the `dist` directory (ie, the docs directory)
  - We run the above script as part of the amplify build - as the file is included in `dist` directory it should be deployed.

**Comment by danmason** [comment]
As discussed - the pipeline to update thsi & deploy this via docs-live onto the docs site is now available, even if the contents are not finalized. Shall close this - will likely need separate ticket for contents (as and when appropriate)
