### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by Sleepful** [xtdb/crux#2942]
I probably configured something wrong, but uh, I couldn't find how to fix this... Whenever I start a REPL, I get:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Looks like the project might be missing a dependency on my machine, but I dunno.

I am following the guides for JDBC config:

```clj
(def JDBC-log {:xtdb/module 'xtdb.jdbc/->tx-log
               :connection-pool :xtdb.jdbc/connection-pool
               :poll-sleep-duration (Duration/ofSeconds 1)})

(def JDBC-doc {:xtdb/module 'xtdb.jdbc/->document-store
               :connection-pool :xtdb.jdbc/connection-pool})

(def JDBC-pool {:dialect {:xtdb/module 'xtdb.jdbc.psql/->dialect}
                :pool-opts {}
                :db-spec {:jdbcUrl url}})

(defn start-xtdb! []
  (letfn [(kv-store [dir]
            {:kv-store {:xtdb/module 'xtdb.rocksdb/->kv-store
                        :db-dir (io/file dir)
                        :sync? true}})]
    (xt/start-node
     {:xtdb.jdbc/connection-pool JDBC-pool
      :xtdb/tx-log JDBC-log
      :xtdb/document-store JDBC-doc
      :xtdb/index-store (kv-store "data/dev/index-store")})))
```

**Comment by Sleepful** [comment]
looking at http://www.slf4j.org/codes.html#StaticLoggerBinder  looks like this is not an error, just a warning. 

Seems like this is telling me that it found “no logging backend”, and so I have the option to add one. I tried to search xtdb docs for info about this, but it seems there's none, maybe I am expected to know this tool? 

The page above says that the warning can be removed by adding `slf4j-nop.jar` to the classpath, I am not sure if it expects me to add an empty file or an actual `.jar`, eh.

**Comment by Sleepful** [comment]
Adding a dependency that handles `slf4j` like

[AvisoNovate/logging](https://github.com/AvisoNovate/logging)

```
[io.aviso/logging "1.0"]
```
seems to work well enough for now.

Looks like there's multiple projects of `slf4j` backends in clojars: https://clojars.org/search?q=slf4j

I have zero knowledge of `slf4j` so I will just try one.

Not sure what's the impact if I don't add any.

**Comment by Sleepful** [comment]
logs are kind of crazy:

```
19:36:46.227 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.333 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.440 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.544 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.647 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.749 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.856 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:46.961 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@16007f10
19:36:47.064 [xtdb-tx-subscription-1] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.j
```

it goes like ad nauseam, is there a way to limit the logging from xtdb?

I tried using these params https://v1-docs.xtdb.com/administration/monitoring/#console but I could not reduce the logging

**Comment by jarohen** [comment]
Hey @Sleepful :wave: 

There's instructions on how to set up logging [here](https://v1-docs.xtdb.com/guides/in-a-box/#_1_install_dependencies) - give me a shout if you have any questions :slightly_smiling_face: 

Unless you have specific preferences, I find that using 'INFO' across the board is a reasonable default.

James

**Comment by Sleepful** [comment]
@jarohen oh yeah this is working wonders, now I can finally see error messages for Transaction Functions 😄 
Thanks! The note was a little bit hidden in the docs, but now people can find the link here in GH issues.
