### ISSUE TITLE
Java API support

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3043]
This ticket tracks work for moving the user specified data in the system from Clojure to Java.
- [x] parse clojure maps to corresponding JAVA api objects and update the places in `impl.node` and downwards accordingly. Probably some layer between node and xtdb.api. An example being `xtdb.query.Basis`.
- [x] instead of putting Clojure maps on the transaction log put Java maps with `Map<String, Object>` 
- [x] there are potentially also some changes to how we write documents

**Comment by jarohen** [comment]
We're in a better place with this now - will close this card and create subsequent cards for future work.
