### ISSUE TITLE
Support params in table temporal filters

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3068]
Both XTQL and SQL have support for params, support for these should be extended to the temporal filters around each languages FROM clause.

* [x] XTQL  `(from ... :for-valid-time $param})`
* [x] SQL `FROM ... FOR SYSTEM_TIME AS OF ?`
* [x] LP  (`scan/->temporal-bounds` already takes in params, which is where temporal filters are converted to scan constraints, so support for params may already exist in the logical plan.

**Comment by danmason** [comment]
We've added some tests around this in #3231 but seems like we're already supporting this in both XTQL and SQL.
