### ISSUE TITLE
Consider `FOR SYSTEM_TIME ALL` for alignment with SQL Server

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3072]
see https://discuss.xtdb.com/t/v2-sql-for-all-system-time-or-for-system-time-all/323

* `FOR SYSTEM_TIME ALL`
* `FOR VALID_TIME ALL`

**Comment by seancorfield** [comment]
Any further movement or thought on this?

**Comment by jarohen** [comment]
Hey @seancorfield - apologies, this slipped off the radar. Will pick it up, should be a quick one :crossed_fingers:

**Comment by jarohen** [comment]
Sorted - snapshot/Docker image on their way :rocket:

**Comment by seancorfield** [comment]
Much appreciated. Will close out my HoneySQL issue.
