### ISSUE TITLE
ECS stuck in `CREATE_IN_PROGRESS`

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3082]
see https://discuss.xtdb.com/t/v2-aws-cloudformation-template-problem/329

> I worked through [Getting started with XTDB on AWS | XTDB](https://docs.xtdb.com/guides/starting-with-aws.html) and ran into a problem:
> 
> I’ve built the cluster completely twice now and both times have gone fine until the last step: setting up the ECS piece mostly works but the ECSService never seems to complete (the other 10 resources get created just fine).
> 
> MSK took about 30 minutes, as expected in the notes.
> 
> The ECSService never completes. It says `CREATE_IN_PROGRESS` for about two hours and then rolls back the entire ECS stack. All the other pieces worked fine.

cc @seancorfield

**Comment by seancorfield** [comment]
I answered all of @danmason questions on the forum -- where do you want to continue discussion/debugging? On the forum or in this GH issue?

**Comment by jarohen** [comment]
Cheers @seancorfield + @danmason  - shall we continue on the discuss forum til we have a repro?

**Comment by danmason** [comment]
:wave: I've posted another [response](https://discuss.xtdb.com/t/v2-aws-cloudformation-template-problem/329/6?u=danmason) into discuss for now - not had so much luck on a repro. I'll aim to keep this issue updated as we go.

**Comment by danmason** [comment]
Going to close this for now - given that the current issue seems to be [resolved](https://discuss.xtdb.com/t/v2-aws-cloudformation-template-problem/329/8) and I couldn't seem to reproduce it. If we see anything similar in the future, can reopen this.

**Comment by seancorfield** [comment]
Thanks for the detailed questions and debugging steps along the way. I still have no idea what was different on that last attempt: I did multiple tear downs and stand ups along the way and previous complete rebuilds always hung up at that ECSService issue -- and the last one "just worked", with the updated ECS template. Even with the templates, it's still a lot of manual data entry and button clicking 😄
