### ISSUE TITLE
`<datetime> - <datetime>` to return interval rather than duration.

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3124]
SQL spec §6.33, general rule 7 (p316)

* returns year-month Arrow interval if years, months or year to month specified
* returns month-day-nano otherwise.
* interval qualifier to be a compile-time constant (see implementation note in #3084)

**Comment by danmason** [comment]
Just some updates from my understanding 
- From the SQL EBNF, I see we also expect an `interval qualifier` to be passed through - ie, subtracting two datetime should look like this: `(DATETIME_1 - DATETIME_2) DAY`.
- We can use that interval qualifier to decide which interval type we want to return - as mentioned in the description above, `year-month` or `month-day-nano`.
- We calculate the difference between the two datetime values, convert to a PeriodDuration and then round/truncate using the specified interval_qualifier.

**Comment by danmason** [comment]
After some time thinking & talking about it - decided the approach with interval qualifier is fairly hard to understand, especially in a lot of the edgecases, and passing around Years/Months here complicates matters. To that end, we've decided on the following (which I make extra tickets and link below):
- Leaving `timestamp - timestamp` as returning a duration (ie, closing this ticket) 
  - Given that this is true and this will remain unused, can remove `(timestamp - timestamp) Interval Qualifier` from the EBNF 
- Add casting between duration <--> interval #3196 
  - Interval here to be in terms of days + duration, where a day is considered to have 24 hours.
- Change `date - date` to return an integer - number of days elapsed between dates, #3197 

As an extra follow on/nice-to-have:
- Implement the [`age(l, r)`](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE) function from postgres #3198
