### ISSUE TITLE
Node doesn't stop cleanly after NodeJS `fetch` query request

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3142]
* Start Docker image: `docker run -ti --rm --name xt2 -p 3000:3000 ghcr.io/xtdb/xtdb-standalone-ea` (my commit hash `a526ccc`)
* `node`:
  ```javascript
  await fetch('http://localhost:3000/query', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: {"from": "visits"},
      queryOpts: {}
    })
  })
  ```
  returns 200
* Ctrl-C docker: 'WARN  xtdb.cli | could not stop node cleanly after 10000 ms, forcing exit'

Can't repro with cURL (`curl http://localhost:3000/query -XPOST -d '{"query": {"from": "visits"}, "queryOpts": {}}' -i -H 'content-type: application/json'`), haven't tried taking Docker out of the loop

**Comment by FiV0** [comment]
You were asking for `application/json`. I have chosen to always reply with `application/jsonl`, regardless of being asked for `application/json` or `application/jsonl`.

The following should work now (commit incoming):
```js
async function getData() {
  const response = await fetch('http://localhost:3000/query', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: {"from": "visits", "bind": ["foo"]},
      queryOpts: {}
    })
  });
  const headers = response.headers;
  console.log('Response Headers:');
  headers.forEach((value, name) => {
    console.log(`${name}: ${value}`);
  });
  console.log('Status:' + response.status);
  response.text().then(text => console.log(text))
}

getData()
```

**Comment by FiV0** [comment]
Closed in https://github.com/xtdb/xtdb/commit/7c5fa53b018f11699633dac01791f5f9052bbd7a.

**Comment by FiV0** [comment]
When running a query we are trying to encode a `Stream` as the result. In the case of `application/json` it was trying to encode the `Stream` with the standard encoder and the `Stream` didn't get closed. The query then didn't get closed and hence the issue when closing the node. You are not hitting the issue the curl request as that still returns transit without an explicit `accept` header.
