### ISSUE TITLE
Remove usage of removed Clojure private var

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3169]
(reported in https://clojurians.slack.com/archives/CG3AM2F7V/p1707605155431599?thread_ts=1707605155.431599&cid=CG3AM2F7V)

Use of `instant/thread-local-utc-date-format`, which was removed in alpha6:

https://github.com/xtdb/xtdb/blob/master/core/src/xtdb/io.clj#L56

**Comment by lispyclouds** [comment]
Hello! Is there a plan to get this one released? I think this is the only issue that's blocking me for an upgrade to Clojure 1.12. I'm happy to take a stab at it too, if I could be pointed to what could solve this! Thanks a lot for making this!

**Comment by lispyclouds** [comment]
Thank you! @jarohen

**Comment by jarohen** [comment]
Hey @lispyclouds, thanks for the poke 🙂
