### ISSUE TITLE
start-node with local file log may fail silently

### ISSUE THREAD

**Issue by aiba** [xtdb/crux#3178]
I was playing with xtdb 2.0, and I built an app that does this upon startup:

```
(xtn/start-node
     {:log         [:local {:path "/tmp/xtdb/log"}]
      :storage     [:local {:path "/tmp/xtdb/storage"}])
```

And was gettign a weird behavior where my log was not being persisted to disk.

I poked around the xtdb code and I think there may be a race condition where if the namespace `xtdb.log.local-directory-log` is not loaded, then the `(defmethod xtn/apply-config! :xtdb.log/local-directory-log ...)` may not have been evaluated, and thus the node doesn't know anything about the local log.

When I explicitly added `(require 'xtdb.log.local-directory-log)`, it fixed the problem.

This is a pretty bad experience for new users because the log configuration is just silently ignored and data is not persisted.

I'm also not sure if the `:storage` configuration key is going into effect.  It doesn't seem to be creating any data files under the storage path, but I'm not sure if that is expected or not.

**Comment by jarohen** [comment]
Hey @aiba, thanks for the report 🙏

We'll take a look into it, and please do let us know if you have any other issues/questions with the early access 🙂

James

**Comment by aiba** [comment]
Regarding whether local-storage is working, I have since observed that if I add enough data, it does indeed eventually write files to local-storage, which gives me confidence that the configuration is working.  Unlike the log file storage, and unlike with xtdb 1.x, it seems that xtdb2 local storage does not write any files until some amount of data has been submitted to the logs.  I would suggest it might be nice to write some kind of file to disk immediately upon starting the node, even just an empty sentinal file, to make it clear to the user that the :storage has been configured as the user intended.

**Comment by FiV0** [comment]
Hey @aiba, 

Regarding strorage: We are currently only creating the first storage files when `102400` (this number might change) rows have been transacted, hence why you are only seeing data at the storage location after you have added enough data.

Regarding log: I am unable to reproduce this on the head of our developping branch, but agree that there is an issue with the persistance of the log with the latest `2.0.0-SNAPSHOT` release. There has been a lot of shuffling of namespace since then. So I will retest with our next release and ping the thread in that case.

**Comment by aiba** [comment]
Cool, thanks.  I'm curious what your strategy is in general for ensuring defmethods get evaluated before they are needed.  I end up running into this in my own clojure projects a lot:

- Namespace a has a defmulti
- Namespace b depends on namespace a and has a defmethod for some key.
- Namespace c depends on a (but not b), calls the defmulti before namespace b has been required yet.

Just curious if you have a better system for this.

**Comment by jarohen** [comment]
Hey @aiba - finally managed to repro this, snapshot and Docker image with the fix just going live :rocket: 

> Cool, thanks. I'm curious what your strategy is in general for ensuring defmethods get evaluated before they are needed.

For us, in the majority of cases the namespace with the defmethods is naturally required by something else which is then required by the main entry point namespace - it's not fool-proof (as you can see!) but Just Works™ most of the time.

The other strategy we use is inspired by [Integrant](https://github.com/weavejester/integrant) (specifically `ig/load-namespaces`) which spots namespaced keywords in a config map and requires those namespaces as needed. Again, not a one-size-fits-all, but we use it often enough that it's become a pattern for us to draw on if need be :slightly_smiling_face: 

HTH - and, as always, thanks for letting us know about the issue!

James
