### ISSUE TITLE
SQL VALID/SYSTEM_TIME Period Name

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#3180]
Currently in SQL the name of the built in temporal periods is "VALID_TIME" and "SYSTEM_TIME".

However we might consider changing this to `xt$valid_time`

Some considerations:

- underlying columns are xt$valid_from/to

- xtql has a first class column with the name xt$valid_time

- period specs (table level filters) must use VALID_TIME according to SQL spec

- technically periods cannot be projected out in SQL/passed around like any other column, however our execution engine can support this and xtql allows it. In that case we'd need a real column name, and the projected struct for a period contains the keys xt$from/to

- in non-XT SQL:2011 the user specifies the name of the application time period in the DDL, and then uses the same name in both period references and period specs.

We could consider supporting both naming schemes as a compromise.

**Comment by jarohen** [comment]
done as part of #3619
