### ISSUE TITLE
Add support for nested parenthesized joined tables

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#3185]
SQL allows for parenthesized_joined_tables, within table primaries.

`SELECT * FROM ( foo LEFT JOIN bar ON true )`

Which we currently support.

Its also possible to nest these 

`SELECT * FROM ( foo JOIN (bar JOIN baz ON true) ON true)`

However the SQL planner isn't currently able to plan these. 

Some investigation perhaps required on how parenthesised joined tables differ semantically (if at all) from regular qualified joins (Join order?).

**Comment by danmason** [comment]
Wrote up the following test:
```clojure

(deftest nested-parenthesized-joined-tables-3185
  (xt/execute-tx tu/*node* [[:put-docs :foo {:xt/id 1 :x 1}]
                            [:put-docs :bar {:xt/id 1 :y 1}]
                            [:put-docs :baz {:xt/id 1 :z 1}]])
  
  (t/is (= [{:x 1, :y 1}]
           (xt/q tu/*node* "SELECT * EXCLUDE xt$id FROM ( foo LEFT JOIN bar ON true )")))
  
  (t/is (= [{:x 1, :y 1, :z 1}]
           (xt/q tu/*node* "SELECT * EXCLUDE xt$id FROM ( foo JOIN (bar JOIN baz ON true) ON true )"))))
```

Which now seems to pass just fine, so thinking to push that to main and close this :)

(Needing to explicitly exclude xt$id due to duplicate cols)
