### ISSUE TITLE
`generate_series` function

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3212]
See Postgres ['set-returning functions'](https://www.postgresql.org/docs/current/functions-srf.html).

This may need to be an operator (similar to `rel`) rather than an EE function.

**Comment by egg-juxt** [comment]
### SQL Tooling

`generate_series` is used by DBeaver at connection time:

```
SELECT pg_type.oid, typname
FROM pg_catalog.pg_type   
LEFT   JOIN (
	select ns.oid as nspoid, ns.nspname, r.r           
	from pg_namespace as ns           
	join (
	select s.r, (
		current_schemas(false))[s.r] as nspname
		from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) 
	) as r          
	using (nspname)) as sp     
ON sp.nspoid = typnamespace  WHERE typname = $1  ORDER BY sp.r, pg_type.oid DESC LIMIT 1
```

**Comment by refset** [comment]
Noting that our implementation for the expression diverges from Postgres where `SELECT GENERATE_SERIES(0,5)` in Postgres will return multiple rows (i.e. the same as `SELECT * FROM GENERATE_SERIES(0,5)`), whereas XT returns a single row with an ARRAY column.
