### ISSUE TITLE
Rudimentary support for Postgres table access control functions

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3216]
Metabase (see #3093) makes a [query](https://github.com/metabase/metabase/blob/1ea996899716252675644f8f1e1bb0c09399e115/src/metabase/driver/postgres.clj#L863-L866) at startup that calls two table access control functions: `pg_catalog.has_table_privileges` and `pg_catalog.has_schema_privileges`.

* Before we have finer-grained access control, we should return that the current user has full read/write access to all schemas/tables/views
* This may involve changes to the SQL grammar/parser. TBC: 
  * what is this syntax implying? i.e. can functions be scoped to a schema, or is `pg_catalog` a receiver?
  * is it SQL-spec compliant?

**Comment by danmason** [comment]
Re-opening this as we take a look at moving over to using `<method invocation>`.

**Comment by danmason** [comment]
Considering this done and not updating to use routine invocation - see comment on #3267.
