### ISSUE TITLE
`:rows-as` query option to the APIs

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3256]
depends on #3255

`:rows-as` being either `:maps` or `:tuples`, default `:maps`.

* [ ] in-process APIs
* [ ] HTTP
* [ ] JS SDK

N.B.

* no header row required
* `:tuples` not valid for XTQL queries

Consideration required about the Java return type - let's discuss how to make this work with generics.

**Comment by malcolmsparks** [comment]
Sorry for not commenting earlier, see https://github.com/xtdb/xtdb/issues/3237#issuecomment-2020220936
