### ISSUE TITLE
Support for LocalDate and LocalTime

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3261]
Currently Clojure users might extend XT1 using Nippy's extension API to create a native-feeling experience when working with Java's LocalDate and LocalTime types:

```clojure
(nippy/extend-freeze LocalDate :codec/local-date [data data-output] (.writeLong data-output (.toEpochDay data)))
(nippy/extend-thaw :codec/local-date [data-input] (LocalDate/ofEpochDay (.readLong data-input)))
(nippy/extend-freeze LocalTime :codec/local-time [data data-output] (.writeLong data-output (.toNanoOfDay data)))
(nippy/extend-thaw :codec/local-time [data-input] (LocalTime/ofNanoOfDay (.readLong data-input)))
```

Native handling of these types could be generally useful, but it should include consideration for HTTP/transit also.

Alternatively we could consider exposing an extension point within the server module that could somehow combine with the above mechanism.

**Comment by jarohen** [comment]
Currently requires something defining print-dup for the java-time classes - can either do this with something like the 'time-literals' library, or by supplying `XTDB_ENABLE_JAVA_TIME_PRINT_METHODS`
