### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by shevchuk** [xtdb/crux#3274]
The page https://docs.xtdb.com/tutorials/immutability-walkthrough/part-2
Contains the sentence:

```
Now lets say our the CFO wants to how the prices have increased over Q1?
```

probably should be:
```
Now lets say our <strike>the</strike> CFO wants to *know* how the prices have increased over Q1?
```

**Comment by refset** [comment]
Hey @shevchuk thanks for the report :pray: `lets` probably needs an apostrophe too!

**Comment by Akeboshiwind** [comment]
Fixed in the above commits
