### ISSUE TITLE
Tech debt: migration to direct SQL planner

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3318]
We're struggling with making changes to the attribute-grammar oriented SQL planner, it takes a while to boot back up, and it's hard to explain how it works when anything can do anything to get the information it needs.

Proposal: replace with a more direct SQL planner.

* [x] `SELECT *`
* [x] `FROM FOR {VALID_TIME|SYSTEM_TIME}`
* [x] `JOIN`
* [x] `GROUP BY`
* [x] `ORDER BY`
* [x] `LIMIT`/`OFFSET`
* [x] exprs (excl. aggregates and subqs)
* [x] scalar subqs (incl. exists)
* [x] correlated subqs
* [x] quantified comparisons
* [x] CTEs
* [x] DML

To do:

- [x] duplicate columns handling:
  - [x] Leave it up to the user to specify in these cases - throwing "duplicate column" errors.
  - [x] Allow user to specify "RENAME" and "EXCLUDE" on Select Star
  - [x] Allow user to specify the above on qualified asterisk
- [x] Parser errors halt planning and throw in a nice format,
   - [x] Perhaps collect all syntax errors and return in a list 
- [x] outputting error records in user friendly manner
- [x] arrow-table
- [x] Support subqueries in DML statements
  - [x] Update
  - [x] Delete
  - [x] TODO: Verify implementations of both of the above.
  - [x] Erase 
  - [x] Should warn if trying to update table that doesn't exist/isnt found, plan it anyway.
- [x] Support subqueries inside of Join Conditions
- [x] schema UOE - migrate to basic identifier chain
- [x] `plan2` - verify UOEs, change some to warnings if appropriate.
- [x] array-agg sort-spec UOE
- [x] SLT direct SQL tests - big bag of errors to categorise
- [x] pgwire bugs
- [x] sql_test
  - [x] Fix any thrown errors - should be valid + planned out, at least. 
  - [x] Numerous updates needed to the expected plans, validating against those. 
- [x] TPC-H
- [x] lateral/unnest UOE
- [x] elsewhere (ie, test failures not covered in the above): 
  - [x] node-test 
  - [x] api-test
  - [x] xtql-walkthrough-test
  - [x] bench-automark-test
  - [x] tx-fn test - 1 test fail due to us not throwing an error for table out of scope. 
- Still need to run/figure out what test failures we have:
  - [x] Integration test? (Any SQL here?)
  - [x] Nightly test? (Probably no impact from SQL here?)
  - [ ] SLT suite

**Comment by danmason** [comment]
Currently a failing test on api-test - `test-sql-insert`:
- The failing query:
```sql
INSERT INTO people (xt$id, renamed_name, xt$valid_from)
SELECT users.xt$id, users.name, users.xt$valid_from
FROM users FOR VALID_TIME AS OF DATE '2019-06-01'
WHERE users.name = 'Dave'
```
- Fails at the point of indexing - inside of `project/->identity-projection-spec`:
  - Receives a `nil` field for one of the later/higher level `xt$id` values.
  - Need to figure out why - suspect could be responsible for failures elsewhere too.
- Suspect this is a bug related to `InsertFromSubquery` - simplified the insert and still see it fail: 
```sql
INSERT INTO people (xt$id, renamed_name)
SELECT users.xt$id, users.name
FROM users
WHERE users.name = 'Claire'
```

Update:
- Suspect the issue is related to `out-col-syms` - simplifying to this gets a working INSERT:
```sql
INSERT INTO people
SELECT users.xt$id, users.name
FROM users
WHERE users.name = 'Claire'
```

Culprit seems to be in visitQuerySpecification:
```
 (if out-col-syms
          (->QueryExpr [:rename (zipmap out-col-syms col-syms)
                         plan]
                        (into out-col-syms (filter (comp :extended-ob-col-ref meta)) col-syms))
```
Switching around the order of the zipmap, `(zipmap col-syms out-col-syms)`, fixes the issues.
