### ISSUE TITLE
Unqualified column in `UPDATE` `WHERE` clause doesn't error

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3322]
```clj
  (xt/submit-tx node [[:put-docs :foo {:xt/id 1 :bar "toto1"}]
                      [:put-docs :foo {:xt/id 2 :bar "toto2"}]])

  (xt/submit-tx node [[:sql "UPDATE foo SET bar = 'toto3' WHERE xt$id = 2"]])

  (xt/q node "SELECT * FROM foo")
  ;; => [{:bar "toto2", :xt/id 2} {:bar "toto1", :xt/id 1}]
  
  (xt/submit-tx node [[:sql "UPDATE foo SET bar = 'toto3' WHERE foo.xt$id = 2"]])

  (xt/q node "SELECT * FROM foo")
  ;; => [{:bar "toto3", :xt/id 2} {:bar "toto1", :xt/id 1}]
```
If the first is valid than it's unclear to me what it does.

**Comment by refset** [comment]
`xt$txs` probably shows it as not-committed.

The [Fiddle](https://fiddle.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGZvbyAoeHQkaWQsIGJhcikgVkFMVUVTICgxLCAndG90bzEnKTtcbklOU0VSVCBJTlRPIGZvbyAoeHQkaWQsIGJhcikgVkFMVUVTICgyLCAndG90bzInKTsifSx7InR4cyI6IlVQREFURSBmb28gU0VUIGJhciA9ICd0b3RvMycgV0hFUkUgeHQkaWQgPSAyOyIsInN5c3RlbS10aW1lIjpudWxsfV0%3D&query=U0VMRUNUIGZvby4qIEZST00gZm9vOw%3D%3D) version queries the `xt$txs` table automatically and surfaces the actual error:
```
Error: xtdb.IllegalArgumentException

Invalid SQL query:
  - XTDB requires fully-qualified columns: xt$id at line 1, column 36

Data:

{:errs ["XTDB requires fully-qualified columns: xt$id at line 1, column 36"], :xtdb.error/error-key "xtdb.sql/analyze-error"}
```

**Comment by refset** [comment]
Aside: the utility of `submit-tx` as an API is under consideration. Something more like `transact` would probably be more appropriate as the default user journey. I don't think there's an issue covering this yet though, so perhaps this can be it.

**Comment by jarohen** [comment]
re-check after #3383

**Comment by refset** [comment]
Looks [fixed](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGZvbyAoeHQkaWQsIGJhcikgVkFMVUVTICgxLCAndG90bzEnKTtcbklOU0VSVCBJTlRPIGZvbyAoeHQkaWQsIGJhcikgVkFMVUVTICgyLCAndG90bzInKTtcblVQREFURSBmb28gU0VUIGJhciA9ICd0b3RvMycgV0hFUkUgeHQkaWQgPSAyOyJ9XQ%3D%3D&query=U0VMRUNUIHh0JGlkLCBiYXIgRlJPTSBmb28%3D).
