### ISSUE TITLE
Improve error message with unqualified select * with other cols

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3385]
This raises the below error:
```sql
INSERT INTO docs (xt$id, foo) VALUES (1, 'bar'); -- pretend the `;` works
SELECT *, foo FROM docs
```

```
Error: xtdb.IllegalArgumentException

Errors parsing SQL statement:
  - line 1:8 mismatched input ',' expecting {<EOF>, ';'}

Data:

{:xtdb.error/error-key "xtdb/sql-error"}
```
[xt-play](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKHh0JGlkLCBmb28pIFZBTFVFUyAoMSwgJ2JhcicpIn1d&query=U0VMRUNUICosIGZvbyBGUk9NIGRvY3M%3D)

**Comment by refset** [comment]
Summarising a few observations:
1. This actually isn't standard SQL
2. However we probably should support eventually it as an explicit extension (per SQLite / Postgres which are setting common user expectations)
3. We previously had a circumflex character that would indicate the position of char '8' (we should re-instate this)
4. It says `expecting {<EOF>, ';'}` but surely `FROM` should be in that list? :thinking: 
5. Bonus: multi-statement tx support would mean the line number should be '2'

**Comment by xuelin-wang** [comment]
Following quick start documentation at https://docs.xtdb.com/quickstart/query-the-past.html
The following query throws error, similar to above. 
xtdb-> SELECT  *, _system_from, _system_to FROM people;
Errors parsing SQL statement:
  - line 1:9 mismatched input ',' expecting {<EOF>, ';'}
xtdb-> SELECT *, _system_from, _system_to FROM people FOR ALL SYSTEM_TIME;

**Comment by refset** [comment]
Ah, thanks for mentioning that @xuelin-wang - looks like it got broken during this change https://github.com/xtdb/xtdb/commit/9afdd077adb42dcc84e72bc36a4bfa14d3f2afb7#diff-3d824e12b8b93c58f1faf84e01e06efeaa76d80b814cef397dcc396c56a8ee4fL95-R95

There are a few similar instances: https://github.com/search?q=repo%3Axtdb%2Fxtdb%20%22SELECT%20*%2C%22&type=code

**Comment by jarohen** [comment]
Hey @Akeboshiwind, @xuelin-wang - went for the approach of 'allow this in our SQL compiler' instead :slightly_smiling_face: 

Will be included with our next snapshot release - thanks for the report :pray:
