### ISSUE TITLE
Fail INSERT map data structure

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3387]
This test fails:
```clojure
(t/deftest test-issue
  (xt/submit-tx tu/*node* [[:sql "INSERT INTO trades (xt$id, info) VALUES (1, {'price': 100})"]])
  (t/is (= [] (xt/q tu/*node* "SELECT * FROM xt$txs WHERE xt$error IS NOT NULL"))))
```

With this error:
```
Error: xtdb.IllegalArgumentException
Errors parsing SQL statement:
  - line 2:12 no viable alternative at input '(xt$id,info,xt$valid_from)VALUES(1,{'price''

Data:
{:xtdb.error/error-key "xtdb/sql-error"}
```

I found this error on the (live) [time in finance docs page](https://docs.xtdb.com/tutorials/financial-usecase/time-in-finance.html#4-complex-version-histories).

**Comment by jarohen** [comment]
As of #3318 keys in maps should no longer be surrounded with `'` - these, like top-level SQL column names, are included as raw symbols: `{price: 100}`

(i.e. this is a breaking change)
