### ISSUE TITLE
When submitted a query from python interactive terminal, got Encountered an unknown key 'query' at path: $

### ISSUE THREAD

**Issue by xuelin-wang** [xtdb/crux#3435]
Seel slack thread: https://clojurians.slack.com/archives/CG3AM2F7V/p1719163318155269

Details copied here:

Trying xtdbv2 following docker quick start and get json decode error. Did I miss some step(s)?
after
 docker run --pull=always -v ~/work/xtdb-prototype/xtdb-data:/var/lib/xtdb -tip 6543:3000 [ghcr.io/xtdb/xtdb-standalone-ea](http://ghcr.io/xtdb/xtdb-standalone-ea)
2. follow python interactive insert a people record and select from people. Got exception of below. Longer details in thread to avoid spamming top level.
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'query' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"query": {"sql": "SELECT * FROM people"}, "queryOpts": {"txTimeout": "PT1S", "keyFn": "SNAKE_CASE_STRING"}}

**Comment by refset** [comment]
Thanks again for reporting this @xuelin-wang - and apologies for the confusion! Now fixed via https://github.com/xtdb/xtdb/issues/3444

**Comment by xuelin-wang** [comment]
Thanks for the quick fix!!
