### ISSUE TITLE
SQL struct field lookup returns no data

### ISSUE THREAD

**Issue by xuelin-wang** [xtdb/crux#3436]
Following quick start with docker environment and python interactive sql example, at the step to query nested json data in info column of people table, shows no column returned:
SELECT people.info.contact[2].tel FROM people
  WHERE people.name = 'fred';
  
  In fact, this query shows the same thing:
  SELECT people.info.contact  FROM people
  WHERE people.name = 'fred';

**Comment by refset** [comment]
Hey @xuelin-wang thanks for reporting this one also - it looks we have a regression in our struct field access support.

This works ([Play](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsIFt7YmFyOiA5fV0pIn1d&query=U0VMRUNUIF9pZCwgZm9vWzFdLmJhciBGUk9NIGRvY3M%3D)):
```
INSERT INTO docs (_id, foo) VALUES (1, [{bar: 9}])
SELECT _id, foo[1].bar FROM docs
```

But without the array the nested lookup doesn't work ([Play](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsIHtiYXI6IDl9KSJ9XQ%3D%3D&query=U0VMRUNUIF9pZCwgZm9vLmJhciBGUk9NIGRvY3M%3D)):
```
INSERT INTO docs (_id, foo) VALUES (1, {bar: 9})
SELECT _id, foo.bar FROM docs
```

An existing test in this area is (which currently passes): https://github.com/xtdb/xtdb/blob/5e48c7fe549a7a8c245531a020f83bfb2e735533/src/test/resources/xtdb/sql/logic_test/direct-sql/sl-a5.test#L56

**Comment by refset** [comment]
@jarohen explained to me earlier that the "ISO standard approved" syntax for this is now `(foo).bar`, i.e. the parens are necesssary ([Play](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsIHtiYXI6IDl9KSJ9XQ%3D%3D&query=U0VMRUNUIF9pZCwgKGZvbykuYmFyIEZST00gZG9jcw%3D%3D)):

```SQL
INSERT INTO docs (_id, foo) VALUES (1, {bar: 9});
SELECT _id, (foo).bar FROM docs;
```

We will review whether making the previous syntax work still is viable and circle back here with thoughts.

I suspect nobody wants to have to type out `SELECT (((people).info).contact[2]).tel FROM people` :slightly_smiling_face:

**Comment by jarohen** [comment]
> I suspect nobody wants to have to type out `SELECT (((people).info).contact[2]).tel FROM people` 🙂

@refset thankfully you don't need to do that at every level - `SELECT (people).info.contact[2].tel FROM people` should be sufficient. It's just to differentiate between `schema.table.field`, `table.field.sub_field` and `field.sub_field.sub_sub_field` - so `schema.table.field`, `(table.field).sub_field` and `(field).sub_field.sub_sub_field` respectively.

(SQL:2011 §6.6 &lt;identifier chain&gt;, syntax rule 10, p210, for anyone keeping score. It's a pretty gnarly one, I'm not 100% convinced we've got it right, but the fact that Postgres mandates [something similar](https://www.postgresql.org/docs/current/rowtypes.html#ROWTYPES-ACCESSING) gives me some confidence, at least.)

**Comment by refset** [comment]
Ah okay, in which case the confirmed working solution for my above example is now ([Play](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsIHtiYXI6IHtiYXo6IDl9fSkifV0%3D&query=U0VMRUNUIF9pZCwgKGZvbykuYmFyLmJheiBGUk9NIGRvY3M%3D)):
```sql
INSERT INTO docs (_id, foo) VALUES (1, {bar: {baz: 9}});
SELECT _id, (foo).bar.baz FROM docs;
```

Glad to have that cleared up! I'll weave this change into the wider shake-up of the quickstart. Apologies @xuelin-wang for the noise and breaking change.
