### ISSUE TITLE
Null being returned as JSON in pgwire

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3443]
Currently: null values are being returned as `"null"`, which causes issues in JDBC.

consider:
* `<Null>` -> text column with SQL nulls (NULL in postgres do not poses they own type, postgres opts to return untyped nulls as type text. which pgjdbc handles).
* `Union<Int, Null>` -> int column with SQL nulls
* `Union<Int, Str, Null>` -> json column with SQL nulls

**Comment by refset** [comment]
Related (or different card?): _valid_to returns as a JSON string also (because nulls), but we want timestamps
