### ISSUE TITLE
Max long is truncated

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3470]
As seen [here](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDkyMjMzNzIwMzY4NTQ3NzU4MDcsICdiYXInKSJ9XQ%3D%3D&query=U0VMRUNUICogRlJPTSBkb2Nz):
```sql
INSERT INTO docs (_id, foo) VALUES (9223372036854775807, 'bar');

SELECT * FROM docs
```

Produces: `9223372036854776000`

**Comment by jarohen** [comment]
Check the network tab :wink: 

JavaScript can be a really f**king [_terrible_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) language sometimes.

**Comment by Akeboshiwind** [comment]
Haha, amazing find
