### ISSUE TITLE
SQL INSERTs that don't perform queries should have similar performance to `:put-docs`

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3484]
e.g. currently `put-docs` can be ~30x (or more) faster than performing batched INSERTs via pgwire, due to the costs of creating unused (unnecessary) watermarks

This will be essential as we switch to promoting pgwire as the main API for bulk loading. Or alternatively, as a workaround, we could invest energy in csv/jsonl/etc import, e.g. `copy my_data from 'my_data.jsonl';`

**Comment by jarohen** [comment]
we now convert static SQL inserts into put-docs before they're submitted - e.g.:

`INSERT INTO foo (_id, v) VALUES (1, 2)` -> `[:put-docs :foo {:xt/id 1, :v 2}]` (roughly speaking)

* If there're multiple arg-rows provided (i.e. execute-batch), we can turn this into a single put-docs (assuming valid-from and valid-to are the same throughout)
* If there're multiple `VALUES` rows provided (e.g. `VALUES (?, ?), (?, ?)`), likewise.
