### ISSUE TITLE
Escaping single quotes inserts two single quotes

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3501]
[Given](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKVxuVkFMVUVTXG4oMSwgJ215IHN0cmluZyB3aXRoICcnc2luZ2xlIHF1b3RlcycnIGluIGl0JykifV0%3D&query=U0VMRUNUIF9pZCwgZm9vIEZST00gZG9jcw%3D%3D):
```sql
INSERT INTO docs (_id, foo)
VALUES
(1, 'my string with ''single quotes'' in it');

SELECT _id, foo FROM docs
```

You get: `"my string with ''single quotes'' in it"`
I expect: `"my string with 'single quotes' in it"`

**Comment by jarohen** [comment]
#3467
