### ISSUE TITLE
100% CPU consumption on empty log, until first tx is submitted

### ISSUE THREAD

**Issue by egg-juxt** [xtdb/crux#3509]
When starting up a new empty xtdb node, the record-reading loop in xtdb.log.NotifyingSubscriberHandler.subscribe consumes 100% CPU* until the first tx is submitted; then it calms down.

*I think due to it being a virtual thread, it gets dispatched to different actual threads, but you can still see a net consumption of ~12.5% in an 8-core CPU. But a JVM profiler points to that thread.

**Comment by refset** [comment]
Can confirm that this is seemingly happening also with the vanilla Docker image (today's latest snapshot). cc @jarohen
