### ISSUE TITLE
Multi node config running against Azure on AKS

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3530]
Want to add a multinode AKS config file and run the azure auctionmark benchmark against that:
- Will need to bump the node pool `vm_size` to support running multiple nodes.
- Should run a `kafka` service within there with persisted kakfa storage, to be used as the txLog by the cluster.
- Should run an `initContainer` responsible for the LoadPhase of the auctionmark benchmark
- Should:
  - Run 3 replicas of containers, each with a separate disk cache.
  - No loadphase on any of them.
  - All using same kafka.

**Comment by tggreene** [comment]
We're switching to AKS to make use of support for better disks which is being worked on [here](https://github.com/tggreene/xtdb/tree/azure-benchmark-latest).

**Comment by danmason** [comment]
Made some good progress on this - setup mostly complete:
- Bumepd vm size to `Standard_D8_v2`
- Split kubernetes into two node pools - one for system components and one for application components (as recommended by azure).
- Added kubernetes setup for a very basic Kafka setup.
- Added kubernetes setup for multi node run:
  - initContainer which waits for kafka to be ready & connectable.
  - initContainer which does the loadPhase on its own.
  - 3 containers running in parallel after the loadphase doing the OLTP auctionmark loop.

Updated all docs under the cloudbenchmark directory accordingly.

Currently seen a few interesting issues, documented most of these under #3537
