### ISSUE TITLE
Ability to enable debug logging in the Docker container

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3532]
e.g. to print the queries that are getting executed by a tool that's attempting to use pgjdbc and generating syntax we can't handle yet

**Comment by refset** [comment]
This should also add logging for pgwire errors which are sent back to the client but otherwise never logged, e.g. protocol violations (not all clients or drivers handle/return the `:message` component to the developer)

**Comment by jarohen** [comment]
see https://github.com/xtdb/xtdb/issues/3587 for a potential approach

**Comment by refset** [comment]
As discussed, we want a simpler approach for this than the custom logback
