### ISSUE TITLE
Allow special columns (_id, _valid_from, etc.) to be quoted in SQL statements

### ISSUE THREAD

**Issue by dekkers** [xtdb/crux#3542]
It looks like #2549 was introduced again when the `xt$` columns were renamed. The test-delimited-identifiers-in-insert-column-list-2549 test that was added when it was previously fixed got the quotes removed when the column was renamed to `_id`.

```
jeroen=> INSERT INTO test ("_id", "col_1") VALUES (1, 2);
ERROR:  Errors planning SQL statement:
  - INSERT does not contain mandatory _id column

jeroen=> SELECT _id, _valid_from FROM test;
 _id |           _valid_from           
-----+---------------------------------
   1 | 2024-07-30 20:49:23.49718+00:00
(1 row)

jeroen=> SELECT _id, "_valid_from" FROM test;
 _id | _column_2 
-----+-----------
   1 | 
(1 row)
```

**Comment by refset** [comment]
Thanks for the report @dekkers - hopefully you won't have to open it _again_ :slightly_smiling_face:
