### ISSUE TITLE
Ensure can pass full storageaccount/servicebus endpoint into Azure Blob Storage

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3586]
We currently take in the storage account/service bus namespace **names** and construct the URLs/endpoints within the Azure module, ie, 
```
(cond-> (-> (BlobServiceClientBuilder.)
            (.endpoint (str "https://" storage-account ".blob.core.windows.net"))
            (.credential credential)
            (.buildClient)))
```

This causes issues when used inside of private networks, where you need some ability to pass in the full private endpoint, so we should offer a mechanism to configure/provide this.

**Comment by danmason** [comment]
Currently in our config class we expect `storageaccount` and `servicebus-namespace` to be passed in, expecting those to be the names, we construct the actual endpoint from those.

Those are both (currently) expected/required params in the config.

Thinking we could either:
- Piggy back off of those for fully qualified endpoints, check if they are a URL or not and act accordingly (I'm not particularly keen on this approach).
- Keep them as required parameters, adding a couple of new "fully qualified" config params that override them when set.
- Make them both optional, add a couple of new fully qualified config params, and throw an exception if neither of the endpoint/name are set (ie, expect at least one to be present and throw an IAE if not).

**Comment by danmason** [comment]
To note, not entirely sure if we **need** to be able to full specify the endpoints or not - looking through the Azure docs it does seem like inside of private networks the only real difference is that the link is of the format `https://storage-account.privatelink.blob.core.windows.net` 

If that is the only difference, could instead add a new boolean option like `PrivatelinkEnabled` and edit the endpoints accordingly in the code. Need to better understand the endpoints setup using privatelink.

**Comment by chrismckelt** [comment]
> (cond-> (-> (BlobServiceClientBuilder.)
>             (.endpoint (str "https://" storage-account ".blob.core.windows.net"))
>             (.credential credential)
>             (.buildClient)))

Perhaps just check if the passed in name contains a '.'? if so accept the value.

Else append the normal non-private link URL  'https://" storage-account ".blob.core.windows.net'
