### ISSUE TITLE
Support executeMany in psycopg

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3597]
```python
import psycopg

# Define the connection parameters
conn_params = {
    "host": "localhost",
    "port": "5432"
}

# Example data to insert
data_to_insert = [
    (1, 'Alice'),
    (2, 'Bob'),
    (3, 'Charlie')
]

# SQL query for inserting data
insert_query = "INSERT INTO your_table_name (_id, name) VALUES (%s, %s)"

# Connect to the database
with psycopg.connect(**conn_params, autocommit=True) as conn:
   conn.adapters.register_dumper(str, psycopg.types.string.StrDumperVarchar)
    with conn.cursor() as cur:
        # Execute the INSERT query using executeMany
        cur.executemany(insert_query, data_to_insert)
        # Commit the transaction
        conn.commit()

print("Data inserted successfully!")
```

Errors with:
```
psycopg.errors.ProtocolViolation: DML is not allowed in a READ ONLY transaction
READ WRITE transaction required for INSERT, UPDATE, and DELETE statements
  - rollback the transaction: ROLLBACK
  - start a transaction: START TRANSACTION READ WRITE
```

Adding `cur.execute("BEGIN READ WRITE")` (/`START TRANSACTION READ WRITE`) immediately before the  `cur.executemany` line gives:
```
psycopg.errors.ProtocolViolation: invalid transaction state -- active SQL-transaction
```

~~I noticed there's an unchecked TODO in https://github.com/xtdb/xtdb/issues/2170 that sounds relevant:~~
> correct implicit transaction semantics as-per-spec (e.g SET TRANSACTION state used for queries outside of BEGIN COMMIT)

(should now be solved)

Also note that this example doesn't error when setting `autocommit=True`, but it still doesn't actually work correctly

**Comment by refset** [comment]
~~Setting `autocommit=True` now makes things work - good enough for now.~~

**Comment by refset** [comment]
Just spotted that autoCommit is actually causing multiple entries in `_txs` - needs further investigation

Adding `await cur.execute("START TRANSACTION READ WRITE")` causes:
```
cb0>: Errors parsing SQL statement:
  - line 1:0 mismatched input 'DEALLOCATE' expecting {'ASSERT', 'START', 'BEGIN', 'SET', 'COMMIT', 'ROLLBACK', 'SETTING', '(', 'WITH', 'FROM', 'VALUES', 'SELECT', 'DELETE', 'ERASE', 'INSERT', 'UPDATE'}
Error occurred: queries are unsupported in a READ WRITE transaction
```

The need for DEALLOCATE seems to suggest that executeMany assumes that explicit (non protocol-level) prepared statements may be in play https://github.com/psycopg/psycopg/blob/a358a31948a6ca527a1b0ff55ba8a5819518ab88/psycopg/psycopg/_connection_base.py#L482-L489

**Comment by FiV0** [comment]
So without autoCommit there is 3 entries in the `tx.txs` table and with there is one which is I think correct from the way I understand the API. `autoCommit = True` is committing the data after every call to the prepared statement.

@refset Could we open another card for the `START TRANSACTION READ WRITE` issue?

**Comment by FiV0** [comment]
So with `with conn.cursor() as cur` `psycopg` starts a new transaction block automatically for you (by sending `BEGIN`), when you issue `START TRANSACTION READ WRITE`, you start a new, more nested, transaction block which we currently don't support. This is related to https://github.com/xtdb/xtdb/issues/3242.
