### ISSUE TITLE
Add error handling around reading of params in pgwire

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#3653]
We should catch and return a pg error in the case we are unable to parse/read params in `xtify-param`

**Comment by FiV0** [comment]
For testing this in `psql`, it would be nice to support the syntax 
```sql
PREPARE my_statement (INTEGER, TEXT) AS
SELECT * FROM users WHERE id = $1 AND name = $2;
```

**Comment by refset** [comment]
@FiV0 note that `psql` also supports an inline `\bind` operator, e.g. as mentioned in https://github.com/xtdb/xtdb/issues/3572

**Comment by FiV0** [comment]
@refset The example above is misleading. I am looking for a way to send erroneous encodings to our pg-wire server. The problem is almost all clients are good citizens and do some check on the client side (i.e. when they are encoding).
