### ISSUE TITLE
`INSERT INTO _ RECORDS ?, ?` taking JSON document parameters

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3656]

**Comment by egg-juxt** [comment]
As a possible alternative to be considered, there is the column expansion `.*` syntax for composite types in Postgres, which we could generalize to apply to JSON params:
```
INSERT INTO <table> VALUES ($1.*)
```

**Comment by egg-juxt** [comment]
Also, this would accept JSON-LD, right?

**Comment by refset** [comment]
> this would accept JSON-LD, right?

This part of the puzzle will be solved here: https://github.com/xtdb/xtdb/issues/3659
