### ISSUE TITLE
Ability to use the full range of scalar types within nested data parameters via pgwire

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3659]
Since https://github.com/xtdb/xtdb/issues/3648 it is now possible to INSERT or UPDATE nested, document-like data via pgwire, but this method is inherently restricted to the JSON scalar types.

If a user wants to make use of XTDB's extensive scalar support (for the fully range of dates, numbers etc.) within nested data parameters, then pgwire is currently incapable of handling that data (beyond very limited circumstances where literals may be used instead of parameters). A range of solutions may be possible.

Some users may find it sufficient to rely on casting of JSON-typed values at query-time (such that the stored data remains in its stringified form) but this is not ideal.

**Comment by jarohen** [comment]
I suspect this'll be a per-client-lang solution, because it'll likely involve translating whatever strongly-typed timestamp etc types each language has.

**Comment by refset** [comment]
Solved by the introduction of a Transit OID, JSON-LD could be added later.
