### ISSUE TITLE
Document Metabase support

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3691]
List of known outstanding compatibility issues:

- [x] https://github.com/xtdb/xtdb/issues/3712
- [x] https://github.com/xtdb/xtdb/issues/3714
- [x] https://github.com/xtdb/xtdb/issues/3699
- [ ] Use of nested fields?

([search for 'metabase' tagged issues](https://github.com/search?q=repo%3Axtdb%2Fxtdb+metabase&type=issues))

**Comment by jarohen** [comment]
@refset will close this in favour of the individual issues? good idea to add a tag

**Comment by refset** [comment]
Thanks. If there's any Metabase-specific guidance we need to document in future then we can add a dedicated page, but for now I've added a reference to the Clients overview page to indicate that we explicitly support it: https://github.com/xtdb/xtdb/commit/29dd052e8fed31ee2667da30f1fec3ebb53a4b3b#diff-0d0f5d84396e05890a3a64f2a88711e40447096217e6c53803fc72597e9d3acbR24
