### ISSUE TITLE
Slow query when overwriting readings-style data

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3751]
Given data of the shape:
```sql
INSERT INTO readings (_id, value, _valid_from, _valid_to) VALUES
(1, 100, TIMESTAMP '2024-01-01T00:00:00Z', TIMESTAMP '2024-01-01T00:05:00Z')
```

Inserting ~2 years of 5 minutely readings for a single `_id` (as above) and then overwriting that (accidentally) 5 times these queries all perform slowly:
```sql
SELECT COUNT(*) -- ~80,000, also takes ~75s
FROM readings FOR VALID_TIME ALL
```

```sql
SELECT COUNT(*) -- ~400,000, takes ~75s
FROM readings FOR VALID_TIME ALL FOR SYSTEM_TIME ALL
```

The data is inserted sequentially in `_valid_from` order and each insert is repeated 5 times total.

**Comment by FiV0** [comment]
In both queries all versions are considered as there is no version outside of the valid time range in this case. The optimisations in the primary index only help if there are valid time ranges that can be pruned (which doesn't apply here).

**Comment by egg-juxt** [comment]
Did some tests of `SELECT COUNT(*) FROM reading FOR VALID_TIME ALL` witha result of 105407. (1 year of measurements). Elapsed time results:
1. First insert: 397.425668 msecs
2. overwrite: 18319.939247 msecs
3. overwrite: 25887.873753 msecs
4. overwrite: 47973.490517 msecs
5. overwrite: 51511.922718 msecs
6. overwrite: 61536.997143 msecs

Code
```
(defn every-5-min [year]
  (let [start-date (jt/local-date-time year 1 1 0 0)
        end-date (jt/plus start-date (jt/years 1))]
    (->> (iterate #(jt/plus % (jt/duration 5 :minutes)) start-date)
      (take-while #(jt/before? % end-date))
      (map #(jt/instant % (jt/zone-id "UTC"))))))

(comment
  (let [dates (every-5-min 2024)
        values (repeatedly #(rand-int 20))
        txs (for [[from to value] (map vector dates (next dates) values)]
              [:put-docs {:into :reading
                          :valid-from from
                          :valid-to to}
               {:xt/id 1
                :value value}])]
    (xt/submit-tx node txs))

  (time (xtdb.api/q node "SELECT COUNT(*) FROM reading FOR VALID_TIME ALL")))
```

**Comment by FiV0** [comment]
We have a small benchmark at https://github.com/xtdb/xtdb/blob/66dbc13d52a617fb8c9af001797265f6a4a7ec48/modules/bench/src/main/clojure/xtdb/bench/readings.clj. 

Are the times to slow? If so let me know and I can pick this up earlier.

**Comment by FiV0** [comment]
To restate the problem (as I first misread). 
> First insert: 397.425668 msecs
> overwrite: 18319.939247 msecs

After an initial overwrite the query times are way off. Doubling the amount of data should increase query time linearly (~800ms not 18000ms).

**Comment by FiV0** [comment]
In light of not merging #3824, I am keeping this open for now, but overall the performance should be better.
