### ISSUE TITLE
Metabase: Support filters for valid time

### ISSUE THREAD

**Issue by egg-juxt** [xtdb/crux#3754]
We're using valid_time as the time column for time series data. We are using Metabase to inspect the data. In particular, we want  a graph of values covering 1 day, where the date can be selected using a Metabase filter.

### Using a Metabase Filter inside SQL WHERE
```
SELECT
  "public"."reading"."value" AS "value",
  "public"."reading"."_valid_from" AS "_valid_from"
FROM
  "public"."reading" FOR VALID_TIME ALL
WHERE
  {{ id_filter }}
  AND _valid_from >= {{ day }}
  AND _valid_from <= ({{ day }} + INTERVAL 'P1D')
```
Here, we're using a plain `day` filter. The query runs, but will gather valid_times for the whole `reading` table, which affects the performance.

### Using a Metabase Filter in the table's temporal filter:
```
...
FROM
  "public"."reading" FOR VALID_TIME FROM {{ day }} TO ({{ day }} + INTERVAL 'P1D')
...
```
This is an error as expressions are not accepted for setting valid-time bounds. Metabase does not provide a way for doing such a calculation on the client.

### Using a Metabase Field Filter inside WHERE:
```
WHERE {{ valid_from_filter }}
```
Metabase Field Filters build a whole boolean term for the WHERE clause.  Field Filters are more convenient and have more facilities than simple Filters. This is not possible to set up in Metabase, as `_valid_from` is not in `information_schema.columns`.

## Proposal

We'd provide better compatibility with existing SQL tooling if we:
- [x] #3306 
- [ ] #3849 
- [x] #3850

All this could apply to system-time as well.

**Comment by refset** [comment]
Related cards, for (1) expressions - #3306 and for (2) constant folding #3849

**Comment by jarohen** [comment]
split, closing
