### ISSUE TITLE
pgwire client with binary encoding (elixir/postgrex) query fails with text fields 

### ISSUE THREAD

**Issue by mpisanko** [xtdb/crux#3758]
using the xtdb/postgrex@xtdb-support (a fork of elixir-ecto/postgrex) against mpisanko/xtdb@elixir-support (adds necessary columns in pg_type for postgrex - typsend+typreceive).

16:17:44.100 [pgwire-connection--pool-3-thread-2] INFO  xtdb.pgwire - Fields  [{:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :binary, :col-type :utf8, :field-name "typname", :typname "text", :typreceive "textrecv", :column-name "typname", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]}]
16:17:44.103 [pgwire-connection--pool-3-thread-2] ERROR xtdb.pgwire - An exception was caught during query result set iteration
java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object, Object, Object)" because "write_binary" is null
        at xtdb.pgwire$cmd_send_query_result$reify__43829$fn__43831.invoke(pgwire.clj:1085)
        at clojure.core$map$fn__5952.invoke(core.clj:2770)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.lang.RT.countFrom(RT.java:670)
        at clojure.lang.RT.count(RT.java:663)
        at xtdb.pgwire$io_list$fn__43442.invoke(pgwire.clj:579)
        at xtdb.pgwire$io_record$write_record__43453.invoke(pgwire.clj:624)
        at xtdb.pgwire$cmd_write_msg.invokeStatic(pgwire.clj:833)
        at xtdb.pgwire$cmd_write_msg.invoke(pgwire.clj:821)
        at xtdb.pgwire$cmd_send_query_result$reify__43829.accept(pgwire.clj:1090)
        at xtdb.operator.project.ProjectCursor$reify__39231.accept(project.clj:133)
        at xtdb.operator.rename.RenameCursor$reify__40024.accept(rename.clj:39)
        at xtdb.information_schema.InformationSchemaCursor$fn__33529.invoke(information_schema.clj:317)
        at xtdb.information_schema.InformationSchemaCursor.tryAdvance(information_schema.clj:315)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
        at xtdb.query$wrap_cursor$reify__41907.tryAdvance(query.clj:83)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.pgwire$cmd_send_query_result.invokeStatic(pgwire.clj:1059)
        at xtdb.pgwire$cmd_send_query_result.invoke(pgwire.clj:1050)
        at xtdb.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1205)
        at xtdb.pgwire$cmd_exec_query.invoke(pgwire.clj:1188)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1564)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1545)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1626)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1601)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1683)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1639)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1724)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1692)
        at xtdb.pgwire$accept_loop$fn__44101$fn__44102$fn__44103.invoke(pgwire.clj:1777)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
16:17:44.127 [pgwire-connection--pool-3-thread-3] INFO  xtdb.pgwire - Fields  [{:write-text #function[xtdb.types/fn--12269/fn--12270], :column-oid 23, :result-format :text, :typlen 4, :col-type :i32, :field-name "oid", :typname "int4", :typreceive "int4recv", :write-binary #function[xtdb.types/fn--12269/fn--12272], :read-binary #function[xtdb.types/fn--12269/fn--12275], :column-name "oid", :typsend "int4send", :read-text #function[xtdb.types/fn--12269/fn--12277]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "typname", :typname "text", :typreceive "textrecv", :column-name "typname", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "typsend", :typname "text", :typreceive "textrecv", :column-name "typsend", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "typreceive", :typname "text", :typreceive "textrecv", :column-name "typreceive", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "_column_5", :typname "text", :typreceive "textrecv", :column-name "_column_5", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "_column_6", :typname "text", :typreceive "textrecv", :column-name "_column_6", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]} {:write-text #function[xtdb.types/fn--12280/fn--12281], :column-oid 20, :result-format :text, :typlen 8, :col-type :i64, :field-name "_column_7", :typname "int8", :typreceive "int8recv", :write-binary #function[xtdb.types/fn--12280/fn--12283], :read-binary #function[xtdb.types/fn--12280/fn--12286], :column-name "_column_7", :typsend "int8send", :read-text #function[xtdb.types/fn--12280/fn--12288]} {:write-text #function[xtdb.types/fn--12280/fn--12281], :column-oid 20, :result-format :text, :typlen 8, :col-type :i64, :field-name "_column_8", :typname "int8", :typreceive "int8recv", :write-binary #function[xtdb.types/fn--12280/fn--12283], :read-binary #function[xtdb.types/fn--12280/fn--12286], :column-name "_column_8", :typsend "int8send", :read-text #function[xtdb.types/fn--12280/fn--12288]} {:write-text #function[xtdb.types/fn--12354], :column-oid 25, :result-format :text, :col-type :utf8, :field-name "_column_9", :typname "text", :typreceive "textrecv", :column-name "_column_9", :typsend "textsend", :read-text #function[xtdb.types/fn--12352]}]

steps to reproduce (running elixir 1.17.3, Erlang/OTP 27: `brew install elixir`):
- run xtdb with additional values in pg_type
- run iex -S mix in the xtdb/postgrex repo (first you need to run mix deps.get)
iex>  {:ok,pid} = Postgrex.start_link(hostname: "localhost", username: "xtdb", database: "xtdb", flavour: "xtdb")
{:ok, #PID<0.189.0>}

- select something that is numeric (integer) - mostly works - there's one (114 - OID for json) decoded to `~c"r"`
iex> Postgrex.query!(pid, "select oid from pg_type", [])
%Postgrex.Result{
  command: :select,
  columns: ["oid"],
  rows: [
    [701],
    [1082],
    [700],
    [21],
    [3802],
    [1184],
    [23],
    [20],
    [16384],
    [3910],
    [1186],
    [1043],
    [2950],
    ~c"r",
    [1114],
    [16],
    [25],
    [2205]
  ],
  num_rows: 18,
  connection_id: 5,
  messages: []
}

- select a text value - and it fails:
iex> Postgrex.query!(pid, "select typname from pg_type", [])
** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3

    The following arguments were given to Postgrex.Protocol.handle_msg/3:

        # 1
        %Postgrex.Protocol{
          sock: {:gen_tcp, #Port<0.4>},
          connection_id: 5,
          connection_key: 0,
          peer: {{127, 0, 0, 1}, 5432},
          types: {Postgrex.DefaultTypes, #Reference<0.2847801179.1978531841.15666>},
          null: nil,
          timeout: 15000,
          ping_timeout: 15000,
          parameters: #Reference<0.2847801179.1978400769.15686>,
          queries: #Reference<0.2847801179.1978531841.15683>,
          postgres: {:idle, #Reference<0.2847801179.1978400769.15914>},
          transactions: :naive,
          buffer: "",
          disconnect_on_error_codes: [],
          scram: nil,
          disable_composite_types: false,
          messages: [],
          flavour: "xtdb"
        }

        # 2
        %{
          notify: #Function<11.10100617/2 in Postgrex.Protocol.notify/1>,
          prepare: false,
          mode: :transaction
        }

        # 3
        {:msg_command_complete, "SELECT 0"}

    Attempted function clauses (showing 3 out of 3):

        defp handle_msg(s, _status, {:msg_parameter, name, value})
        defp handle_msg(s, status, {:msg_notify, _, channel, payload})
        defp handle_msg(s, _status, {:msg_notice, fields})

    (postgrex 0.19.1) lib/postgrex/protocol.ex:3397: Postgrex.Protocol.handle_msg/3
    (postgrex 0.19.1) lib/postgrex/protocol.ex:3045: Postgrex.Protocol.recv_ready/3
    (postgrex 0.19.1) lib/postgrex/protocol.ex:3082: Postgrex.Protocol.error_ready/4
    (postgrex 0.19.1) lib/postgrex/protocol.ex:2157: anonymous fn/2 in Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.1) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.1) lib/db_connection.ex:1333: DBConnection.run_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:1428: DBConnection.run/6
    iex:3: (file)

15:53:33.257 [error] GenServer #PID<0.228.0> terminating
** (DBConnection.ConnectionError) client #PID<0.225.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3
    (postgrex 0.19.1) lib/postgrex/protocol.ex:3397: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{sock: {:gen_tcp, #Port<0.4>}, connection_id: 5, connection_key: 0, peer: {{127, 0, 0, 1}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.2847801179.1978531841.15666>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.2847801179.1978400769.15686>, queries: #Reference<0.2847801179.1978531841.15683>, postgres: {:idle, #Reference<0.2847801179.1978400769.15914>}, transactions: :naive, buffer: "", disconnect_on_error_codes: [], scram: nil, disable_composite_types: false, messages: [], flavour: "xtdb"}, %{notify: #Function<11.10100617/2 in Postgrex.Protocol.notify/1>, prepare: false, mode: :transaction}, {:msg_command_complete, "SELECT 0"})
    (postgrex 0.19.1) lib/postgrex/protocol.ex:3045: Postgrex.Protocol.recv_ready/3
    (postgrex 0.19.1) lib/postgrex/protocol.ex:3082: Postgrex.Protocol.error_ready/4
    (postgrex 0.19.1) lib/postgrex/protocol.ex:2157: anonymous fn/2 in Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.1) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.1) lib/db_connection.ex:1333: DBConnection.run_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:1428: DBConnection.run/6
    (db_connection 2.4.1) lib/db_connection.ex:593: DBConnection.parsed_prepare_execute/5

    (db_connection 2.4.1) lib/db_connection/connection.ex:198: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 6.1) gen_server.erl:2371: :gen_server.try_handle_cast/3
    (stdlib 6.1) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.1) proc_lib.erl:340: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.2847801179.1978531841.15904>, %DBConnection.ConnectionError{message: "client #PID<0.225.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3\n    (postgrex 0.19.1) lib/postgrex/protocol.ex:3397: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{sock: {:gen_tcp, #Port<0.4>}, connection_id: 5, connection_key: 0, peer: {{127, 0, 0, 1}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.2847801179.1978531841.15666>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.2847801179.1978400769.15686>, queries: #Reference<0.2847801179.1978531841.15683>, postgres: {:idle, #Reference<0.2847801179.1978400769.15914>}, transactions: :naive, buffer: \"\", disconnect_on_error_codes: [], scram: nil, disable_composite_types: false, messages: [], flavour: \"xtdb\"}, %{notify: #Function<11.10100617/2 in Postgrex.Protocol.notify/1>, prepare: false, mode: :transaction}, {:msg_command_complete, \"SELECT 0\"})\n    (postgrex 0.19.1) lib/postgrex/protocol.ex:3045: Postgrex.Protocol.recv_ready/3\n    (postgrex 0.19.1) lib/postgrex/protocol.ex:3082: Postgrex.Protocol.error_ready/4\n    (postgrex 0.19.1) lib/postgrex/protocol.ex:2157: anonymous fn/2 in Postgrex.Protocol.bind_execute_close/4\n    (db_connection 2.4.1) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.1) lib/db_connection.ex:1333: DBConnection.run_execute/5\n    (db_connection 2.4.1) lib/db_connection.ex:1428: DBConnection.run/6\n    (db_connection 2.4.1) lib/db_connection.ex:593: DBConnection.parsed_prepare_execute/5\n", severity: :error, reason: :error}, %Postgrex.Protocol{sock: {:gen_tcp, #Port<0.4>}, connection_id: 5, connection_key: 0, peer: {{127, 0, 0, 1}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.2847801179.1978531841.15666>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.2847801179.1978400769.15686>, queries: #Reference<0.2847801179.1978531841.15683>, postgres: {:idle, #Reference<0.2847801179.1978400769.15914>}, transactions: :naive, buffer: "", disconnect_on_error_codes: [], scram: nil, disable_composite_types: false, messages: [], flavour: "xtdb"}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{sock: {:gen_tcp, #Port<0.4>}, connection_id: 5, connection_key: 0, peer: {{127, 0, 0, 1}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.2847801179.1978531841.15666>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.2847801179.1978400769.15686>, queries: #Reference<0.2847801179.1978531841.15683>, postgres: {:idle, #Reference<0.2847801179.1978400769.15914>}, transactions: :naive, buffer: "", disconnect_on_error_codes: [], scram: nil, disable_composite_types: false, messages: [], flavour: "xtdb"}}

**Comment by mpisanko** [comment]
In fact the write-binary functions are missing from a couple types. adding them solves this problem.
will try the fix on `elixir-support` branch

**Comment by mpisanko** [comment]
elixir-ecto/postgrex uses the following query:
```sql
SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
        coalesce(d.typelem, t.typelem), coalesce(r.rngsubtype, 0), 
        ARRAY (
          SELECT a.atttypid 
          FROM pg_attribute AS a  
          WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped  
          ORDER BY a.attnum
        ) 
FROM pg_type AS t 
LEFT JOIN pg_type AS d ON t.typbasetype = d.oid 
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid 
       OR r.rngmultitypid = t.oid 
       OR (t.typbasetype <> 0 AND r.rngtypid = t.typbasetype) 
WHERE (t.typrelid = 0) AND (t.typelem = 0 OR NOT EXISTS 
                            (SELECT 1 FROM pg_catalog.pg_type s WHERE s.typrelid != 0 AND s.oid = t.typelem));

```

**Comment by olivercsr** [comment]
I'm also seeing the "write_binary is null" error message when trying to query (select) fields that contain strings from Common Lisp with the postmodern postgres client, e.g.

```cl
(pg:with-connection '("db" "user" "pw" "localhost"
                      :port 5432
                      :pooled-p nil
                      :use-binary t
                      ;;:use-ssl :try
                      :application-name "myapp")
    (pg:execute (:insert-into 'foo :set '_id 123 'name "heyjo"))
    (pg:query (:select '_id 'name :from 'foo)))
```

The "insert" will successfully complete, but the subsequent "select" fails with the xtdb server error "write_binary is null", due to "name" field returning a string (text/varchar?) value:

```
...
19:09:22 | INFO  xtdb.cli | Node started
19:09:29 | DEBUG xtdb.pgwire | Interpreting SQL:  INSERT INTO foo (_id, name)  VALUES (123, E'heyjo')
19:09:29 | DEBUG xtdb.pgwire | Interpreting SQL:  (SELECT _id, name FROM foo)
19:09:29 | ERROR xtdb.pgwire | An exception was caught during query result set iteration
java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object, Object, Object)" because "write_binary" is null
        at xtdb.pgwire$cmd_send_query_result$reify__28362$fn__28364.invoke(pgwire.clj:1084)
        at clojure.core$map$fn__5952.invoke(core.clj:2770)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.lang.RT.countFrom(RT.java:670)
        at clojure.lang.RT.count(RT.java:663)
        at xtdb.pgwire$io_list$fn__27975.invoke(pgwire.clj:579)
        ...
```
