### ISSUE TITLE
pgwire generic array OID return type support is needed for Postgrex to work

### ISSUE THREAD

**Issue by mpisanko** [xtdb/crux#3775]
```
postgres=# select array(select 1);
 array
-------
 {1}
(1 row)
```
```
xtdb=> select array(select 1);
 _column_1
-----------
 [1]
(1 row)
```

https://www.postgresql.org/docs/17/arrays.html

**Comment by refset** [comment]
@mpisanko it sounds like this is actually because of the default JSON fallback return type (because XT doesn't support pgwire array types yet). Do you know which array types are needed for Postgrex to work?

**Comment by mpisanko** [comment]
not actual 'types' @refset - just the query results should have squiglies, not squares (the former one is the query result in postgres, the latter is xtdb).
postgrex relies on arrays being returned as {x, y, z} - as they are in postgres

**Comment by mpisanko** [comment]
so actually - sorry - misinterpreted:
```
postgres=# select oid, typname from pg_type where typname like '%array%';
 oid  |        typname
------+-----------------------
 2277 | anyarray
 ---2776 | anynonarray ---
 5078 | anycompatiblearray
 ---5079 | anycompatiblenonarray ---
```

**Comment by mpisanko** [comment]
will do the most basic that i know are needed to get postgrex off the ground: _int4, _int8, empty array
