### ISSUE TITLE
Configuration docs overhaul

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3793]
Re-organise to focus on the user-facing Docker journeys, not the underlying 'modules':

1. standalone image (common env vars, common yaml)
2. 3x cloud images (+ additional env vars and yaml for each)

Users should not have to be conscious of XTDB as being composed of independent modules (at least initially), beyond the need to group/structure configurations.

Notes about logging, e.g. `docker run --pull=always -p 5432:5432 -e XTDB_LOGGING_LEVEL_PGWIRE=debug ghcr.io/xtdb/xtdb:edge` per:
> XTDB_LOGGING_LEVEL=info for all XTDB logging, XTDB_LOGGING_LEVEL_FOO_BAR=trace to set for xtdb.foo.bar namespace

**Comment by egg-juxt** [comment]
I believe we should have only one Docker image. I don't think the cloud images are adding anything substantial?

**Comment by refset** [comment]
I tend to agree, but that's definitely a separate issue - I think the only difference in regards the proposed config docs would be having a different image suffix on each page vs. a consistent image name.

**Comment by jarohen** [comment]
obsoleted with #3896?

will optimistically close, feel free to re-open
