### ISSUE TITLE
Ingestion stopped by INSERT with fewer columns available than are specified

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3797]
e.g. `INSERT INTO docs (_id, foo) SELECT 1` [Play](https://play.xtdb.com/?version=2.0.0-b1&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgZm9vKSBTRUxFQ1QgMSJ9XQ%3D%3D&query=U0VMRUNUIF9pZCwgZm9vIEZST00gZG9jcw%3D%3D)

`clojure.lang.ExceptionInfo: Ingestion stopped: Cannot invoke "org.apache.arrow.vector.types.pojo.Field.getType()" because "field" is null {}`

**Comment by FiV0** [comment]
Got fixed somewhere along the way
