### ISSUE TITLE
Incorrect example in XTQL delete docs

### ISSUE THREAD

**Issue by espzip** [xtdb/crux#3815]
In the documentation for XTQL :delete (https://docs.xtdb.com/reference/main/xtql/txs.html#_delete), the example reads:
```
[:delete {:table :users
          :bind [{:email $email}]}
 {:email "james@example.com"}]
```
This is incorrect. `:table` should be replaced with `:from`. The bind section is also somewhat ambiguous because both the left and right side are named 'email'. It may be more illustrative to use different names for the attribute and the argument in the binding.

**Comment by jarohen** [comment]
thanks @espzip :pray:
