### ISSUE TITLE
Clojure user experience working with Transit-encoded PgObjects

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3844]
We currently support [Transit](https://github.com/cognitect/transit-format) as an extension type/encoding over the pg-wire protocol, for better round-tripping of values that don't have a native JSON encoding.

Current state:

* Users can (3081f915b92a46762ffcf4a4470c187ec971237d) set 'fallback_output_format' on the connection to return Transit objects
* We have `transit->pgobject` which means that users can `["INSERT INTO table RECORDS ?" (transit->pgobject doc)]`, but this is not exposed to users.

Is there anything we can do to both make this more accessible, and publicise it?

* Could this support be added to next.jdbc? (and would there be appetite to do so?)
* Consider adding `->pgobject` and `<-pgobject` to `xtdb.serde` (already bundled in `xtdb-api`), or maybe create `xtdb.api.transit` if we don't want to inadvertently make `xtdb.serde` a public API
* Document it up in the Clojure documentation

**Comment by refset** [comment]
Working sample code that might be helpful (borrowing from pgwire.clj/serde.clj, also implements `pgobect->transit`):
```clj
(ns main
  (:require [next.jdbc :as jdbc]
            [cognitect.transit :as transit])
  (:import org.postgresql.util.PGobject
           [java.io ByteArrayInputStream ByteArrayOutputStream]))

(def db
  {:dbtype "postgresql"
   :dbname "xtdb"
   :user "xtdb"
   :password "xtdb"
   :host "localhost"
   :port 5432})

;; this is relatively low-level code - the usual connection pooling
;; and SQL abstraction libraries can be used too.

(with-open [conn (jdbc/get-connection db)]
  (jdbc/execute! conn ["INSERT INTO users RECORDS {_id: 'jms', name: 'James'}, {_id: 'joe', name: 'Joe'}"])

  (prn (jdbc/execute! conn ["SELECT * FROM users"])))

(defn write-transit
  (^bytes [v] (write-transit v nil))
  (^bytes [v fmt]
   (with-open [baos (ByteArrayOutputStream.)]
     (-> (transit/writer baos (or fmt :msgpack) {#_#_:handlers transit-write-handlers})
         (transit/write v))
     (.toByteArray baos))))

(defn transit->pgobject [v]
  (doto (PGobject.)
    (.setType "transit")
    (.setValue (String. (write-transit v :json)))))

(defn read-transit
  ([bytes] (read-transit bytes nil))
  ([bytes fmt]
   (with-open [bais (ByteArrayInputStream. bytes)]
     (transit/read (transit/reader bais (or fmt :msgpack) {#_#_:handlers transit-read-handlers})))))

(defn pgobject->transit [v]
  (cond
    (instance? PGobject v)
    (try
      (read-transit (.getBytes (.getValue v)) :json)
      (catch Exception _ ; fallback if it’s not transit-encoded
        v))

    (map? v)
    (into {} (map (fn [[k v]] [k (pgobject->transit v)]) v))

    (sequential? v)
    (mapv pgobject->transit v)

    :else v))

(with-open [conn (jdbc/get-connection db)]
  (jdbc/execute! conn ["INSERT INTO arbitrary_maps RECORDS ?" (transit->pgobject {:_id "jdt", :name "Jeremy", :oh {:wow #inst "2020-01-01" :very {:cool [#inst "2021-01-01" "hi" 4]}}})])

  (let [result (jdbc/execute-one! conn ["SELECT * FROM arbitrary_maps"])]
    (prn (pgobject->transit result))))
```

**Comment by egg-juxt** [comment]
When using PostgresJS, the following code inserts a single record:

```
await sql`INSERT INTO ${sql(table)} RECORDS ${sql.typed(typedData, pgType)}`
```

In order to insert multiple records in a single statement, I need to workaround the standard PostgresJS query builder and build the list of parameter placeholders in the query. This also prevents using other facilities of the query builder (like escaping identifiers):

```
          await sql.unsafe(
            'INSERT INTO ' +
              this.escapeIdentifier(table) +
              ' RECORDS ' +
              Array(typedData.length).fill('?').join(','),
            typedData.map((elem) => sql.typed(elem, 16384)),
          );
```

It would be nice that arrays would be accepted in a single parameter, in order to insert more than one record.

**Comment by jarohen** [comment]
@egg-juxt yeah, I don't disagree, it's a little weird - but how it is is more in keeping with how `VALUES` works in SQL.

`INSERT INTO foo VALUES (1, 'a'), (2, 'b')` becomes `INSERT INTO foo VALUES (?, ?), (?, ?)`.

Have you tried preparing the statement for one element and executing it repeatedly, with one element in each call?

i.e. the equivalent of

* prepare `INSERT INTO foo VALUES (?, ?)`
* execute with each row of values
