### ISSUE TITLE
Implement pgwire PREPARE

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3855]
`PREPARE` is useful for making `.sql` data loading scripts run fast (by avoiding re-parsing and re-compiling ~identical statements).

https://www.postgresql.org/docs/current/sql-prepare.html

**Comment by mpisanko** [comment]
section 20.6 <prepare statement> of SQL2011 spec is somewhat hazy to me, but looks like it _should_ be something along the lines of: 
`PREPARE statement_name FROM 'select bar from foo where id = $1'` 
and the statement can be one of a number of: 
- preparable SQL data statement
- preparable SQL schema statement
- preparable SQL transaction statement
- preparable SQL control statement
- preparable SQL session statement
- preparable implementation-defined statement

**Comment by mpisanko** [comment]
postgres [follows](https://www.postgresql.org/docs/current/sql-prepare.html) the following:
`PREPARE name [ ( data_type [, ...] ) ] AS statement`
eg:
```sql
PREPARE fooplan (int, text, bool, numeric) AS
    INSERT INTO foo VALUES($1, $2, $3, $4);
```
we can start by implementing the pg version and then adding on the SQL spec compliant version.

**Comment by mpisanko** [comment]
the prepare can cause an error when the parameter type does not match the actual column type:
```
postgres=# create table foo (id int, foo TEXT);
CREATE TABLE
postgres=# insert into foo values (1, 'bar');
INSERT 0 1
postgres=# select * from foo;
 id | foo
----+-----
  1 | bar
(1 row)

postgres=# select * from foo where id = '1';
 id | foo
----+-----
  1 | bar
(1 row)

postgres=# select * from foo where id = 'foo';
ERROR:  invalid input syntax for type integer: "foo"
LINE 1: select * from foo where id = 'foo';
```

**Comment by mpisanko** [comment]
prepared statements only make sense in pgwire - what do we do in non-pgwire context?
there's currently no support for prepared DML in pgwire. this will be a bit more involved.

**Comment by FiV0** [comment]
Some questions that came about while discussing with @mpisanko 
  - Do we need some version of PreparedStatement for DML now?
 -  How should `PREPARE` behave on non pg-wire connection (in-memory, http) ?
     - not supported?
