### ISSUE TITLE
Add `PATCH`

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3879]
for upserting documents into XT using standard map merge.

SQL has `MERGE`, which we can add, but this gets pretty verbose in this common case.

e.g. `PATCH INTO foo (FOR PORTION OF VALID_TIME ...) (RECORDS { ... } | VALUES ( ... ))`

* Behaviour is that, either for the valid time provided or from now -> ∞, we either insert or merge the given records into 
* Records must contain `_id`, same as `INSERT`
* We update for the segment of the patched timeline that are present, and insert for segments that are not - after the operation, the whole segment is covered.

**Comment by refset** [comment]
How about something like `UPDATE products PATCH {price: price * 0.90, product_description: product_description + " - now 10% off!"} WHERE price > 200;`

Also relevant - JSON Merge Patch https://datatracker.ietf.org/doc/html/rfc7386

**Comment by jarohen** [comment]
@refset: I'm not so keen on including this in `UPDATE` because `UPDATE` usually carries the semantics that, if there are no matching rows, nothing happens, whereas here we're talking about inserting it in the doc's absence.

**Comment by egg-juxt** [comment]
Pending clarifying with design partner how valid-time is required to behave if using PATCH.
