### ISSUE TITLE
Implement pgwire statement limit for queries that return rows

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3902]
e.g. currently `.setMaxRows` on a Statement in JDBC will be ignored

Per https://github.com/xtdb/xtdb/blob/52ec4d4a6a6790de43814577f370fdce028ad1f0/core/src/main/clojure/xtdb/pgwire.clj#L1540

**Comment by refset** [comment]
FYI @seancorfield 🙂

**Comment by seancorfield** [comment]
Thanks @refset Looks like the latest Docker image is still `5aafb16` so I'll have to wait a bit for a new build to update `next.jdbc`'s test suite and actually test this.

**Comment by seancorfield** [comment]
Ah, `latest` is `5aafb16` but `nightly` is built -- I'll switch `next.jdbc` over to test against the nightly builds.

**Comment by seancorfield** [comment]
Confirmed fixed: I've reinstated the `:max-rows` tests for XTDB and they all pass.
