### ISSUE TITLE
Comprehensive native type handling over pgwire

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3909]
- [X] UUID - https://www.postgresql.org/docs/current/datatype-uuid.html Currently, attempting to return a UUID causes a server error: `Unexpected type encountered by pgwire (class java.util.UUID)`
- [x] VARBINARY - example in the docs is `X('41af8e01')` gives `java.lang.AbstractMethodError: Receiver class xtdb.sql.plan.ExprPlanVisitor does not define or inherit an implementation of the resolved method 'abstract java.lang.Object visitBinaryStringLiteral(xtdb.antlr.Sql$BinaryStringLiteralContext)' of interface xtdb.antlr.SqlVisitor.`
- [x] URI - example in the docs `SELECT URI 'https://xtdb.com';` gives `- Errors parsing SQL statement:  - line 1:11 extraneous input ''https://xtdb.com'' expecting {<EOF>, ';'}`
- [ ] ???

The [json-clj](https://github.com/xtdb/xtdb/blob/069aa683a28e9c1be8a9a9c309463cc328010ebf/core/src/main/clojure/xtdb/pgwire.clj#L541) function needs to be extended. However, in light of this and [another recent example](https://github.com/xtdb/xtdb/issues/3866) we should exhaustively make sure that all native types can be handled (/ be clear on which ones can't).

**Comment by refset** [comment]
UUID now support fixed in https://github.com/xtdb/xtdb/pull/3911

**Comment by jarohen** [comment]
@refset - what's the gap between current state and calling this done?

I'll optimistically close given it was moved to 'Done' but feel free to re-open and flesh out the checklist

**Comment by refset** [comment]
Just added two more - again, not exhaustive. Might be safest to comment out problematic types in the docs until we're ready to support them.

**Comment by FiV0** [comment]
We should now support everything on https://docs.xtdb.com/reference/main/data-types.html with all the caveats of pgwire conversions (Is there an equivalent pg type? Is it nested? etc...).
