### ISSUE TITLE
JDBC - `INSERT INTO ... RECORDS` with parameters fails

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3958]
The following
```clj
(deftest test-records-as-params
  (with-open [conn (jdbc-conn)]
    (jdbc/execute! conn ["INSERT INTO foomap RECORDS ?" {:_id 1 :a {:b 42}}])

    (t/is (= [{:xt/id 1, :a {:b 42}}]
             (q conn ["SELECT * FROM foomap where _id = 1"])))))
```
fails with 
`error: org.postgresql.util.PSQLException: No hstore extension installed`.

**Comment by jarohen** [comment]
yep, I don't think this is something we can do on the user's behalf without global side-effects (`extend-protocol`).

have to wrap the record: `(xt-jdbc/->pg-obj {:_id 1, ...})`
