### ISSUE TITLE
Remove xtdb.mirrors.time-literals to avoid conflict with Tick / time-literals

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3973]
Currently a user is blocked when trying to use transit serdes over JDBC because of a conflict with [Tick](https://github.com/juxt/tick) (used elsewhere in their application code).

The suggestion, IIUC, is to simply remove our custom mirror and depend on the upstream time-literals library directly.

**Comment by jarohen** [comment]
it'll likely be the EDN readers rather than Transit - EDN readers are global to the JVM, Transit are specific to our call-sites so should be fine.

I've moved ours under `#xt`, so they should now happily co-exist
