### ISSUE TITLE
BIT literals not supported

### ISSUE THREAD

**Issue by seancorfield** [xtdb/crux#3974]
```sql
INSERT INTO btest (_id, v) VALUES (6, b'1')
```

This is valid syntax in PostgreSQL and MySQL (although not in MS SQL Server and a few other DBs).

**Comment by seancorfield** [comment]
Or maybe more accurate to say `BIT` is just not a supported type? I tried `1::BIT` which doesn't work either. I believe both work in PG?

**Comment by seancorfield** [comment]
Never mind, I see BIT is not listed in data types. I was just adapting some PG SQL in my `next.jdbc` tests.

**Comment by refset** [comment]
I suspect that if we were to add BIT literal support we would also need to create a (new) custom 1-bit type based on Arrow's existing boolean type: https://arrow.apache.org/docs/python/api/datatypes.html

Happy to consider further it if there are ever actual use cases needing this 🙂

**Comment by seancorfield** [comment]
Given XTDB has a proper `bool` type and seems to have an `int8` type, I can't imagine needing a dedicated `bit` type. This only came up as I was reworking the bit/bool/boolean tests in `next.jdbc` -- because MS SQL Server doesn't have a Boolean type (pretty much alone, out of all the DBs I know!).
